### ISSUE TITLE
[BUG] Nextstrain fails to render correctly in the latest version of Firefox on Windows

### ISSUE THREAD

**Issue by heliosfa** [nextstrain/auspice#1005]
**Current Behavior**  
When loading the Novel Coronavirus build at https://nextstrain.org/ncov in the latest version of Firefox (and Waterfox Classic) on Windows, many of the branches of the phylogeny tree are not rendered as per this screenshot:
![image](https://user-images.githubusercontent.com/6616536/77712306-53037080-6fcb-11ea-9965-a77716ff4401.png)

This issue has only started to occur in the last day (26/03/2020) and the tree used to render correctly on this platform/browser combination.

**Expected behavior**  
I would expect the tree to render correctly as it does in Chrome:
![image](https://user-images.githubusercontent.com/6616536/77712377-73cbc600-6fcb-11ea-8dff-1826c16415c2.png)

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Open https://nextstrain.org/ncov in the latest version of Firefox or Waterfox on Windows
2. See error  

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Windows 10 Enterprise 1809, Windows 10 Education N 1909, Windows 8.1 Enterprise
 - Browser:  Firefox 74.0 (64-bit), Waterfox Classic 2020.03.1 (64-bit)

**Additional context**  
This has been tested on multiple computers (including a disposable, non-persistent VM with the portable version of Firefox 74) with all add-ons disabled and with clean profiles.

Renders correctly in Firefox 74 and Waterfox Classic 2020.03.1 (64-Bit) on MacOS 10.14.6

**Comment by jameshadfield** [comment]
This bug was introduced via the SVG gradients applied in PR #947. Can confirm it works on Firefox 74 on MacOS, which implies it is OS specific.

**Comment by heliosfa** [comment]
@jameshadfield thanks for moving this to the correct repo and I'm glad it was easy to identify the cause - hopefully it's not too nasty to fix!

**Comment by jameshadfield** [comment]
I use MacOS (and we don't have any OS-specific testing) so thanks for raising this issue as we wouldn't have otherwise known about it! Hopefully someone who uses Windows can help with a fix (@ivan-aksamentov perhaps?)

**Comment by ivan-aksamentov** [comment]
@jameshadfield Sorry James, cannot help at this time. We are swamped with a project of ours.

But it's not a rocket science: I just run a Windows 7 guest in Virtualbox on my Ubuntu. Then run a browser in question and navigate to `http://10.2.2.0:4000` (or `5000`). This is the default address which maps to the host machine's localhost (on Ubuntu in my case), where auspice or nextstrain prod server runs. That's it. Hope you can nail it! :crossed_fingers:

**Comment by emmahodcroft** [comment]
Can confirm this is also true for me, on Windows 10, running an older Firefoxx 72.0.2 (64-bit)

**Comment by emmahodcroft** [comment]
For me, *some* of the gradients render: 
![image](https://user-images.githubusercontent.com/14290674/77741166-b9f94780-7014-11ea-9658-d762dd95f4d2.png)

**Comment by lmoncla** [comment]
This happened to me here,
<img width="1151" alt="Screen Shot 2020-03-27 at 4 06 19 PM" src="https://user-images.githubusercontent.com/8919808/77807390-ecbb3400-7044-11ea-86a7-7e7c8ba135c6.png">
 using Mac OSX 10.12.6, using Brave browser 1.4.96.

**Comment by gj262** [comment]
@jameshadfield ping me if you need help testing a fix i.e. I have a saucelabs.com account and can preview any changes you make. (I'd offer to help fix but my SVG knowledge is rusty.)

**Comment by cpsandbox** [comment]
Yes. This works on Linux/chrome/Firefox as well. @imoncla @heliosfa  Is this on the first render or after changing the color by?

**Comment by heliosfa** [comment]
@cpsandbox this is on first render and after changing the color by.

I can get the full tree if I change the "color by" to something like "Exposure History" that is more monochrome
![image](https://user-images.githubusercontent.com/6616536/77830231-0f218000-711f-11ea-9e99-04c88302b00a.png)

Playing about with the colour by options, some of the options with gradients render some of the branches some of the time. e.g. on this one coloured by Submission Date the yellow-grey gradients render, but the orange-grey one to Iceland/220/2020 does not:

![image](https://user-images.githubusercontent.com/6616536/77830276-5dcf1a00-711f-11ea-8587-5ce07588afbe.png)

Which branches render is not consistent by zoom level, e.g. zooming into the cluster of new Welsh cases:
![image](https://user-images.githubusercontent.com/6616536/77830414-27de6580-7120-11ea-9ae3-d92fefbab09b.png)

![image](https://user-images.githubusercontent.com/6616536/77830419-3298fa80-7120-11ea-9a69-44fa55be971f.png)

![image](https://user-images.githubusercontent.com/6616536/77830426-3b89cc00-7120-11ea-8dec-22ddcc6eb07d.png)

![image](https://user-images.githubusercontent.com/6616536/77830435-4e040580-7120-11ea-9fa9-9b153142c052.png)


Some of the branches render momentarily during a zoom onto a more specific part of the tree before disappearing.

**Comment by lmoncla** [comment]
@cpsandbox  on initial render

**Comment by jameshadfield** [comment]
Closing this as we've reverted back to non-gradient branches. Thanks for all the detailed reports here!
