### ISSUE TITLE
[BUG] Replace hard-coded /dist/auspice.bundle.js in index.html on auspice build --extend

### ISSUE THREAD

**Issue by terrycojones** [nextstrain/auspice#1014]
If you give a JSON config to `auspice build --extend config.json` and it contains a `serverAddress` I expected that server address would replace the hard-coded request to `/dist/auspice.bundle.js` in the resulting `index.html`.

**Comment by jameshadfield** [comment]
The `serverAddress` defines the address / prefix which the auspice client uses for client-server API requests, not the address the bundle is sourced from, as per https://nextstrain.github.io/auspice/customise-client/api#available-customisations. This extension could do with some improvements in general, and proposals are welcome.
