### ISSUE TITLE
Unnecessary require statement

### ISSUE THREAD

**Issue by avin-kavish** [nextstrain/auspice#1019]
What is the need for a require statement here? Can't we use good old ESModule imports?

https://github.com/nextstrain/auspice/blob/536f33ea42e3ccf1edd31545c9a68a21c6ab9b4a/src/index.js#L38

**Comment by jameshadfield** [comment]
> Can't we use good old ESModule imports?

Probably 🤷‍♂ - I can't remember why I did this (or it may not have been me) -- please submit a PR if possible 😄

**Comment by avin-kavish** [comment]
Yeah, I brought it up because you mention in #702 that tree-shaking may not be taking place. I know that files imported through `require()` can't be tree shaken, so I tried an import statement. But it only made a tiny difference just for that file... The rest of it seems to be tree shaken.

**Comment by raftar2097** [comment]
cc @jameshadfield  please have a look
