### ISSUE TITLE
[BUG] Search Strain Autocomplete is not sized properly

### ISSUE THREAD

**Issue by avin-kavish** [nextstrain/auspice#1024]
**Current Behavior**  
The search strain autocomplete is not sized propertly

![image](https://user-images.githubusercontent.com/48435155/77844302-42b5e600-71c3-11ea-99d8-c91c9d796e9d.png)

**Your environment: if running Nextstrain locally**  
 - Operating system:  Linux Mint 19.2
 - Browser:  Chrome latest
 - Version (e.g. `auspice 2.7.0`):

**Comment by clouraa** [comment]
The search input container is set at 80%, putting at 100% fixes the bug.
![image](https://user-images.githubusercontent.com/62800056/77852972-ce297a00-71b7-11ea-9056-90d8925ce6e0.png)
