### ISSUE TITLE
Is it possible to remove the Transmissions title & arcs from the map?

### ISSUE THREAD

**Issue by terrycojones** [nextstrain/auspice#1033]
Is there anything I can set to get rid of these?  Thanks!

**Comment by jameshadfield** [comment]
These are defined by the dataset, specifically what geographic resolutions have values inferred for the internal nodes in the tree. If you are generating your own build in `augur`, then you can control these by changing what traits you run `augur traits` for. For our current nCoV build, if you change the resolution to "division" or "location" then you won't get transmissions drawn as we haven't inferred this trait for internal nodes.

**Comment by terrycojones** [comment]
Aha, thanks! I wondered why they started popping up (I had changed this in the config).
