### ISSUE TITLE
Connecting Auspice to other tools

### ISSUE THREAD

**Issue by sherzinger** [nextstrain/auspice#1034]
Hi,

I've an unusual question. We're currently working on connecting Auspice to some other visualization tools for national COVID-19 related research. We managed to deploy it just fine and embedded it as an iframe together with the other tools. 

It being on the same domain than the other tools allows us to access the iframes (auspices) content directly, which in return allows us to connect some events from auspice to the other tools. As an example: Clicking the Phylogeny tree in Auspice could give us a list of strains, which then can be used to visualize them in other representations. 

To make it really short: I've got access to the DOM and `window` of Auspice.

Now the question: How do I go about accessing the currently selected list of strains? Is there somewhere a object accessible from `window` that holds the current selection? Or maybe some `__data__` in the DOM that could be easily extracted?

I'm fully aware of how hacky, undocumented, and unsupported this approach is, but I'd appreciate if you could point me to the right direction anyhow.

**Comment by tsibley** [comment]
Hi @sherzinger, fascinating idea!

Nearly all of Auspice's state is managed with Redux, which you won't be able to reach into easily at all. For example, this is the Redux reducer which manages the tree component's state: https://github.com/nextstrain/auspice/blob/master/src/reducers/tree.js.

Note also that Auspice only supports "selecting" a single strain at a time at the moment by clicking the tip on the tree. Is this the selected strain your looking for? Or are you looking for all strains currently visible?

If the former, then the easiest way might be to inspect the iframe's `window.location` and parse out the `s` query parameter, e.g. from something like `https://nextstrain.org/ncov?s=USA/WI-08/2020`.

If the latter, one way might be to crawl the DOM looking at the tree component's visible SVG nodes. This is bound to be pretty ugly, but it might work. You could also consider modifying Auspice to insert one or two [`window.dispatchEvent()`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) calls in the appropriate places that emit custom events with the data you need. Then you'd be able to register listeners for those events from the iframe's parent window.

I hope that helps!

**Comment by sherzinger** [comment]
They @tsibley, thank you very much for the kind response.

In our scenario it would be all information in a selected sub-tree. I was already able to listen to click events on the tree, which contains the node id as part of its attributes. However, that still requires me to parse the tree myself in order to get all of the information under the selection.

I was hoping I could avoid this, as you seem to have this logic already somewhere within Auspice. I.e. when you click on a branch, you see the tree and the world map adapting. If I could somehow manage to access this state that is passed between these components (I assume redux) then I could avoid duplicating that logic.

**Comment by jameshadfield** [comment]
This information is held in `reduxState.tree.visibility`. For a given node, you can query its visibility via `visibility[node.arrayIdx]`.
