### ISSUE TITLE
Color-by changes result in duplicate (expensive) function calls 

### ISSUE THREAD

**Issue by cpsandbox** [nextstrain/auspice#1035]
**Current Behavior**  
When choosing a different color by method (clade, administrative area, etc.) change.js in components/tree is called twice. 

**Expected behavior**  
This should only get called once. 

**How to reproduce**  
As a developer add logging statement in change.js indicating the properties to be updated. 
Use the UI to change the colorBy method. 
The logging will indicate two passes through change.js 

**Possible solution**  

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Linux
 - Browser:  Chrome/Firefox

**Your environment: if running Nextstrain locally**  
 - Operating system:   Linux
 - Browser:  Chrome/Firefox
 - Version (e.g. `auspice 2.7.0`):  

**Additional context**  
Running in developer mode.

**Comment by jameshadfield** [comment]
Good find Clint -- `change()` is an expensive function and getting rid of unnecessary calls here will be a good win for tree performance. I'm sure there are other functions (and react render calls) which are unnecessarily called & there are obvious performance wins here.

**Comment by andressrudqvist** [comment]
Hi,
I would like to work on this issue. 
I've followed the instructions to reproduce the bug, and now I'm looking for the double invocation of `change()` method.
Regards,
Andres
