### ISSUE TITLE
Buttons in map don't handle longer text well

### ISSUE THREAD

**Issue by joachimschmidt557** [nextstrain/auspice#1038]
**Current Behavior**  

Some translations have longer texts for the buttons in the map view.

![image](https://user-images.githubusercontent.com/28556218/78244221-76f01600-74e5-11ea-8a3c-e209ce58d1f4.png)

**Expected behavior**  

Correct sizing of the buttons

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Open https://nextstrain.org/ncov or some other dataset
2. Switch language to German

**Possible solution**  

- Make size adapt to text
- Use icons (e.g. from font awesome) instead of text

**Your environment: if browsing Nextstrain online**  
 - Operating system: Linux
 - Browser: Firefox

**Your environment: if running Nextstrain locally**  
 - Operating system: Linux
 - Browser: Firefox
 - Version: from `master` branch

**Additional info**  

If either solution is chosen, I can work on a PR for this.

**Comment by jameshadfield** [comment]
Moving from a hardcoded button width to a size-adapts-to-text solution is preferable. Thanks Joachim!
