### ISSUE TITLE
Add automated bundle size checks to PRs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1039]
Following from #1018 it would be great to report bundle size changes in each PR. Perhaps something like [bundlesize](https://github.com/siddharthkp/bundlesize) but I haven't looked into it.

**Comment by avin-kavish** [comment]
Hmm... Seems like it needs access to the build output to calculate the size, I think you will have to follow the steps [here](https://github.com/siddharthkp/bundlesize#build-status-for-github) and let me know where the build output goes in Travis CI. I'll try to do a PR for this.

**Comment by avin-kavish** [comment]
Ran into a speed bump with this, bundlesize checks each file individually, which is not what we want I think.

![image](https://user-images.githubusercontent.com/48435155/78331611-0b20b280-75a4-11ea-912b-f508742f8ea6.png)

**Comment by hydrosquall** [comment]
This doesn't help with the split files problem, but I've used this free SaaS tool on public github repos before, perhaps it could be a quick win for us even if it doesn't create a gitlab check the way `bundlesize` does.

https://www.bundle-analyzer.com/

If total budget is our concern, perhaps this task could be tackled by writing the budget check as a custom rule via a Dangerfile, which sums the sizes of the relevant chunks and can report the result back as a Github check.

https://danger.systems/js/guides/getting_started.html
