### ISSUE TITLE
404 error with drop-down menu

### ISSUE THREAD

**Issue by neavemj** [nextstrain/auspice#1044]
Hello and thanks for the great software! I'm just having an issue with 404 errors when changing the drop-down menu options as below:

**Current Behavior**  
When running auspice either locally ("auspice view --datasetDir auspice") or from a locally-running server, selecting a different option in the top drop-down menus cause a 404 error. I think this is because the full URL to the dataset is not being retreived, only a partial URL. I think it also only occurs when the virus build has more than one part to the URL, such as strain or segment.
 
**Expected behavior**  
Expect a different dataset to load when drop down menu is changed. For example, selecting a different virus should load that dataset

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Run "auspice view --datasetDir auspice" on a set of jsons generated with augur
2. Open the local server in a webpage (localhost:4000)
3. Select a different virus from top drop-down menu
4. A 404 error page is displayed. 

**Possible solution**  
I'm pretty sure this is because the full URL is not retreived. For example, if I try to load a "BTV" build by clicking on the drop-down menu, auspice tries to load this URL:
localhost:4000/BTV
However, the correct URL is
localhost:4000/BTV/segment1

I think I somehow need to tell auspice to load the full path to a specific segment when a virus is selected.

**Your environment: if running Nextstrain locally**  
 - Operating system: linux / xcfe
 - Browser:  Firefox
 - Version: auspice v.2.11.4

Thanks again - any help much appreciated!

Matt.

**Comment by jameshadfield** [comment]
Hey Matt - you're correct, and it would be great to have this fixed. This is bug #698. I'll shift your comment over to there :)

**Comment by neavemj** [comment]
Ah sorry James! Thought I'd had a good look through the issues - obviously not hard enough!
