### ISSUE TITLE
Make strain mutation data available via file download and/or API GET request

### ISSUE THREAD

**Issue by cornhundred** [nextstrain/auspice#1052]
**Context**  
Thanks for the great resource. We would like to try and visualize this data using our interactive heatmap Clustergrmmer2 - e.g. a heatmap with strains as columns (with clade categories, and hierarchically clustered using phylogenetic tree) and mutations/metadata as rows linked to a world map. We have a similar example set up using Citibike data here https://github.com/cornhundred/citibike-clustergrammer2 and see GIF below:

![small_gif](https://user-images.githubusercontent.com/8352840/78839240-14f04e80-79c6-11ea-91bb-a2a81f9beb86.gif)

**Description**   
We would like to obtain the mutation data (nucleotide and AA) for the strains in order to generate the heatmap, but the current downloads do not appear to include this information (e.g. nextstrain_ncov_global_metadata.tsv).

**Examples**  
The mutation data is available on mouseover in the application. 

**Possible solution**   
The mutation data could be made available in the metadata as an additional column (e.g. semi colon separated list of mutations that show up on mouseoer). Also, this latest data could be made available via an API.

**Comment by jameshadfield** [comment]
Hey Nicolas. I understand your desire here. To obtain this information please register with [GISAID](https://platform.gisaid.org/epi3/) to obtain the original genomic data & please adhere to their conditions of data sharing when using GISAID data. You are most welcome to run our [ncov pipeline](github.com/nextstrain/ncov) to align & identify mutations in the data. Good luck!

**Comment by cornhundred** [comment]
Ok, thanks for the help :D
