### ISSUE TITLE
invalid css (minor)

### ISSUE THREAD

**Issue by rleir** [nextstrain/auspice#1081]
**Current Behavior**   
chrome 'inspect' shows invalid css.
In Elements tab, click on the <body class= .. > line
In styles, scroll to the bottom and find 'color: "#333"; '

**Expected behavior**  
No invalid css

**Possible solution**  
please assign to me, I have the fix

**Your environment: if running Nextstrain locally**  
 - Operating system:   Ubuntu
 - Browser:  Chrome
 - Version (e.g. `auspice 2.7.0`):  Master today

**Additional context**  

Hi all, 
this is very minor. please feel free to ignore it.
thanks
Rick

**Comment by rleir** [comment]
global.css line 5
I am testing it ASAP

**Comment by rleir** [comment]
James, to rebuild I would say "auspice build --verbose"? After which, to get the new build live I would say "auspice develop --datasetDir data"? Is there any other step in this? I don't see my source changes having any effect on the runtime. There are some build warnings, maybe I should track them down. Thanks -- Rick

**Comment by jameshadfield** [comment]
Yup that's right (see https://nextstrain.github.io/auspice/introduction/install#installing-from-source for more). It may be that the CSS is coming from a dataset, not auspice itself? (Dataset JSONs can define hex values for tips in the tree, for instance). If you put up a PR i'd be happy to take a look
