### ISSUE TITLE
Better error messages when HOST env variable is set

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1086]
There have been a number of cryptic error messages from users running `auspice develop` or `auspice view` along the lines of

```
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: getaddrinfo ENOTFOUND x86_64-apple-darwin13.4.0
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1448:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:17)
```

@barneypotter24 and I were able to track this down to occuring when the `HOST` env variable is set (see [develop src code](https://github.com/nextstrain/auspice/blob/master/cli/develop.js#L37)).

It can be fixed by running `HOST="localhost" auspice develop` or similar.
It can be recreated by running `HOST="x86_64-apple-darwin13.4.0" auspice develop` or similar.

We need to catch this error for both `auspice develop` & `auspice view` and print a message explaining that it may be caused by having a HOST env variable set and indicating how to fix it.

**Comment by AlyxMoon** [comment]
Hey, I've been looking through the app today and it looks really neat.  I was able to replicate this issue and I'd be happy to get up a PR to address it.

**Comment by jameshadfield** [comment]
Sounds great @AlyxMoon, thanks!
