### ISSUE TITLE
Devel hot updates

### ISSUE THREAD

**Issue by rleir** [nextstrain/auspice#1093]
Hi all,
I git-cloned and followed the instructions to build and run in devel hot-update mode. None of my source changes caused updated pages in the local browser. 
The doc pages are:
https://github.com/nextstrain/auspice/blob/master/docs/introduction/install/index.html
https://nextstrain.org/docs/getting-started/local-installation
Section: "Install Augur & Auspice with Conda (recommended)"

https://github.com/nextstrain/auspice/blob/master/docs/introduction/how-to-run/index.html

https://github.com/nextstrain/auspice/blob/master/README.md

The problem I ran into was that webpack was not running the code in the git-clone directory tree. It was running the code under the miniconda directory tree (and running the previous version of the source).  Now, my fix: with the git master source copied into the miniconda directory tree, hot updates work fine. Very nice!

Would you like to assign this issue to me? I would probably describe how and why to make a symbolic link in the miniconda directory so webpack would see the current git source. But the core developers could very well have a better way (and I admit to not having read all the documentation).
Thanks 
Rick

**Comment by rleir** [comment]
James, 
No, the symbolic link I suggested is not good. The 'auspice build' fails with a confusing error. We need a real src tree under miniconda, so I would describe some other way of getting it set up. What do you do yourself to get the src tree into place under miniconda? Perhaps mv the 'git clone' directory into place?
thanks -- Rick

**Comment by rleir** [comment]
Hi James
That is the answer for me, I moved the git clone directory tree under miniconda. 
cheers -- Rick

**Comment by jameshadfield** [comment]
Hi Rick. The `auspice develop` command is only intended to be used in conjunction with modifying the source code of auspice for development purposes. I've only ever used it with a from-source install of auspice ([docs here](https://nextstrain.org/docs/getting-started/local-installation#install-auspice-from-source)). 

I think modifying symlinks to conda installs, or trying to modify auspice source code which is part of a conda install, should be discouraged.

**Comment by rleir** [comment]
Hi James, @jameshadfield yes, I am using it for development. When I was installing, I saw that Conda was recommended and yes, it is convenient. I followed the instructions you linked to and got in a situation where none of my source changes caused updated pages in the local browser.

As you say, putting the git development directory in the miniconda tree is questionable. I take it that you don't use Conda? Or that you have another way use Conda and develop in a git directory?

Let's not bother about this issue, I must have done something wrong while installing.
Thanks
Rick

**Comment by jameshadfield** [comment]
I use conda, but conda's a bit of a red-herring here I think.

The docs you liked to, and I believe followed, install auspice via `npm install --global auspice`, which installs it from the npm registry and into the conda tree (if using conda). This install method shouldn't be used for development.

The "from-source" installation, which can be done from within a conda environment, is recommended for development purposes.
