### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by hnsnsjkf** [nextstrain/auspice#1100]
please help me, when i try to install auspice, i got this error ,my environment is windows+powershell.
<img width="580" alt="捕获" src="https://user-images.githubusercontent.com/30283492/80866547-dfd3d500-8cc1-11ea-8639-71530d91a228.PNG">

**Comment by joachimschmidt557** [comment]
The scripts in the `scripts/` directory depend on `bash` which is probably not installed on your windows machine.

**Comment by emmahodcroft** [comment]
For Windows install, I'd recommend trying to [Windows Subsystem for Linux instructions](https://nextstrain.org/docs/getting-started/windows-help) on the Nextstrain website, or using the [Docker install instructions](https://nextstrain.org/docs/getting-started/container-installation).

**Comment by hnsnsjkf** [comment]
when i use the docker，after entering the nextstrain check-setup，it show me this . Is it right?
![image](https://user-images.githubusercontent.com/30283492/80867957-e1090000-8cc9-11ea-9678-67d5a11ab550.png)

**Comment by jameshadfield** [comment]
@hnsnsjkf that should be ok & allow you to run `nextstrain view` which will run auspice from within a docker container.

Auspice isn't tested under windows powershell, but we have had success with  WSL as Emma said. 

Please reopen if you have problems with `nextstrain view`
