### ISSUE TITLE
about creating transmission lines

### ISSUE THREAD

**Issue by islekburak** [nextstrain/auspice#1121]
It is not shared that how auspice can visualize the virus tracing yet. I am trying to read your react codes but it is hard to understand how are transmission lines created. We can create traits.json file using augur trait module but which data does auspice retrieve from this traits.json (or the final json file -main+tree+meta-) is unclear. Does it take only values of confidence and entropies for selected meta labels (i.e country) to create transmission lines? What is the further statistical methods if we should use just these 2 data (confidence and entropies).
I really wonder if there is a way to create a matrix of transmission rates from the data that auspice uses (confidence and entropy information) as treetime module in augur (by creating GTR model -i.e P & Q matrices-).
The other thing is: How is the connection between states (i.e countries) created? If we think about a 2D matrix like GTR model, every column and rows will have a connection value, but it does not have to be the same for origin and destination points for virus tracking. Let's say a virus can originate from the "A" point and goes to the "B" point, and then "C". In this thought the connection lines will appear between A and B and C, there will no connection between A and C. So, does auspice change the transmission data to the identity matrix?

**Comment by jameshadfield** [comment]
Hi @islekburak -- there are two parts to understanding the transmissions shown in auspice.

Let's start with the auspice part: any dataset JSON with `node_traits` set on internal (as well as terminal) nodes of the tree will have transmissions drawn on the map. Auspice is agnostic as to how these internal values were calculated. Confidence & entropy values are currently not used for the map visualisation, but are communicated in the tree visualisation via the on-hover info-box and color saturation of the branch, respectively. 

`augur traits` is one way to create these internal node values (there are others). It uses a GTR model as implemented by TreeTime. In your thought experiment, if no other samples are collected from state "B" then the inferred movement will be between "A" and "C". You should be able to see the inferred transition matrix (and other info) inside the resulting JSON (from `augur traits`). 

Please feel free to reopen if you have further questions.
