### ISSUE TITLE
Strain grouped in correctly when viewing in divergence

### ISSUE THREAD

**Issue by gurkhali** [nextstrain/auspice#1124]
**Current Behavior**  
When viewing in rectangular view EPI_ISL_426067 is being grouped with EPI_ISL_424319 in the same Phylogeny despite its nucleotide mutations. This is the only strain that I have found to show the behavior but I have not looked for more. I was looking at json file for some work that I was doing and saw this by accident.
 
**USA/ID-UW-4378/2020**
Collection date	2020-03-28
Authors	Roychoudhury et al
Clade	A2a
Country	USA
Admin Division	Idaho
Division of exposure	Idaho
Host	Human
Originating Lab	UW Virology Lab
Submission Date	One month ago
Region	North America
Submitting Lab	UW Virology Lab
GISAID EPI ISL	426067

**USA/ID-UW-1935/2020**
Collection date	2020-03-22
Authors	Roychoudhury et al
Clade	A2a
Country	USA
Admin Division	Idaho
Division of exposure	Idaho
Host	Human
Originating Lab	UW Virology Lab
Submission Date	Older
Region	North America
Submitting Lab	UW Virology Lab
GISAID EPI ISL	424319

**Additional context**  
When I hover, I see "Gaps (-): 7"

**Comment by gurkhali** [comment]
This is when I am looking at https://nextstrain.org/ncov/global?m=div

**Comment by emmahodcroft** [comment]
Hi @gurkhali ! Thanks for reaching out!

I am sorry this has confused you. When we make the phylogenies for SARS-CoV-2, we do not consider gaps - they are ignored. 
We do display them, however, as some of them may be real and be of interest, so we want to ensure people can be aware of them in the mouse-over view. 

I hope that clarifies why having 7 gaps is the same as having no gaps in the tree!

**Comment by gurkhali** [comment]
@emmahodcroft thanks for clarifying. Just so I understand, what defines a gap for these strains?

**Comment by emmahodcroft** [comment]
We take the sequences as they are, so gap characters are `-` symbols in the nucleotide alignment. 

(`N` characters are also ignored in the reconstruction of the tree, but they are not interpreted as gaps - just `N`)
