### ISSUE TITLE
Internal nodes without mutations? 

### ISSUE THREAD

**Issue by biocyberman** [nextstrain/auspice#1125]
Hi
This may be a bug, a feature, or a mistaking from myself. So not sure which type of issue to submit. 

I created a custom clades.tsv, ran data processing with `augur`, then view the data with `auspice`. On this tree, there are some internal nodes that do not have mutations(see screenshot), so I wonder why. Is it because they are filtered away after some thresholds, and the tree is calculated before this filtration step? Otherwise I don't understand how a branch can be made without sequence changes. 

![image](https://user-images.githubusercontent.com/447942/81919980-d1968a80-95d8-11ea-8cd4-2b88b7c3a41c.png)

**Comment by emmahodcroft** [comment]
Hi @biocyberman ! Thanks for reaching out! Yes, this is something that's a little confusing about the two tree views in Auspice.

The view you're looking at now is 'Time' - so here the dots (samples) are plotted by the sampling date, and the algorithms in augur (`refine` call in particular, which uses `Treetime`) try to estimate when the different samples had a common ancestor. They must have a common ancestor in the past, even if that ancestor was identical - even if there were no mutations. Often, the confidence intervals on these 'timing of the ancestor' estimates are large, as the mutation rate of SARS-CoV-2 is not incredibly fast (only a couple of mutations per month by which to estimate), and sampling is far from comprehensive. So, these estimates must also be interpreted carefully. However, ancestors do not always have mutations, and the time view is trying to reconstruct when ancestors existed, even if they did not have mutations!

The view you will find perhaps more intuitive is to switch to 'Divergence' view. Here the tree will show the tree only by mutational differences, You will notice it collapses' quite a lot. And all the nodes will have mutations here. This is a much more robust visualisation of the tree, as it is based only on mutations without trying to reconstruct past events in time. 

Both are useful views, but they must each be interpreted in their own way! I hope this helps explain, though!

**Comment by biocyberman** [comment]
Excellent! Thank you @emmahodcroft . I know better now what is going on.

**Comment by biocyberman** [comment]
@emmahodcroft This might be more relevant to ask over `augur` repo, but the two are so close to each other and in this context it may be easier to understand: 

I am interested in fetching all mutations for a strain/tip compared to the reference, and also all mutations on each internal node between a tip and the root. As you explained about the Time tree, it would be more appropriate to use the `tree_raw.nwk` file. However, there a couple of things:

1. All steps in the standard workflow use the Time tree after the `refine` step: `ancestral`, `translate`, `traits`. Especially `ancestral` and `translate` step produces `nt_muts.json` and `aa_muts.json` respectively. So I can't use the `tree_raw.nwk` with these `.json` files (node names are different, tree topologies are different), can I?

2. Would it make sense to parse the raw tree and compute the mutations along the tree, or the `nt_muts.json` and `aa_muts.json` files can still be used with the raw tree somehow?

3. Auspice's `divergence` tree has unit of `mutations`, and the `tree_raw.json` has unit of branch_length of distance. So are they identical  or do they have same topology?

**Comment by emmahodcroft** [comment]
Hi @biocyberman - you're best traversing either the `tree.nwk` and `nt_muts.json` files (together you can walk through the tree and see the mutations on each node) or just traversing your final output JSON file (`ncov.json` or similar). In the latter, the tree and mutations are both in the same file - you can traverse the tree and count up the mutations on every node. If you use the `ncov.json` you can also gather both nucleotide and amino-acid mutations.

I hope that helps!

**Comment by jameshadfield** [comment]
Emma is absolutely correct -- mutations in augur (and auspice) are defined per-branch, so any questions relating to comparing two non parent-child nodes in the tree will require a traversal. Please note that for a given analysis the root of the tree may not be identical to the reference used. 

> Would it make sense to parse the raw tree and compute the mutations along the tree, or the nt_muts.json and aa_muts.json files can still be used with the raw tree somehow?

This approach will work, but you shouldn't use the raw tree (the output from `augur tree`) here as it does not have internal node names and therefore you won't be able to match it up with the names in `nt_muts.json` etc. Rather use the tree from `augur refine` (often just `tree.nwk`). 

> Auspice's divergence tree has unit of mutations, and the tree_raw.json has unit of branch_length of distance. So are they identical or do they have same topology?

Similarly to above, the raw-tree is only used for input to `augur refine`. The newick tree out of `augur refine` provides the topology you see in auspice.

**Comment by biocyberman** [comment]
Fastasic! Thank you Emma and James again.  The answers really helps to avoid incorrect usage of the information and confusion.
