### ISSUE TITLE
color-by Genome position options

### ISSUE THREAD

**Issue by rleir** [nextstrain/auspice#1130]
**Context**  
How would this feature help you? What would it enable you to do?  
Ease of color-by genome position selection. 

**Description**   
A clear and concise description of what you want to happen  
In the left panel tree options you can select color-by -> Clade/Date/Genotype/etc
When you select Genotype then you have to select E/M/N/Orf10/etc
Then you have to select a numeric position (1 - 222 in the case of M). 
Most positions do not give you a 'useful' display. Would it be a good idea to present a list of useful positions in a drop-down?  If you like this feature, please vote by commenting.

**Examples**  

**Possible solution**   
The 'useful' options for each genotype would probably be computed server-side and downloaded with the data.

**Comment by jameshadfield** [comment]
Could you say more about how you would select these "useful" positions?

In my experience, the dropdown is good when you know _a priori_ the mutation of interest (and it's important that it allows you to select any valid position, not just from a curated subset). Mainly, I use the diversity panel (below the tree/map) which visually conveys what positions have high entropy (or a large number of events) which is often a proxy for "useful" in this context.

**Comment by rleir** [comment]
OK, you say "it's important that it allows you to select any valid position, not just from a curated subset" so my suggestion is bad. But what if your data only contains mutations for a certain subset of the valid positions? Why allow the user to try positions where the data contains no mutations?

Let's just close this issue, I will learn how the diversity panel works. No worries.

**Comment by jameshadfield** [comment]
> Why allow the user to try positions where the data contains no mutations?

Right now this is somewhat uninformative, but in the future we'd like to show the (unchanging) base at this position.

**Comment by rleir** [comment]
Aha! Now I have looked at Orf8, site 84. But it was not easy to get there. If this is a minor issue, let's move on.
Thanks -- Rick
