### ISSUE TITLE
npm version ?

### ISSUE THREAD

**Issue by biocyberman** [nextstrain/auspice#1141]
I am developing some features for auspice, and node version and its packages use newer version, for example nodejs version `12.16.x`. So I wonder is there any specific reason to keep current `engines` for auspice with `"node": 10.8.x`? More directly, will a PR with newer node version be accepted or what I need to test to make sure that things function correctly?

**Comment by jameshadfield** [comment]
Newer node versions work with auspice -- nextstrain.org builds it under v12, I often build it using v13 locally. I'd be in favor of something like
```
  "engines" : { 
    "node" : ">=10.8 <=13.6" 
   }
```

**Comment by biocyberman** [comment]
That makes thinks much simpler :) I was trying to be strict with node v 10.8 but some parts didn't work.
