### ISSUE TITLE
Required nodejs version issue

### ISSUE THREAD

**Issue by huaigulin** [nextstrain/auspice#1161]
Hi,

I noticed in the README, it says "Install auspice for use as a global command. This requires nodejs 10+." 

But in [package.json](https://github.com/nextstrain/auspice/blob/master/package.json), the required node version is `10.8.x`. I think the correct way of saying "requires nodejs 10+" is `>=10.0.0`. 

Updating package.json might introduce breaking change, so should we update README to reflect the true requirement in package.json?

**Comment by jameshadfield** [comment]
Thanks @huaigulin, PR up to relax this requirement. Node 10.8 is a couple of years old now so I don't think there's need to specifically support previous versions, although I think it's likely they'd work.
