### ISSUE TITLE
Metadata not showing in "Color by" column when interactively dropping tsv/csv into browser

### ISSUE THREAD

**Issue by Silberbaer** [nextstrain/auspice#1174]
When loading a Tree in Auspice and adding Metadata according to the documentation [here](https://nextstrain.github.io/auspice/advanced-functionality/drag-drop-csv-tsv) by dropping it into the browser correctly identifies all the columns and rows and adds them to the tree nodes, but does not add any of the columns to the "Color By" selection box. I tried csv and tsv files and both are being correctly read and the data added to tree as evidenced by the popup message and the data showing up on the appropriate nodes.

I am on Windows 10 with Google Chrome Version 83.0.4103.106 (64bit)

If there is an easy workaround I would also be glad if someone can tell me how to add metadata to color into the tree file from the start.

**Comment by emmahodcroft** [comment]
Hi @Silberbaer - sorry to hear you're having trouble! I'm not sure why adding things via drag-and-drop isn't working with the "Color By" selection - @jameshadfield might be able to help with this better than I can!

However, if you're happy for this information to go into the main metadata file, that might be an easier way for your to proceed. You can use a text-editor to add a new column to the `metadata.tsv` file. You can call this whatever's appropriate, and ensure that every line has an entry - either some word or value, empty (but be sure there's a `tab` before it!), or `?` (note this would mean if you run `traits` on this column, it will be inferred). 

Once you have that new columns into your metadata file, you can have it show up in your auspice build by modifying the file in `config/auspice_config.json`. You'll need to add an entry that matches up to your new trait - you can see how to do this [here](https://github.com/emmahodcroft/sarscov2-tutorial/blob/master/docs/customizing-visualization.md#adding-custom-metadata-fields-to-color-by). 

I hope that helps!

PS - If you want to keep your metadata file updated with the latest available from GISAID, then you might want to write a script add this column - then you can update the file and 're-add' the column to the new version very easily!

**Comment by Silberbaer** [comment]
Hi @emmahodcroft - Thank you for this workaround. I got it to work with the whole metadata file by specifying all the columns in a auspice_config.json and have also all the colorings available in the webinterface.

**Comment by emmahodcroft** [comment]
I'm so glad to hear it's working for you!

**Comment by jameshadfield** [comment]
@Silberbaer -- the CSV/TSV not working was a bug with auspice which has been fixed in v2.17.1. The new version should be up on nextstrain.org very shortly!
