### ISSUE TITLE
Drag and drop tsv metadata not adding color by option to dropdown

### ISSUE THREAD

**Issue by eharkins** [nextstrain/auspice#1176]
**Current Behavior**  
From @trvrb :
> drag-and-drop metadata is working on auspice.us, but is perhaps broken on nextstrain.org.

**Expected behavior**  
Drag and drop should work to add a color by option to the dropdown upon dropping and parsing a TSV. This works on auspice.us

**How to reproduce**  
Reproduce bug:
1. On current master, run `auspice view --datasetDir examples` and go to `http://localhost:4000/minimal/v2`
2. When that has loaded, drag and drop https://gist.github.com/eharkins/c89ae185f164c2af3ae6668ffa8f55c2
4. Note that `collection` is *not* an option to select in the sidebar's Color By dropdown

Reproduce correct behavior:
1. Go to auspice.us 
2. Drag and drop https://github.com/nextstrain/auspice/blob/master/examples/minimal_v2.json 
3. When that has loaded, drag and drop https://gist.github.com/eharkins/c89ae185f164c2af3ae6668ffa8f55c2 
4. Note that `collection` is an option to select in the sidebar's Color By dropdown

**Possible solution**  
Differing versions of auspice (2.17.0 in nextstrain.org and 2.12.0 in auspice.us) are my best guess as to the difference in behavior - several hundred commits in auspice separate the two. One way to solve this is to try and find the commit that broke it, another way is more directly debugging the current code.

**Your environment: if browsing Nextstrain online**  
 - Operating system:  macOS High Sierra 10.13.4 (17E199)
 - Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by jameshadfield** [comment]
It used to (and still should) work in auspice by itself, so bisecting (perhaps from 2.12 which auspice.us is running) should identify the commit which breaks it.

**Comment by jameshadfield** [comment]
Bisecting indicates this is 20d8439c6b618bfb4df629d738332033816d75ed, which makes sense: the new coloring is being correctly added to the redux state as an available option, but the drop-down is not being updated due to the `shouldComponentUpdate` code introduced in that commit. This also explains why the TSV-derived color-by option magically appears in the dropdown once you change the color-by to any one of the original options.

**Comment by trvrb** [comment]
I believe this was resolved?
