### ISSUE TITLE
shift,option+mouseWheel zoom bugs in entropy panel

### ISSUE THREAD

**Issue by eharkins** [nextstrain/auspice#1179]
**Current Behavior**  
Breaking this out from #1145
> Zooming the entropy panel by the ctrl+mouseWheel does not update the URL query. Not sure what (if any) dispatches are occurring on this action

[relevant code here](https://github.com/nextstrain/auspice/blob/master/src/components/entropy/entropyD3.js#L526) 

It looks like the keys that allow you to zoom on the entropy panel by scrolling are actually `shift` and `option`. 

`shift` + scrolling doesn't update the zoom visually or in the query for me.
`option` + scrolling updates the zoom visually but not in the query as described in #1145 

**Expected behavior**  
If it is working, the bar should change in size (and the query should update with [`gmin` and/or `gmax`](https://nextstrain.github.io/auspice/advanced-functionality/view-settings#url-query-options)).

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Go to https://nextstrain.org/flu/seasonal/h3n2/ha/2y
2. On the entropy panel, hold either `option` or `shift` key and scroll while the mouse is over the grey bar:
![Screen Shot 2020-06-26 at 4 14 48 PM](https://user-images.githubusercontent.com/12140437/85908022-4eb44280-b7c8-11ea-8375-98ee1ffa536f.png)

3.  see expected behavior. the bug looks like either nothing happening or query not updating

**Your environment: if browsing Nextstrain online**  
 - FWIW I am using external mouse not laptop touch pad.

**Comment by hangzho** [comment]
Hi @eharkins, I'm new to this project. I've created a potential solution in my PR to fix this issue. Let me know if you have any questions or suggestions. Thanks.
