### ISSUE TITLE
Add a guest post to your website.

### ISSUE THREAD

**Issue by IamAkku** [nextstrain/auspice#1195]
As I gone through the website there is no option for guest post. I think this website must have a guest post option so that people coming to this website can write blogs and give their vailuable contribution as opinion or by writing  blogs related to the scientific and public health potential of pathagen genome data.After a guest post the owner of website may review their blogs regarding any mentioned topics and if they will be convenient with that blog they can approved it on their website so that it can be visible to others and will be helful for people  and also for their website to explore more. So I wanted to add a guest post on this website and also some option for topics so that people can choose to write their blogs on the website.

**Comment by emmahodcroft** [comment]
Dear @IamAkku, Thank you for your idea and reaching out, but this isn't a direction we're going to be introducing. We are primarily not a blogging or posting site, but instead focused on phylogenetic visualisation, with some commentary on what that means, and tools and information for how to make use of our software and services. Best wishes.
