### ISSUE TITLE
Add "Label By" dropdown for labeling nodes by attributes other than `name`

### ISSUE THREAD

**Issue by batson** [nextstrain/auspice#1201]
**Context**  
We would like to be able to label nodes with attributes other than their `name`. Uses:

* A user has drag-and-dropped a file linking public identifiers to patient names onto auspice, and they would like to label the nodes by the patient names.
* Nodes have multiple name-like fields, such as the public GISAID name, a lab accession number, and an ID used by a partner institution. It would be useful to toggle between them.
* When an attribute has too many values for the color to be legible, as is the case with Admin Division in current ncov builds, labels with that attribute would be easy to read.
* A user who wants to see two attributes simultaneously could use one as a color and the other as the label. For example. facility name and worker/resident status. Currently, one has to rapidly toggle the color and squint to compare two sets of attributes at once.

**Description**   
An additional dropdown box called "Label By", under "Color By", in the navigation panel on the left, with the default set to `Name`. Attributes would appear in the drop-down. When selected, the nodes would be labelled by the value of the attribute instead of the current `name` field.

Open question: should these be specified separately in the JSON as a `labelings` field? For backwards compatibility, we could also use the union of `filters` and `colorings` OR simply the full set of node attributes if `labels` is not specified. Many name-like fields might not make sense as colorings or filters, so having an option to specify a might offer a better user experience.

**Comment by sidneymbell** [comment]
Bumping this :)

**Comment by allenkj2** [comment]
I would love to see this as well. It would be great to be able to choose a label, and also great to be able to turn off labels altogether if things are too cluttered.

**Comment by jameshadfield** [comment]
It's in the queue 😉 

> and also great to be able to turn off labels altogether if things are too cluttered

Yup -- this is #916 -- also in the queue 😉
