### ISSUE TITLE
setting "color_by" in the json file to "clade" doesn't work on Auspice.us; but setting it to "location" does work

### ISSUE THREAD

**Issue by jaredroach** [nextstrain/auspice#1223]
**Current Behavior**  
A clear and concise description of what is happening / what the bug is.  

when I edit the json file for auspice from

the default
 "color_by": "division",
to
 "color_by": "location",
then I get the nodes colored by location
which is good and expected

but when I edit it to 
 "color_by": "clade",
I get the nodes colored by country
I can manually change it to clade once the file is loaded

**Expected behavior**  
A clear and concise description of what you expected to happen instead.  

I expect that if  "color_by": "clade", 
is set, then the nodes will be colored by clade

Note that I am not loading it with a specific parameter like an html code to override this behaviour

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Drag a json file onto auspice.us with the value "color_by" set as described above

**Possible solution**  
I think this is something to do with the auspice json interpreter

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Mac
 - Browser:  Chrome

**Comment by jameshadfield** [comment]
Hi @jaredroach - this should work if you use `"color_by": "clade_membership"`. 

The reasoning is a bit of a historical tangent, but the [key (in the JSON) for clades](https://docs.nextstrain.org/en/latest/augur/docs/releases/migrating-v5-v6.html?highlight=clade_membership#colorings) is actually `clade_membership`. One way of seeing this is to select "clade" as the coloring within auspice and notice that the URL query key changes to `?c=clade_membership`

Please reopen if this doesn't fix things!
