### ISSUE TITLE
Auspice installation Error from source

### ISSUE THREAD

**Issue by nitha26** [nextstrain/auspice#1227]
Hi,
I tried to install auspice from source in centos7. I followed the steps described in https://nextstrain.github.io/auspice/introduction/install (Installing from Source).

I am not able to install auspice system-wide. Please help me to install @jameshadfield . Attaching the command line used and installation log file.
[auspice.txt](https://github.com/nextstrain/auspice/files/5483138/auspice.txt)

Thank you.

**Comment by jameshadfield** [comment]
I would guess it's due to a missing space in the install command -- instead of `npm install -g.` we want `npm install -g .` -- if that's not it then I'll dig deeper!

**Comment by nitha26** [comment]
The problem was because of ``node: 'v15.0.1', npm: '7.0.3'``. I have downgraded the version and now aupice is installed and it works. @jameshadfield Thank you!

**Comment by jameshadfield** [comment]
Glad you got it working! Nodejs 15 isn't yet on conda for MacOS but when it is I'll make sure auspice works on v15

**Comment by nitha26** [comment]
Hi @jameshadfield 
I would like to do my interest pathogens phylogenetic analysis using NextStrain tool. From the tutorial, I understood basically we need 2 files to start Nextstrain. 1. sequence.fasta and 2. Metadata. I am confused about what type of sequence should be download from NCBI (whether it is a Complete genome or CDS)? 
2. What is the augur filter, in what bases I have to exclude the sequence?
3. how this "config" folder files to be created? whether they automatically created while running NextStrain Steps?

Sorry, I couldn't understand properly how to use nextstrain efficiently when I am are trying to build a new pathogen.  Could you please guide me on how to do it?

I am able to run zika tutorial, but create my own.

Thank you.

**Comment by jameshadfield** [comment]
Hi @nitha26 -- Congratulations on running the zika tutorial -- my suggestion would be to adapt that to use your data, and then continue modifying rules as necessary.  I think a lot of the questions you asked are scientific ones and depend on the pathogen you are analysing and what kind of analysis you want to do. 

P.S. If you ask at discussion.nextstrain.org then more people may be able to commend and help with specifics 😄 

james
