### ISSUE TITLE
Improve performance of sidebar filtering display

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1230]
https://github.com/nextstrain/auspice/pull/1200 implemented sidebar filtering, however this is laggy for large datasets. Debouncing / throttling should reduce this dramatically & there may be other improvements here.

**Comment by trvrb** [comment]
For me, the lag to display filter list is not at all an issue. However, the lag for characters typed to appear in text box is a bit frustrating. I don't know what's best here technically, but I could imagine a fixed debounce at ~500ms might still catch people mid-typing of their filter term. Perhaps there's some way to only start filter look up when it appears that typing is finished.

**Comment by jameshadfield** [comment]
Closed by https://github.com/nextstrain/auspice/commit/868179b1b629aea67c7c6894840d51f88dc0e49b
