### ISSUE TITLE
Add "Download Filtered Tree" option

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/auspice#1235]
**Context**  
Under "Download Data" in Auspice, you can currently download selected metadata as a TSV, or a Newick divergence or time tree. However, it'd be nice to download a Newick tree with only the selected strains. This would improve interoperability of Nextstrain when someone wants to explore a subset of a larger tree in a different program (e.g. epidemiologists wanting to look at an outbreak in MicrobeTrace).

**Description**   
Option under "Download Data" in auspice to download "Selected tree" or "Selected TimeTree" Newick file.

**Comment by jameshadfield** [comment]
Thanks Cassia! Notes from talking through this today:
* The root of the exported tree should be the CA of the selected strains. Related to #1240
* If the tree is zoomed, then we should only export the visible tree (i.e. the root of the exported tree is auspice's "in-view" root node). 
* If we add contextual sequences (#1241) these should be included in the exported tree.

**Comment by trvrb** [comment]
All this sounds good. I'd be pretty firm between what's selected and what's not. If tips are shown they and their ancestors (back to the common ancestor) should be present in the exported filtered tree. Ie "contextual sequences" would be just as selected as other tips when active.

**Comment by emmahodcroft** [comment]
I'm ok with all of this. One comment (which I guess we can't prevent but should keep in mind for users) is that the filtered tree may not be the same as the tree you'd get if you ran it from scratch, with just the filtered sequences.

**Comment by jameshadfield** [comment]
Closed by #1245 and released in v2.21.0
