### ISSUE TITLE
(re-)investigate react router

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#124]
Now that we run our own server (i.e. not amazon S3) can react router handle things? If so, is this better than our current implementation?

**Comment by trvrb** [comment]
Brief notes here on react-router. It adds some convenience methods to manipulate `location.pathname` and `location.query` that I think will be quite valuable. For example, you can

```
this.props.router.push("full/url/here")
```

To update path from App. This is safer than `changeRoute`. It also adds `this.props.location.pathname` and `this.props.location.query` to App.

I going to carve out more atomic router issues now.
