### ISSUE TITLE
Sidebar filtering options should include all node/branch attrs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1251]
The original intent of the sidebar filtering was to allow filtering by all traits which are defined via `metadata.filters` as well as those defined via `metadata.colorings`. The latter has not yet been implemented.

Note that the filters which appear in the footer of Auspice should still only reflect those defined in `metadata.filters`.

**Comment by joverlee521** [comment]
With the work to export metadata fields without defining them as coloring options (https://github.com/nextstrain/augur/pull/1384), we should extend filtering options to include _all_ available metadata fields.

**Comment by jameshadfield** [comment]
I think this issue should be extended a bit (but I'm including here as it'll almost certainly be simpler to do it in a single push). 

I think _all_ node and branch attrs defined across a tree should be searchable via the dropdown sidebar. That is, the `meta.filters` array should no longer be used. For the filters listed in the footer we don't want this behaviour, and we could repurpose the `meta.filters` array to suit this purpose.
