### ISSUE TITLE
auspice 2.21 epic

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1255]

**Comment by emmahodcroft** [comment]
Are we giving them names now?? 😁

**Comment by jameshadfield** [comment]
John & I are trying out different ways of organizing things using ZenHub, hopefully we can settle into a good system soon, right now it's all a bit experimental!

**Comment by jameshadfield** [comment]
v2.21 released (and nextstrain.org updated) on 2020-01-06
