### ISSUE TITLE
Ensure bundle hashes are appropriately computed

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1266]
**Context**

We recently observed hard-to-debug bugs when deploying nextstrain.org which are caused by errors in how we compute bundle hashes during bundling (using webpack). These errors were (and sometimes still are) hard to pin down and reproduce. The core of the issue is that we encode the hash of each chunk in the filename so that chunks which haven't changed between different auspice versions (or nextstrain.org updates) look the same, which allows browsers to utilise cached assets. Any changes to chunk contents should result in a different filename, and thus the browser will not use the (previously-)cached asset. If the situation arrises where chunks are named the same, but have different content, then the browser may use the cached asset, thus resulting in an auspice client whose code is a combination of different auspice builds and unpredictable behavior will ensue. 

**Current Behavior**  

Sometimes, after rebuilding auspice (or nextstrain.org) you can get seemingly-random bugs, including complete app crashes, entropy-panel weirdness etc. These will go away if you reload the page with the cache disabled.

Inspecting the assests (`dist/*js`) of the previously build version (which has been loaded in a browser and cached) and the subsequent version (which is buggy when loading in the browser, with cache access enabled) indicates that there are JS bundle chunks with identical filenames but different contents. 

We use the `WebpackChunkHash` plugin to create hashes for chunks, which determines the chunk filename. This step apparently happens before minimisation/uglification steps (but this hasn't been confirmed for our webpack version/config).  Inspecting the bundles themselves (see previous paragraph), it seems that the differences do indeed stem from minification/uglification steps.

**Expected behavior**  

Changes in final bundle contents should result in a changed bundle filename, therfore not allowing a browser to use a cached resource.

**How to reproduce**  

> As this bug is related to webpack minisation & chunk creation, it cannot be reproduced using `auspice develop` or if we remove the minimisation steps from the webpack config.

These steps seem to work reproibly for me, but note that the bug is general and there will be many different paths to recreate it, which may appear different in terms of how the client crashes / behaves.

1. `cd auspice && mkdir ../auspice-bundle-hash-bug && mkdir ../auspice-bundle-hash-bug/a && mkdir ../auspice-bundle-hash-bug/b`
1. `git checkout 7ecbd6e3` (v 2.22.2)
1. `npm ci` (ensures the dep tree is correct) 
1. `auspice build && auspice view`
1. Load `http://localhost:4000/zika` with the cache disabled (in Firefox, this is a checkbox in the network tab of dev tools)
1. Confirm the app renders appropriately
1. Uncheck the "cache disabled" box. Keep the page open (shouldn't be necessary, but makes life simpler).
1. close the server process
1. `cp dist/*js ../auspice-bundle-hash-bug/a`
1. `git checkout 960dfea9` (`filter-by-genotype` branch, others could probably be used)
1. `auspice build && auspice view`
1. reload the open page, `http://localhost:4000/zika`, making sure the cache disabled box is _unchecked_. Note that the ~frequency~ entropy panel is broken.
1. Confirm that this is fixed by reloading the page with "cache disabled" ticked.
1. `cp dist/*js ../auspice-bundle-hash-bug/b`
1. `cd ../auspice-bundle-hash-bug`
1. `for i in $( ls a ); do if [[ -f b/$i ]]; then cmp --silent a/$i b/$i || echo "$i has different contents!"; fi; done;`
1. I get the following output (perhaps yours differs? The important thing is that there are chunks with the same filename which have different contents.)
```
auspice.chunk.12.bundle.1c2d5e3a950d2195bb40.js has different contents!
auspice.chunk.8.bundle.93172f6ce1a138aef270.js has different contents!
```

**Possible solution**  

Debug & fix webpack config.

Upgrade to webpack 5 so we can use [`optimization.realContentHash`](https://webpack.js.org/configuration/optimization/#optimizationrealcontenthash).

**Comment by eharkins** [comment]
@jameshadfield I'm trying to reproduce but the frequency panel isn't shown by default for zika for me so I'm not sure how to interpret 
> reload the open page, http://localhost:4000/zika, making sure the cache disabled box is unchecked. Note that the frequency panel is broken.

Did you mean another panel or should I add it into the `panels` key for the dataset json locally (or should it be there already)?

**Comment by ivan-aksamentov** [comment]
I always thought this caching comes by default with webpack, at least recent versions (4+). If not, how important this caching really is for Nextstrain? Is saving 2 seconds on every first load after a new release really worth sacrificing stability and adding another moving part to maintain and debug? Or are there other nuances?

I'd remove this entirely and kept the webpack config as vanilla as possible.

[offtopic]
In all our recent projects at NeherLab we use Next.js - we delegate the complexity of the build to the qualified people at Vercel who's full-time job is this kind of things. Next.js also adds a lot of interesting stuff on top of Webpack. They also maintain backwards compat, so that you always have the latest webpack and trendy features without breakages every time.

We might consider moving Nextstrain projects to Next.js. I have some experience and would be glad to help. I am sure they mastered chunk hashing to state of the art. Another thing that comes to mind is routing - with Next.js router we would never need to maintain our own URL processing, page switching etc. This transition is a major undertaking and would have some kinks in the beginning, but, I believe that would be the major good long term.
[/offtopic]

**Comment by jameshadfield** [comment]
> I'm trying to reproduce but the frequency panel isn't shown by default for zika for me so I'm not sure how to interpret

Typo! I meant the entropy panel. (I've updated the original message.)

> how important this caching really is for Nextstrain?

I think the only conversation had about this is the PR which introduced it --  https://github.com/nextstrain/auspice/pull/1126

**Comment by kairstenfay** [comment]
@jameshadfield I want to confirm that I can reproduce the bug, and in step 17, I get the same results as you.
