### ISSUE TITLE
Download Data producing empty trees

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/auspice#1267]
**Current Behavior**  
When I try to download a Newick tree after I've filtered to specific tips, the downloaded file is empty. The download "dashboard" says currently 523/4047 tips are displayed, but the downloaded file only contains a semicolon.

**Expected behavior**  
The tree file should contain the tips shown & selected in the tree display.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Open  https://nextstrain.org/groups/blab/ncov/wa/4m
2.   Filter to Recency --> 1-2 days ago.
3.  Click Download data
4. Download Newick tree
5. File is empty.

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Windows 10 Pro
 - Browser:  Chrome 

**Additional context**  
This doesn't seem to happen with every type of filter every time. For example, when testing this bug, I initially filtered to clade 20G, and the file contained the expected number of tips. But then when I switched to filter by recency, the file was empty. If I then tried to filter by clade again, the file was also empty. So the bug may only be occurring after multiple filters have been toggled on and off.

This only seems to be a bug for .nwk files. With filters toggled on, all other files available to download (nexus tree, metadata, etc) were complete.

**Comment by kairstenfay** [comment]
Thanks for opening this issue, @cassiawag. I see the issue you describe on nextstrain.org. When I try to reproduce locally with my checkout of the [nextstrain.org repo](http://github.com/nextstrain/nextstrain.org), however, I don't see an option to download a Newick tree, and I'm not sure why.

**Comment by cassiawag** [comment]
Do you have the latest version of auspice? This is a relatively new feature.

**Comment by jameshadfield** [comment]
Thanks @cassiawag -- note that if you click “Zoom to selected” and then download the tree it works. 

My guess for the bug is that the tree-traversal used for export is starting at a non-visible node and thus terminating straight away.

A complicating factor, but not the cause of this bug, is the situation subsequently introduced in #1265 (and one which will become more common with #1275) where we have trees where the MRCA which is not visible (i.e. `visiblity[idxOfFilteredRoot]!==NODE_VISIBLE`). This will require a new issue I think.

**Comment by trvrb** [comment]
I'm confirming that this bug still exists. I was able to reproduce just now.

**Comment by corneliusroemer** [comment]
@SpyderBunny encountered this too, still exists and confuses users

**Comment by joverlee521** [comment]
This bug has been brought up by users a lot recently. I'll try looking into it next week.
