### ISSUE TITLE
error: frequency JSON not found

### ISSUE THREAD

**Issue by ps120195** [nextstrain/auspice#1268]
After generation of the frequency json file and exporting it ,I am unable to visualise the frequency figure in auspice.
![auspice](https://user-images.githubusercontent.com/62909237/104909642-2a12f880-59ae-11eb-9e8f-aa94e83eb03b.jpg)
I tried keeping panels as default as well as setting it as  --panels frequencies , the option appears on the panels but no graph.
Please help.
auspice version = 2.18.1

**Comment by jameshadfield** [comment]
The error printed by the locally-running auspice server (`[verbose] Error: ENOENT: no such file or directory, open 'freq1801r1_tip-frequencies.json'`) and the attached screenshot indicate that the auspice client is making a request for a frequencies JSON but that the server can't find the correct file.

From the error message, your dataset seems to be named `freq1801r1.json` - can you check if there is also a file `freq1801r1_tip-frequencies.json` in the same directory?

**Comment by ps120195** [comment]
No, There is no file formed with name "freq1801r1_tip-frequencies.json"

**Comment by ps120195** [comment]
Command to generate frequency json file :
augur frequencies --method kde --metadata metadata.tsv --min-date 2020 --max-date 2021 --tree refined_tree.nwk --include-internal-nodes --alignments aligned.fasta --output frequencykde.json

And Command to export all the jsons into auspice json :
augur export v2 --tree refined_tree.nwk --node-data traits.json nuc_muts.json amino_muts.json branch.json clades.json frequencykde.json --output freq1801r1.json --auspice-config auspice_config.json --geo-resolutions State --color-by-metadata State New_Nextstrain_Clade Region Age_Group Gender Status Pangolin_Lineage GISAID_Clade --colors colors.tsv --lat-longs lat_long.tsv --metadata metadata.tsv

This freq1801r1.json was the only file generated ,which was pushed to local server.
Why am I not getting tip frequencies json file?
Please help.

**Comment by jameshadfield** [comment]
Your `augur export ...` command is producing `freq1801r1.json`.
Your `augur frequencies ...` command is currently producing `frequencykde.json` (via the `--output` arg), but this needs to be `freq1801r1_tip-frequencies.json`.
