### ISSUE TITLE
Size branch width according to clade frequency

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#127]
This is done in auspice v1 and makes for a very handsome tree. Clade frequency is calculated as the number of tips that subtend a branch that are "on" divided by the total number of tips that are "on" in the entire tree.

**Comment by jameshadfield** [comment]
related to #140

**Comment by trvrb** [comment]
This is partially addressed in 0d0addb3776b34cb2d1ad4f9c0fe5f9777a248a9. Still need to wire it up so that frequencies update when tips go between hidden and visible.
