### ISSUE TITLE
Improve search algorithm in sidebar filtering UI

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1271]
Currently (and unchanged in #1265) one must type an exact (case-insensitive) substring of the displayed filter options in order to have them show up as selectable. For example, given a filtering option `mutation HA1 136E` (buried in a large list), typing any the following examples do not identify the option: `mut 136E`, `mut HA1 136`, `136 HA1`.

This is also evident for options such as `Country → USA` where typing in `country USA` does not identify the option for filtering!

**Notes**   

- As part of this, we may want to upgrade the version of react-select we are using (we're pinned to 1.0.0-rc5, the latest is 3.2.0). 
- A solution here must take into account performance, as we frequently have lists of options of 10^4 or higher.
- During #1265 I investigated using https://github.com/bvaughn/react-select-fast-filter-options, which would easily expose the string matching algorithm, however this resulted in significantly decreased performance and thus wasn't persued.

**Comment by didithilmy** [comment]
Hello, I'm interested in taking this issue, I might have a solution without the need to upgrade react-select.

The code takes advantage of react-select's `filterOption` prop. The filter shows an option only if every word in the search query exists somewhere in the option label. Using this, entering `country USA` will include `Country → USA`. This also works even when the order of the word doesn't match.

<img width="236" alt="Screen Shot 2021-03-10 at 15 09 23" src="https://user-images.githubusercontent.com/4845621/110597003-9d690780-81b2-11eb-8fab-349c7476910f.png">

I have tried this out using `ncov/global` and there doesn't seem to be a significant performance issue.

Take a look at https://github.com/nextstrain/auspice/compare/master...didithilmy:filter-search-alg
