### ISSUE TITLE
Incorrect frequency plot from augur frequencies

### ISSUE THREAD

**Issue by ps120195** [nextstrain/auspice#1279]
![augur_frequencies](https://user-images.githubusercontent.com/62909237/105994707-00ed1900-60ce-11eb-8f6c-bd2b6e00386d.jpg)

In the attached figure , the yellow colour is showing the mutation frequency at 0% ,which should not be the case ideally.
Please help

**Comment by jameshadfield** [comment]
@ps120195 this was a rounding error -- in this case the frequency was below 0.5% and was being rounded to 0%. PR #1301 will improve this output.
