### ISSUE TITLE
Better document swapping map tilesets

### ISSUE THREAD

**Issue by michalkowalski94** [nextstrain/auspice#1286]
**Current Behavior**  
When running auspice view locally and in container, map is a huge gray rectangle

**Expected behavior**  
Working map like it supposed to 

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Install however you like, from source with nodejs via package manager or via conda with source
2. auspice view
3. map is a gray rectangle

**Possible solution**  
No idea

**Your environment: if browsing Nextstrain online**  
 - Operating system: CentOS 7, Ubuntu 16.04LTS, Ubuntu 18.04LTS, Ubuntu 20.04LTS  
 - Browser:  Chromium, Firefox, Edge, Internet explorer (with exposing port)

**Your environment: if running Nextstrain locally**  
 - Operating system: CentOS 7, Ubuntu 16.04LTS, Ubuntu 18.04LTS, Ubuntu 20.04LTS  
 - Browser:  Firefox
 - Version: auspice 2.23.0  

**Additional context**  
![image](https://user-images.githubusercontent.com/40108472/107753956-18a8dc00-6d21-11eb-9ce6-60ca01813f14.png)

**Comment by emmahodcroft** [comment]
Hi @michalkowalski94 ! Sorry for this causing you trouble. This isn't my area of expertise, but just to check something - does the container have access to the internet? The map has to be download on first launch and at every zoom level, so this could be the issue. However, if it does have internet there's clearly another problem at work, and hopefully another person from the team can have a look!

**Comment by michalkowalski94** [comment]
Hi, it actually does not work even if auspice is not in container.
Container is exposed to public zone and has access to internet via docker bridge network.
Thank You for quick response

**Comment by rneher** [comment]
We have been rotating mapbox tokens, but the new ones should work for `localhost`. Please check in the browser console why/if the mapbox request fails. @trvrb or @jameshadfield might know more.

**Comment by rneher** [comment]
some privacy extensions also block fetching of tiles. But I see you tested many browsers, so that is probably not the issue.

**Comment by michalkowalski94** [comment]
Okay, changed in `src/util/globals.js` api to
`
export const getMapTilesSettings = () => {
  if (hasExtension("mapTiles")) {
    return getExtension("mapTiles");
  }
  /* defaults */
  const api = 'https://a.tile.openstreetmap.org/{z}/{x}/{y}.png';
  return {
    api,
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    mapboxWordmark: true
  };
};
`
It solved the problem and licensing is more humanitarian.
Extending with auspice build --extend filename.json resulted in dumped core

**Comment by jameshadfield** [comment]
This is due to the [new mapbox tokens we are using](https://github.com/nextstrain/auspice/blob/master/CHANGELOG.md#version-2220---20210111) being rejected due to the doman that auspice is running on. What is the browser address you are viewing auspice through? (You are running `auspice view` so I expect this is `http://localhost:4000` but want to double check)

In the meantime, you can temporarily downgrade auspice to 2.21.0 to fix this. 

> Extending with auspice build --extend filename.json resulted in dumped core

Would you mind posting this error log somewhere to help us debug this (unrelated) issue?

**Comment by nkeito** [comment]
> In the meantime, you can temporarily downgrade auspice to 2.21.0 to fix this.

How can this be acheived by using a docker image? Because, I tried to do npm uninstall auspice

**Comment by ThijnvanKempen** [comment]
We are also running into the same problem, the map is working on the localhost but not on the hosted webaddress.

Please see: nextstrain.nrcnvwa.nl for examples.

Hopefully you can help us to fix this, since downgrading to auspice 2.21.0 does not work for us. 

Kind regards

**Comment by jameshadfield** [comment]
Hi @ThijnvanKempen -- these tokens have stopped working on hosted instances of auspice, as each use incurs a fee for us! The [docs](https://docs.nextstrain.org/projects/auspice/en/stable/customise-client/api.html#custom-map-tiles) provide a way for you to provide your own token at auspice build time. (And this also lets you choose the style of map tiles you wish.) If those instructions don't work, please make an issue detailing which commands you ran & the terminal output / error message(s) and i'll happily help debug it.

**Comment by ThijnvanKempen** [comment]
Hi @jameshadfield,

Thank you for the reply. We would like to include openstreetmap as an API for the webserver. 
We are kinda struggling with the manual since we have no experience with .JSON files, could you maybe provide us with an instruction how to do so?

Thank you in advance.

Kind regards,
Thijn

**Comment by dwwhall** [comment]
> Hi @ThijnvanKempen -- these tokens have stopped working on hosted instances of auspice, as each use incurs a fee for us! The [docs](https://docs.nextstrain.org/projects/auspice/en/stable/customise-client/api.html#custom-map-tiles) provide a way for you to provide your own token at auspice build time. (And this also lets you choose the style of map tiles you wish.) If those instructions don't work, please make an issue detailing which commands you ran & the terminal output / error message(s) and i'll happily help debug it.


I am having the same trouble as @ThijnvanKempen.  The map is not working on our servers.  I am trying to run auspice build --extend on the JSON file, but I keep on getting errors.  Is there a different way to change the API address on auspice? 


Command:

auspice build --extend auspice/MyNewBuild.json



Terminal output:

Running webpack compiler

[BABEL] Note: The code generator has deoptimised the styling of /Users/dwightwillhall/opt/miniconda3/envs/nextstrain/lib/node_modules/auspice/node_modules/lodash/lodash.js as it exceeds the max of 500KB.

[BABEL] Note: The code generator has deoptimised the styling of ~/opt/miniconda3/envs/nextstrain/lib/node_modules/auspice/node_modules/react-icons/fa/index.esm.js as it exceeds the max of 500KB.

…

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

…

zsh: abort      auspice build --extend auspice/MyNewBuild.json

(nextstrain) ***** % node:events:346

      throw er; // Unhandled 'error' event

      ^



Error: write EPIPE

    at process.target._send (node:internal/child_process:849:20)

    at process.target.send (node:internal/child_process:722:19)

    at callback (/Users/dwightwillhall/opt/miniconda3/envs/nextstrain/lib/node_modules/auspice/node_modules/worker-farm/lib/child/index.js:32:17)

    at module.exports (/Users/dwightwillhall/opt/miniconda3/envs/nextstrain/lib/node_modules/auspice/node_modules/terser-webpack-plugin/dist/worker.js:13:5)

    at handle (/Users/dwightwillhall/opt/miniconda3/envs/nextstrain/lib/node_modules/auspice/node_modules/worker-farm/lib/child/index.js:44:8)

    at process.<anonymous> (/Users/dwightwillhall/opt/miniconda3/envs/nextstrain/lib/node_modules/auspice/node_modules/worker-farm/lib/child/index.js:55:3)

    at process.emit (node:events:369:20)

    at emit (node:internal/child_process:920:12)

    at processTicksAndRejections (node:internal/process/task_queues:82:21)

Emitted 'error' event on process instance at:

    at node:internal/child_process:853:39

    at processTicksAndRejections (node:internal/process/task_queues:76:11) {

  errno: -32,

  code: 'EPIPE',

  syscall: 'write'

}

**Comment by ThijnvanKempen** [comment]
Hi @dwwhall,

For me it worked to change the API code section in global.js file found in util/etc.
Afterwards I just ran the auspice build (no extend) and it worked for me. 
Hopefully this also works for you.

**Comment by trvrb** [comment]
I suspect this is still confusing a number of users. Perhaps the main thing that can be done is to slightly expand out https://docs.nextstrain.org/projects/auspice/en/stable/customise-client/api.html#custom-map-tiles? I'm not sure I would have understood what to enter under `mapTiles.api`. Just give an example from MapBox and an example from OpenStreetMaps.

**Comment by jameshadfield** [comment]
Update: please see [these steps on discussion.nextstrain.org](https://discussion.nextstrain.org/t/build-with-newest-nextstrain-ncov-has-api-requests-to-mapbox-403-forbidden/396/11?u=james) for a hands-on approach to setting custom tile API. 

Leaving this issue open until I've added this to the actual docs.
