### ISSUE TITLE
better sorting of color by legend

### ISSUE THREAD

**Issue by jbell-cdph** [nextstrain/auspice#1291]
If there are a lot of values in the color-by trait, it can be difficult to find the one of interest, because the order of the list appears random.    If the values were sorted in some easy-to-recognize way, it would be easier to find the strains of interest.

I would like for there to be a way for the order of values in the color-by legend to be sorted, either by default or by choice.

An example of a problematic case is attached.   It took me a minute to find B.1.1.7 in this list, for instance.

![pango_legend_madness](https://user-images.githubusercontent.com/68124699/108385421-81300700-71c0-11eb-9ce7-6cbb266bb1c2.png)

**Comment by jameshadfield** [comment]
👍 currently the filters are ordered using counts (i.e. B.1.2 has the most occurances in the tree), which is sometimes ideal and sometimes not! There are a few improvements possible here, some on our side and some available to the dataset maintainer:

(1) If `pangolin` is added to the [`json.meta.filters`](https://github.com/nextstrain/augur/blob/master/augur/data/schema-export-v2.json#L93-L99) array, then one can quickly filter the dataset via the sidebar typing-based UI to "pangolin B.1.1.7". 

(2) It's on my to-do list to make all colorings automatically available as filters (in the sidebar UI) so hopefully this will be up in the next few days

(3) If you [define a scale for a coloring](https://github.com/nextstrain/augur/blob/master/augur/data/schema-export-v2.json#L181-L191) then the legend ordering reflects this. Really useful for traits where you have not too many values - for pangolin it would require a small script to generate the list & colours I think.

**Comment by trvrb** [comment]
Thanks for the feedback @jbell-cdph. I'm hopeful that (1) + (3) above resolve this issue for you. On live https://nextstrain.org/ncov/global?c=pango_lineage, the legend is properly sorted and you can quickly filter to B.1.1.7 as @jameshadfield suggests. But please let us know if this is not sufficient.
