### ISSUE TITLE
Large datasets will result in a RangeError

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1292]
Currently this can be observed with nextstrain.org/tb/global in Chrome, where the app crashes with  `RangeError: Maximum call stack size exceeded.` This is most probably due to a recursive tree-traversal algorithm exceeding the stack size allowed by Chrome (note that Firefox works). It also arrived recently, and my guess would be it's related to the code which collects genotypes to be used as filters. 

An acceptable solution may be to catch this `RangeError` if possible and if it's not in a mission critical part of auspice.

**Comment by tsibley** [comment]
Related discussion post: https://discussion.nextstrain.org/t/tuberculosis-data/364
