### ISSUE TITLE
Dates Before Present are -undefined

### ISSUE THREAD

**Issue by ktmeaton** [nextstrain/auspice#1294]
**Current Behavior**  
When "Branch Length" TIME is selected, dates before present appear as "-undefined" on the axis labels. Despite the inferred dates and confidence intervals displaying correctly.

![image](https://user-images.githubusercontent.com/14981272/109335367-ee324500-782f-11eb-8ce2-698e7451e12d.png)

**Expected behavior**  
I would like axis labels for dates before present to appear as "-2000 ... -1000..." not -undefined. This was how it worked in a previous version of auspice, but I'm not sure where the changed occurred.

**How to reproduce**  
1. Remote: https://nextstrain.org/community/ktmeaton/plague-phylogeography/clock-model?ci&m=num_date
1. Local:
    - Unzip the following archive, which contains the json ready to be visualized with auspice.
[clock_model_auspice.zip](https://github.com/nextstrain/auspice/files/6051438/clock_model_auspice.zip)
    - Start the auspice server. For local visualization:
    ```bash
    HOST="localhost" auspice view --datasetDir .
    ```

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Windows 10
 - Browser:  Google Chrome and Microsoft Edge

**Your environment: if running Nextstrain locally**  
 - Operating system:  WSL2 Ubuntu 20.04
 - Browser:  Google Chrome and Microsoft Edge
 - Version:  `auspice 2.22.0` and `auspice 2.23.0`)

Thank you!!

**Comment by jameshadfield** [comment]
Thanks for the detailed bug report & for including a dataset to reproduce ⭐ 

PR #1297 fixes this and should be in an auspice release this week

**Comment by ktmeaton** [comment]
Thank you for looking into this! I've made a few attempts to install auspice from source (off master). The build succeeds but I haven't been able to run the local server successfully. I'm sure this is entirely because of my inexperience with nodejs :) I will just wait for the next release!
