### ISSUE TITLE
Legend masks branches and tips in upper left of tree panel

### ISSUE THREAD

**Issue by AngieHinrichs** [nextstrain/auspice#1295]
**Current Behavior**  
The legend is drawn over the upper left corner of the tree area, which sometimes has branches and tips that become less visible and unclickable because they're covered by the legend, even when the legend is minimized to just the label.  For example, in this image ([JSON file](https://hgwdev.gi.ucsc.edu/~angie/singleSubtreeAuspice_hgwdev_demo_angie_ab43_822a50.json)), all of the red sequences are obscured when the legend is not minimized:

![image](https://user-images.githubusercontent.com/186983/109356190-356f0480-7835-11eb-95cb-31f8158a52da.png)

and even when the legend is minimized there is still a sequence that can't be reached:

![image](https://user-images.githubusercontent.com/186983/109356353-70713800-7835-11eb-8192-9a9b219f9f83.png)

**Expected behavior**  

I expect to be able to click on any branch or tip in the tree.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Download [JSON file](https://hgwdev.gi.ucsc.edu/~angie/singleSubtreeAuspice_hgwdev_demo_angie_ab43_822a50.json)
2. Drag-drop onto https://auspice.us/  

(This also happens on nextstrain.org, e.g. https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/singleSubtreeAuspice_hgwdev_demo_angie_ab43_822a50.json)
  

**Possible solution**  
If the legend could be moved, perhaps to the right of the "Phylogeny" label (at least when it's minimized?), then it would not hide part of the tree.  Or if the legend could fit in its own vertical space when minimized, that would also keep it out of the tree.

**Your environment: if browsing Nextstrain online**  
 - Operating system:  macOS Catalina 10.15.7
 - Browser:  Chrome 88.0.4324.150

**Additional context**  
Having a wide web browser window on a large monitor ameliorates the problem by stretching the tree farther out to the right, but on a little laptop screen (like my PI's 🙂 ) it's worse.

If I'm missing an obvious way to avoid this problem please let me know!  Thanks.

**Comment by emmahodcroft** [comment]
Thanks for making an issue on this @AngieHinrichs - I've noticed it myself, and a couple of times been frustrated with it!

**Comment by AngieHinrichs** [comment]
Wow, that was fast!  Thanks so much!
