### ISSUE TITLE
Export image from auspice :Is it possible to export image(tree/map) from auspice?

### ISSUE THREAD

**Issue by BettyAC** [nextstrain/auspice#1299]

**Comment by trvrb** [comment]
Hi @BettyAC. If you scroll to the bottom of the page you'll see a "DOWNLOAD DATA" button. After clicking on this, you'll get the option for "SCREENSHOT (SVG)". Clicking this will give what I believe you're looking for. For more information see: https://docs.nextstrain.org/en/latest/guides/share/download-data.html#svg-screenshot.
