### ISSUE TITLE
Metadata drag-and-drop on auspice.us causes crash

### ISSUE THREAD

**Issue by jmcbroome** [nextstrain/auspice#1304]
**Current Behavior**  
I have a small tree of 29 samples I'm interested in visualizing via the Auspice web interface. I have a JSON and a metadata file with some sample quality values (in the attached zip archive). The json uploads and displays fine, but when I try to drag-and-drop my metadata file, which is formatted according to the instructions on the [documentation](https://docs.nextstrain.org/projects/auspice/en/latest/advanced-functionality/drag-drop-csv-tsv.html), it crashes and whites out the screen. I then have to reload, which clears everything I've uploaded.

[test_auspice_A24.zip](https://github.com/nextstrain/auspice/files/6135184/test_auspice_A24.zip)

**Expected behavior**
I'd expected the metadata to properly display for each sample in my input tree, or to get an informative error message telling me that my metadata or json is malformed in some way.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Unzip the attached archive 
2. drag and drop the JSON file test_24.json onto auspice.us
3. drag and drop the metadata file a24_samples.txt onto auspice.us

 - Operating system:  Found on both MacOS and Windows machines
 - Browser:  Safari and Chrome respectively

**Additional info**  
I tried selecting just a few samples out of my file, removing the header lines, and using a csv version of the file, and all combinations of these. Nothing changed the behavior and nothing displayed correctly. I also tried different metadata values and converting from integers to letters, all which had no effect. The JSON I'm using was generated by custom code, so its possible that there's some incompatibility there- if this is the case, please let me know what changes I need to make to my JSON format to allow drag-and-drop metadata to function.

**Comment by jmcbroome** [comment]
With some trial-and-error I managed to figure out that the "filters" attribute has to explicitly exist under "meta" in the JSON, even if its empty, in order for the drag and drop to render properly.

**Comment by jameshadfield** [comment]
Thanks for troubleshooting! This is indeed a bug, and i'll try to get it fixed for the next release!
