### ISSUE TITLE
Allow urls to be set & displayed for node attrs

### ISSUE THREAD

**Issue by AngieHinrichs** [nextstrain/auspice#1307]
**Context**  
On https://nextstrain.org/ncov/global, when I click on a sample, the sample details include a link to https://www.gisaid.org:

![image](https://user-images.githubusercontent.com/186983/111554579-d9b4de80-8743-11eb-93ee-c87ef84d3704.png)

In ncov.json, every sample's `node_attrs` has `"url": "https://www.gisaid.org"` so I assume that's where the link comes from.

**Description**   

I would like to add a URL for each sample in the Auspice V2 JSON loaded using nextstrain.org/fetch/ so that the user can click from one view to another.  I added `node_attrs.url` URLs for my samples, and the URL text is displayed but is not a link, i.e. I have to copy-paste it:

![image](https://user-images.githubusercontent.com/186983/111554528-c99cff00-8743-11eb-8cb5-1633d34e6ce4.png)

Would it be possible to automatically make `url` a clickable hyperlink?

**Examples**  

Load this and click on a red sample:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/uploadedSampleUrl.json

Thanks, having /fetch/ has been a huge help for us!

**Comment by jameshadfield** [comment]
Hey @AngieHinrichs  - this shouldn't be too hard for us to do, and I think it would be generally worthwhile. I think the best  approach would be to allow `node_attrs` properties to have an optional `url` field as well as the required `value` field. For instance,

```json
"node_attrs": {
   "subtree": {
        "value": "See this subtree",
        "url": "https://nextstrain.org/..."
   }
}
```

Re: the `url` field, the `node_attrs` dictionary has a number of properties which we treat as "special" (`div`, `num_date`, `vaccine`, `hidden`, `url`, `author`, `accession`) which could be better documented.

**Comment by AngieHinrichs** [comment]
Even better!  Thank you @jameshadfield!
