### ISSUE TITLE
[scatterplots] allow non-continuous variables

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1316]
Currently scatterplots (as implemented in #1310) restrict the {x,y} variables to continuous colorings. It would be beneficial to allow categorical variables, and this issue outlines the required steps.

(1) `collectAvailableScatterVariables` is the function which restricts the variable choices to continuous variables

(2) Upon selection of a non-continous variable, we need to collect the different values in the tree, and order them. Until now, this has been the remit of colour scales (e.g. see `/src/util/colorScale.js`), which both examine nodes to collect values and check the metadata for any provided scale, which would define an ordering of the values. This code will have to be (minimally) refactored to allow usage here. This will have to run on dataset load (if needed) and when selecting new scatterplot variables, and is thus probably best suited as a wrapper function in `/src/util/scatterplotHelpers.js`. The results should be stored inside the `scatterVariables` object, which will be passed to PhyloTree (this is where we store the variable keys, labels etc). 

(3) Phylotree will need to create new scales. Currently we only use `scaleLinear`, but we will have to expand to `scaleOrdinal`. I believe PhyloTree's `setScales` function (`layouts.js`) can be modified to examine `this.scatterVariables` and change scales as needed. The `addGrid` prototype will need to be updated correspondingly. Further testing is needed to ensure that this is all that's required.

(4) Regressions shouldn't be calculated for non-continuous variables. 

(5) Genotypes will require more work, as the way we access this variable on each node is special, however this shouldn't be too much extra effort.

**Comment by trvrb** [comment]
This was resolved in #1310. It even works for genotypes 🌟
