### ISSUE TITLE
Ability to modify the filter data fields to match 'Color By' titles

### ISSUE THREAD

**Issue by matt-sd-watson** [nextstrain/auspice#1322]
Currently, the auspice configuration json allows for the user to specify the title displayed for certain keys i.e. allowing a metadata key such as 'health_region' to be displayed in a more readable format like 'Global Health Region'. 

Is it possible to specify the title for these same keys in the Filter Data box? The filter data options appear in the same way as the keys appear, which for some users may be confusing as they may not fully understand if the filter option corresponds exactly to the same field in Color By. 

The attached graphic is taken from the global Nextstrain build provided b the Nextstrain team, highlighting the difference in labeling between 'Clade' in Color By and the same filter label 'clade_membership' in Filter Data. 

![Screenshot from 2021-03-30 11-11-19](https://user-images.githubusercontent.com/40243147/113012592-e7596380-9148-11eb-9b07-4c13d7436a5e.png)

**Comment by jameshadfield** [comment]
Thanks for the detailed write up Matt -- this is an oversight from my side. Should be an easy fix.
