### ISSUE TITLE
Scatterplots don't always show x-axis ticks

### ISSUE THREAD

**Issue by huddlej** [nextstrain/auspice#1323]
**Current Behavior**  

When changing the default x-axis variable in the scatterplot layout, the x-axis ticks sometimes disappear. Whether the ticks show up or not seems to depend on the variable being displayed.

**Expected behavior**  

Axis ticks should always be present for any selected variable.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Go to the flu H3N2 HA 2y build
2. Select the "Scatterplot" layout
3. Change the `x` variable to "Divergence"
4. The x-axis looks like the figure below

![image](https://user-images.githubusercontent.com/85372/113029719-9d20b400-9141-11eb-9ebf-f21169d47e06.png)

**Your environment: if running Nextstrain locally**  
 - Operating system:  Mac OS X Mojave 10.14.6
 - Browser: Chrome 89.0.4389.90
 - Version:  `master` branch at commit 946e210

**Comment by jameshadfield** [comment]
Doh! I noticed issues with the grids in the PR and attempted to fix them via 38201fb but missed a few edge cases. PR up soon.
