### ISSUE TITLE
Add support for categorical colorbys to scatterplot

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#1339]
The scatterplot functionality has proved highly enabling to be able to view multiple aspects of data in a single view. One chief example at this moment is to compare attributes of emerging lineages, where a couple common views look like:

Color by emerging lineage, time on x axis, spike S1 mutations on y axis
https://nextstrain.org/ncov/global?branches=hide&c=emerging_lineage&l=scatter&scatterY=S1_mutations
<img width="1276" alt="s1" src="https://user-images.githubusercontent.com/1176109/116166265-7e66fc00-a6b2-11eb-93c5-27955cbe6aa2.png">

Color by emerging lineage, time on x axis, logistic growth on y axis
https://nextstrain.org/ncov/global?c=emerging_lineage&l=scatter&scatterY=logistic_growth
<img width="1276" alt="Screen Shot 2021-04-26 at 5 12 51 PM" src="https://user-images.githubusercontent.com/1176109/116166357-a7878c80-a6b2-11eb-9361-42a6a812a6a5.png">

Both these views help to surface which emerging lineages have highest S1 mutations (P.1) and which emerging lineages have highest rates of logistic growth (largely B.1.1.7), but other lineages get lost in the mix due to occlusion of tips.

For the desired comparison of S1 mutations and logistic growth across emerging lineages it would be preferable to have emerging lineage on the x axis and S1 mutations or logistic growth on the y axis.

In this case, rather than a regression line, I'd imagine a horizontal black line for each categorical variable demarcating its mean.

**Comment by huddlej** [comment]
One other use case that occurred to me recently would be a kind of transmission network view where we could plot time on the x-axis, regions on the y-axis, color by clades, and look for clades whose branches traverse region boundaries (sort of like [a slope plot](https://vega.github.io/vega-lite/examples/line_slope.html)). For some subset of geographic locations, we could get a similar effect from the current functionality by plotting latitude or longitude on the y-axis.

**Comment by jameshadfield** [comment]
This feature was released in v2.26.0
