### ISSUE TITLE
blank space on RHS of panels (sometimes)

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#134]
Related to sidebar closing but no browser resize event (I believe)

**Comment by trvrb** [comment]
Is this still an issue? Sidebar collapse is currently broken per issue #211.

**Comment by jameshadfield** [comment]
fixed somewhere!

**Comment by jameshadfield** [comment]
definitely not fixed :(

**Comment by jameshadfield** [comment]
seems to be fixed
