### ISSUE TITLE
Add back button to allow gradual zoom back out from clade in addition to "reset layout"

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1348]
**Context**  
In auspice, one can iteratively zoom into clades, but the only way to get back out is to click `RESET LAYOUT` which isn't terribly user friendly when exploring trees.

![image](https://user-images.githubusercontent.com/25161793/118861633-010f5f80-b8dd-11eb-832a-067b109a557e.png)

**Description**   
It would be great if there was an additional button `zoom out one step`

**Comment by rneher** [comment]
this exists, but isn't very discoverable...

If you click on the root of the clade you currently zoomed to, it will zoom out one branch.

**Comment by rneher** [comment]
A zoom out button might be an easy and intuitive fix.

**Comment by corneliusroemer** [comment]
Yes, I don't think it would harm.

The existing option of moving up one parent at a time is good, but tedious if you went in multiple steps. Moving out one level at a time is slightly different than going back to the previous view. There's a use case for both.

**Comment by trvrb** [comment]
I'd think the best solution here would be to properly work with the browser back/forward buttons and have this be a feature for generic app state. Ie you change state of Auspice to zoom tree, or filter or whatever and can easily get back to previous state by clicking back button. I think this would be much more intuitive than trying to add a universal back button to the app somewhere.

**Comment by joverlee521** [comment]
Resolved by #1392 . If desired, we can make new issue for a "back to previous state" feature that is separate from the zoom out.

**Comment by corneliusroemer** [comment]
Amazing! Yes I think it'd still be cool to have a "back to previous state" feature in addition.
