### ISSUE TITLE
Clicking on filtered tips, then away, means they're removed from filter

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#1357]
**Current Behavior**  
If a tip is selected under a filter, then you click on that tip to see more information, when you click away to close the box, the filter is removed.
![tipClickDisappear](https://user-images.githubusercontent.com/14290674/121502935-e498ab80-c9e0-11eb-9c26-edd3ec0496aa.gif)
This is particularly annoying if you are trying to explore a set of sequences, but have to keep re-adding them, or never click on the tips (particularly if you can't see the information you want because the mouse-over box is cut-off 🙃 #1356 ).
I run into this a lot when trying to evaluate the 'suspect' sequences proposed by Moira & Eli for potential exclude, but other times as well.

Happens with any filtered set of tips but here's a link for the gif shown (may have changed since then as these are live builds):
https://nextstrain.org/ncov/europe?c=S1_mutations&l=clock&s=India/MH-NIV-8404/2020,Mongolia/7908/2020,Peru/LIM-INS-768/2020,France/PAC-IHU-3126i/2020

**Expected behavior**  / **Possible Solution**
This is a tricky one as I know that clicking a random tip also applies a 'filter' of a sort, and we want that to disappear once box is clicked away from. 
Perhaps a variable could be set as to whether a tip was in a filter _prior_ to the box being clicked, so it could remain filtered once box is clicked away from?

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Windows 10 Pro
 - Browser:  Chrome

**Comment by trvrb** [comment]
I see what you mean Emma. My guess here is that activating the `infoPanel.click` component shouldn't also filter the dataset. Just clicking on a tip should bring up modal panel but shouldn't filter.
