### ISSUE TITLE
Allow 'turn off' of all filters, not just individual ones

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#1358]
**Context**  
When trying to inspect a set of filtered tips, one cannot zoom in so easily if only one filtered tip is visible. The best thing to do is turn off all filters, then click on the branch you want, then turn filters back on. However, for multiple tips, this takes ages to turn them on and off when switching views. 

![turnOffFilterTips](https://user-images.githubusercontent.com/14290674/121504097-ff1f5480-c9e1-11eb-8fe8-c33dcc9bc9b3.gif)

**Possible Solution**   
Perhaps alongside the 'delete all' icon below the 'Filter Data' on the menu, there could be a 'hide all' option? So that one could hide and unhide all the sample filters at once, to allow for more easy zooming in and out?

![image](https://user-images.githubusercontent.com/14290674/121504342-3b52b500-c9e2-11eb-936d-56b8d0475907.png)

**Examples**  
With any set of multiple tips on filter, try to zoom in and out to look at them each more closely in turn, without accidentally deleting any along the way :) 
https://nextstrain.org/ncov/europe?c=S1_mutations&s=France/PAC-IHU-3126i/2020,India/MH-NIV-8404/2020,Mongolia/7908/2020,Peru/LIM-INS-768/2020

**Comment by jameshadfield** [comment]
>  Perhaps alongside the 'delete all' icon below the 'Filter Data' on the menu, there could be a 'hide all' option? So that one could hide and unhide all the sample filters at once, to allow for more easy zooming in and out?

I've often wanted this!

**Comment by jameshadfield** [comment]
@emmahodcroft would you mind testing https://nextstrain-s-auspice-pr-zsssjw.herokuapp.com/ncov/open/global? I think this is a clear improvement.
