### ISSUE TITLE
Tree axis disappears on zoom

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#136]
![image](https://cloud.githubusercontent.com/assets/8350992/22317607/bb70b574-e329-11e6-997b-5960e734ab44.png)

I think we should have some whitespace at the bottom of the tree and display the axis values there

Not high priority

**Comment by rneher** [comment]
Issue here is that phyloTree puts the grid into the same SVG as the tree, the viewport zoom doesn't know about this...
