### ISSUE TITLE
Make it possible to zoom backwards in time, excluding descendants from certain time/divergence onwards

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1360]
**Context**  
I wanted to analyse how SC2 evolved during the first few months, to see how pango lineages A and B are related, for example. However, the tree is very dense in that region and I couldn't find a way to zoom into the first few months.

It's possible to zoom into descendants of a certain node, but there seems to be no equivalent in the other direction: excluding descendants after a certain point.

One can filter with respect to time with beginning and end time points, but this doesn't change the view.

If I have missed a feature, please let me know. The problem may then just be discoverability of that feature or entirely with me.

**Possible solution**   
The most straightforward way to introduce this feature would be to use the existing time filter and change view dynamically based on the cut-off times.

As a graphical example of what I mean here is a screenshot. I would like to zoom into the red box:
<img width="1223" alt="Screenshot 2021-06-13 at 17 17 55" src="https://user-images.githubusercontent.com/25161793/121813542-b3341000-cc6c-11eb-99a9-fada02d4d048.png">

**Comment by trvrb** [comment]
Closing this issue in favor of #1368.
