### ISSUE TITLE
Workflow creates incomplete JSON

### ISSUE THREAD

**Issue by erinyoung** [nextstrain/auspice#1374]
**Current Behavior**  
I created a json file with augur using the following steps:
- augur filter
- augur align
- augur tree
- augur refine
- augur ancestral
- augur translate
- augur export v2

I then get a wonderful json file that I want to give to https://auspice-us.herokuapp.com/, BUT! when I do I get the following message :
>auspice.us attempted to read this file but failed! Please consider making a GitHub issue for this to help us improve auspice.us. Error message: Unexpeccted end of JSON input.

This used to work just fine, so I'm a little baffled.

I can't share my json with you because it has PHI in it. 

Here's my entire augur export command, because this is likely where I'm going wrong.
```
augur export v2 \
     --tree {input.tree} \
     --metadata {input.metadata} \
     --node-data {input.branch_lengths} {input.nt_muts} {input.aa_muts} \
     --colors {input.colors} \
     --lat-longs {input.lat_longs} \
     --auspice-config {input.auspice_config} \
     --description {input.description} \
     --output {output.auspice_json}
 ```
 
**Expected behavior**  
Normally I just pull the json file to https://auspice-us.herokuapp.com/ and it just works (like magic). 

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Open https://auspice-us.herokuapp.com/
2. Drag JSON file generated by augur export
3. See error  

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Windows
 - Browser:  Version 91.0.4472.124 (Official Build) (64-bit)

**Your environment: if running Nextstrain locally**  
 - Operating system:  Centos 7
 - Version (e.g. `auspice 2.7.0`):   
 ```
$ nextstrain --version
nextstrain.cli 3.0.3
```

**Comment by emmahodcroft** [comment]
Just as a quick check - though apologies if you've already checked this! - have you opened the JSON in a text editor of done a `tail`-like view somewhere, to ensure the file isn't corrupted or didn't get cut off half-way when moving or writing for some reason? I commonly get this error in auspice.us when my cluster job was cut off unexpectedly, or my file transfer didn't finish correctly - that's why it makes me think of that!

**Comment by erinyoung** [comment]
I did try to look at that. It looks normal to me.

```
$ tail auspice/Utah_results.json
          2019.3142359231463,
          2019.9648575642775
        ],
        "value": 2019.9084650562213
      }
    }
  },
  "version": "v2"
}
```

**Comment by emmahodcroft** [comment]
Ok, thanks for checking! 

There's nothing that looks obviously wrong with your export command, particularly if it worked earlier. Did this stop working after an update of `augur`, or after adding some new data? If it's new data I would wonder if perhaps there's something with a special or strange symbol in a new sequence name or metadata column?

Before you drag the file into auspice.us, could you try to enable the 'console' in your browser (in Chrome you can right-click on a blank area of the page, then select 'inspect' and then in the window that appears to the side, select 'console' at the top). Then drag in the JSON as usual, and let us know what any errors are that appear?

**Comment by erinyoung** [comment]
I try to keep the container up to date, so maybe it was something with that.

I did just re-run the workflow, and now it appears to work. I guess it was just a corrupted file or something.

Thank you for your help!

**Comment by emmahodcroft** [comment]
No worries! Glad you got it sorted!
