### ISSUE TITLE
community not finding available datasets anymore

### ISSUE THREAD

**Issue by babarlelephant** [nextstrain/auspice#1378]
Hi, https://nextstrain.org/community/babarlelephant/cov doesn't find the list of .json in the github repository https://github.com/babarlelephant/cov 
Yesterday it was working. I guess the bug is on your side because https://nextstrain.org/community/babarlelephant/cov/sarscov works and it does find all the other .json in the github repository.
Thanks a lot.

**Comment by eharkins** [comment]
Thanks for pointing this out @babarlelephant! A fix is in progress at the PR linked above.

**Comment by eharkins** [comment]
Hi @babarlelephant, this should be fixed on nextstrain.org now. Let us know if this issue or other any others come up!
