### ISSUE TITLE
"Filter to this clade" broken

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#138]
Currently turns the tree branches black and changes the legend from country to something else (although this is restored when you mouseover the legend). Filtering should "select" the leaves which are descendent from the node, thus affecting the entropy and map panels. 

The "filtered" clade / nodeID should populate a box in the sidebar similar to geographic location / authors.

Multiple nodes should be able to be filtered in this way.

If a branch is clicked on that is already filtered, you should be able to unfilter / see that it's filtered

This information should not be stored in the URL, as consistency cannot be guaranteed

**Comment by trvrb** [comment]
I believe this has been fully resolved in PR #208.
