### ISSUE TITLE
Serving dist/index.html results in a client request for /charon/getDataset?prefix=/dist/index.html

### ISSUE THREAD

**Issue by terrycojones** [nextstrain/auspice#1391]
Hello!

I've made a build using `auspice build` (with a config that specifies custom map tiles, as described at https://docs.nextstrain.org/projects/auspice/en/stable/customise-client/api.html#custom-map-tiles and with no "serverAddress" key) and have put the resulting `dist` dir onto an Amazon EC2 instance sitting behind nginx. nginx correctly handles requests for URLs starting with `/dist` from this directory.

When I go to `/dist/index.html`, an Auspice landing page is displayed, but with a 404 message (see attached) saying "Couldn't load JSONs for /dist/index.html". Looking in the console, I see my browser has requested `https://myhost.com/charon/getDataset?prefix=/dist/index.html`. A list of available datasets is shown, and if I click on one it all works.

Is there a way to load my custom build `dist/index.html` _and_ immediately display a particular dataset (i.e., without going through the top-level landing "page" shown in the attached)? If I go directly to a `/charon` URL with a `prefix=` corresponding to my dataset, everything loads correctly, but then I am not running my build so the map doesn't work.

BTW, I'm doing this to get around the mapbox 403 token issue described at https://discussion.nextstrain.org/t/build-with-newest-nextstrain-ncov-has-api-requests-to-mapbox-403-forbidden/396  Maybe I should change src/util/globals.js as others have done.

Thanks for any help, and for the great tool & docs.

<img width="398" alt="Screenshot 2021-09-12 at 10 58 15" src="https://user-images.githubusercontent.com/132978/132981563-1d05a1e6-1ec5-4b25-bf26-588a0c0a478c.png">

**Comment by terrycojones** [comment]
I ended up just changing `globals.js` and rebuilding, so there's no urgency from my side on the above.

**Comment by jameshadfield** [comment]
The client will make requests for datasets (see [documentation here](https://docs.nextstrain.org/projects/auspice/en/latest/customise-client/requests.html)). By default these addresses start with `/charon`, [however this can be customised](https://docs.nextstrain.org/projects/auspice/en/latest/customise-client/api.html#available-customisations). Please reopen if this customisation doesn't work!
