### ISSUE TITLE
Allow inspection of all mutations on a branch, avoid truncation if too many muts

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1417]
I like to observe mutations on branches. Unfortunately, if there are more than 4 or so, they get truncated, and it doesn't seem possible to get a tooltip that shows all mutations of a branch. With tips, you can left-click them, however, with branches, left-clicking zooms in. Would it be possible to:
1. increase the tooltip for branches so all muts are shown (or at least up to say 15) and/or
2. allow right-clicking on branches to show a big tooltip like for tips?

See screenshot for an illustration of the issue, I don't like the `+ 4 more` in the AA muts view:
![image](https://user-images.githubusercontent.com/25161793/137482641-3f34ae4a-48ea-46d2-8179-5a7bc98f98f5.png)

**Comment by AngieHinrichs** [comment]
I would really like to see all mutations too!

**Comment by jameshadfield** [comment]
I've made progress on this, should have a PR up tomorrow

**Comment by AngieHinrichs** [comment]
@jameshadfield Thanks, that is really helpful!  I especially like that I can copy-paste the full list from the pop-up.  👍

**Comment by AngieHinrichs** [comment]
The new link to copy all nuc mutations to clipboard must be described in some other issue:
![image](https://user-images.githubusercontent.com/186983/138160732-574e18c1-483d-450c-9744-d70a33bd21fd.png)
-- but I just noticed it, and have to say OMG I love it, so helpful!  Thanks for all of the ongoing improvements!

**Comment by jameshadfield** [comment]
Thanks! (Beware, it includes `N`s as mutations, I will tweak this later.)

P.S. I did this as part of PR #1420, along with some other niceties such as ordering the genes according to genome position 😉
