### ISSUE TITLE
Auspice regularly freezes/crashes entire Brave browser, not just single tab

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1418]
**Current Behavior**  
About every 10-20min browsing Auspice trees with ~3000-4000 genomes my whole Brave browser will hang infinitely when I zoom into a branch. This doesn't happen on every branch click, by far not, but maybe on every 100th or so.

When I use Firefox, I have not encountered this issue.

**Expected behavior**  
Auspice should not hang my browser, I have enough RAM, the computer is fast enough etc.

**Your environment: if browsing Nextstrain online**  
 - Operating system:  macOS Big Sur v11.6
 - Processor: 2.2 GHz 6-Core Intel Core i7
 - RAM: 16GB
 - Graphics: Radeon Pro 555X 4GB
 - Plugged into power
 - Browser: Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (x86_64)

**Comment by corneliusroemer** [comment]
@tsibley what else shall I do than use Firefox which I already do and where the problem doesn't occur? 

> When I use Firefox, I have not encountered this issue.

Do I need to use Edge? 😱

**Comment by corneliusroemer** [comment]
Ok, just installed Chrome on Mac and crash appears after doing a few branch clicks on https://nextstrain.org/groups/neherlab/ncov/sa-chile

Has anyone tried to reproduce on a different computer also running Mac, ideally Big Sur?

![image](https://user-images.githubusercontent.com/25161793/137998531-708befee-7468-4b4c-a58e-9bd1c42cdd83.png)

Now I tried to collect logs and the crash doesn't happen anywhere. Argh!

**Comment by corneliusroemer** [comment]
This bug keeps coming up for me using Auspice and Brave, even when I use Brave Beta or Brave in incognito without any extensions (to rule out extensions causing it).

All I have to do is:
1. Open https://nextstrain.org/zika in any Brave browser (normal, incognito, Beta)
2. Select "show aa muts" instead of clades
3. Click on a node
4. Browser freezes

**Comment by jameshadfield** [comment]
@corneliusroemer -- following those steps (well, as well as I could, step 2 isn't applicable for zika) in brave 1.35.101 on MacOS 11.5 (M1 chip) I can't get it to freeze. I also tried with https://nextstrain.org/ncov/gisaid/global.

**Comment by victorlin** [comment]
@corneliusroemer I tried using Brave 1.35.101 on an Intel Mac (macOS 12.2.1; 2.9 GHz Dual-Core Intel Core i5; 16GB) and couldn't repro 😕

**Comment by corneliusroemer** [comment]
Can't repro anymore, seems to have worked itself out 🎉 
Or it's that I switched to M1 Pro from Intel 🙃
