### ISSUE TITLE
Add temporal colouring scale to use YYYY-MM-DD dates

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1427]
**Context**  
Datasets often have date information additional to sampling date (e.g. symptom onset date, sequencing date, submission date). We have no good way of displaying / interrogating such data. An additional use case is datasets with sampling date but for which internal nodes have no temporal info. 

**Description**   
Add a "temporal" colour scale type to the [existing 4 types](https://github.com/nextstrain/augur/blob/master/augur/data/schema-export-v2.json#L175-L180). The values must be either floats (e.g. `2020.123`) or YYYY-MM-DD (e.g. `"2021-10-31"`). We may extend this to allow ambiguity, but this can be left for subsequent work. Auspice will interpret such a value the same way as we currently interpret sampling dates, and generate a colour scale appropriately. 

**Related issues**
#1402 will discuss how filtering UI should behave here. Which branches we show as selected is up for debate, but I propose we treat this the same as filtering to traits where we trace back to the MRCA of selected tips, ignoring internal node annotations.

**Comment by jameshadfield** [comment]
This was implemented in #1523 however this required all dates to be numeric. I'll leave this issue here but rename it to indicate that we wish to allow YYYY-MM-DD dates

**Comment by emmahodcroft** [comment]
Allowing both would be good (maybe that is already what's intended) so that current implementations still work! :D
