### ISSUE TITLE
decide on URL structure

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#146]
Everything that should persist (i.e. when you reload the page) needs to be in this URL, so it's a subset of current state. This is used for the narrative, as well as sharing of links.

**updated feb 23 2018**

### state in URL (and key)
* Time range (`dmax`, `dmin`)
* tree format (`l`)
* tree metric (`m`)
* geographic resolution (`g`)
* panel layout (full vs grid) (`p`)
* filters (`f_<FILTERNAME>`, e.g. `f_authors`, `f_country`) - values are comma seperated
* colorby (`c`) - including genotype
* panels displayed (`d`)
* animation status
* selected tip (`s`)

### state thats should be in URL:
* selected branch #520
* map zoom #521
* confidence intervals #522

### state which we don't need to worry about
* scroll hijacking

**Comment by jameshadfield** [comment]
Currently `8581be1` this is working well enough with the following keys:
* dataset (zika/ebola)
* colorBy (`c`)
* `dmax` & `dmin`
* layout (`l`)
* divergence / time (`m`)
I'll keep this issue open but move it to backlog

**Comment by trvrb** [comment]
Realized that for narrative, setting map bounds is important.
