### ISSUE TITLE
Upgrade `react-select` package

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/auspice#1467]
We are still using v1 of `react-select` which is [no longer maintained](https://github.com/JedWatson/react-select/issues/3981). We should upgrade the package to use new features that have been added, such as option groups. The latest version is v5, but v2 was a complete rewrite so we should follow [their v2 upgrade guide](https://react-select.com/upgrade-to-v2) to make the necessary changes.

According to @jameshadfield: 
> Might be quite a bit of work as we use a lot of `<Select>` elements.

**Comment by jameshadfield** [comment]
From memory (I can't find the branch / stash anymore) getting styled components to work with react select was difficult. That was a long time ago, so things may have improved.

**Comment by jameshadfield** [comment]
This may also fix #1453 out of the box?

**Comment by joverlee521** [comment]
Turns out the the upgrade from v1 is pretty straightforward ([see `upgrade-react-select` branch](https://github.com/nextstrain/auspice/commit/3db55482177f98a61dd9c2d54a7b161a7af8a2d5)). 
The bigger hurdle is actually replacing `react-virtualized-select` since it is built on top of `react-select` v1 and also no longer maintained.

A few options forward:
1. Use another package with virtualized `react-select` components, maybe [react-select-virtualized](https://www.npmjs.com/package/react-select-virtualized)?
1. Use `react-virtualized` to build our own custom `MenuList` to use with `Select`. 
There are examples of this in https://github.com/JedWatson/react-select/issues/3128
(We can then use `CellMeasurer` from `react-virtualized` to make the options height dynamic.)
1. We can explore other virtualization packages that come with built-in dynamic heights, such as [react-virtual](https://react-virtual.tanstack.com/) or [react-virtuoso](https://virtuoso.dev/)

Option 1 seems like the easiest change _now_, but options 2 & 3 would allow us to tackle #1453.

**Comment by jameshadfield** [comment]
P.S. f9944eb7eda30c5922d229fafe2752f21fa507b4 is the commit which introduced `react-virtualized-select`. I would suggest options 2 or 3, so that we can address #1453.
