### ISSUE TITLE
Clarify definition of mutation categories

### ISSUE THREAD

**Issue by AngieHinrichs** [nextstrain/auspice#1469]
Congrats on the new release!  It's exciting to see the new mutation categories, and I'll have to explode some trees and see what happens.  :)  I just noticed in an [UShER subtree view](https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/auspice_rev_homoplasy.json?branchLabel=back-mutations&c=pango_lineage_usher&label=nuc%20mutations:C2790T,C9866T,T22200G,G22599A,C24503T,T26060C) that the same mutation can be listed as both a Homoplasy and Reversion in the branch pop-up, which I wouldn't expect.  I don't know if it's my [JSON](https://hgwdev.gi.ucsc.edu/~angie/auspice_rev_homoplasy.json) or a logic corner-case or the expected behavior...?

**Current Behavior**  
The reversion G22200T is listed under both "Homoplasies" and "Reversions to reference" in the pop-up:
![image](https://user-images.githubusercontent.com/186983/153993659-4f56f30a-a260-44de-aa1d-b48e54363d26.png)

**Expected behavior**  
I would expect the categories to be mutually exclusive, so G22200T would be just a reversion, not both a reversion and a homoplasy.  I'm not really sure what homoplasy is intended to mean here... is it anything that happens more than once in the JSON, or is it more like Nextclade's new "labeledSubstitution" output?  Or something else?  :)

**How to reproduce**  

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/auspice_rev_homoplasy.json?branchLabel=back-mutations&c=pango_lineage_usher&label=nuc%20mutations:C2790T,C9866T,T22200G,G22599A,C24503T,T26060C

Hover or shift-click on any labeled branch (branches are labeled by reversions).

**Comment by jameshadfield** [comment]
> I would expect the categories to be mutually exclusive, so G22200T would be just a reversion, not both a reversion and a homoplasy. I'm not really sure what homoplasy is intended to mean here...

Thanks Angie -- I need to document these somewhere better than in the commit itself. The groups are not mutually exclusive -- `G22200T` appears at least three times on your tree and is thus both homoplasic, and a reversion to the root state (`T`). Note that "Unique" and "Homoplasies" are mutually exclusive groups!
