### ISSUE TITLE
ENH: Make Esc dismiss sample details popup

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1479]
### Context
I often (shift)-click on samples or branches to see details.

Right now, to dismiss the popup, I need to click outside the popup, requiring a mouse movement which is a little cumbersome.

I've repeatedly found myself hitting `esc` in the expectation that it would dismiss the popup, which it didn't do.

### Description
It would be nice if `esc` dismissed the details popup, just how clicking outside does at the moment.

I'm talking about this popup:
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/25161793/157252976-a6d7071b-35db-438f-a59a-f248c10e6ff9.png">

**Comment by jameshadfield** [comment]
Seems sensible and easy 👍
