### ISSUE TITLE
Tree Confidence Interval d3 errors

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#151]
`PhyloTree.prototype.makeConfidence` throws lots of d3 errors such as 

```
Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "0.00383531745133…".
```

**Comment by colinmegill** [comment]
I have been seeing this too. I think @rneher had an explanation on this one

**Comment by rneher** [comment]
I think https://github.com/nextstrain/auspice/blob/master/src/util/phyloTree.js#L846 should be `confLine`
