### ISSUE TITLE
Truncated display on main monkeypox tree when zooming out

### ISSUE THREAD

**Issue by theosanderson** [nextstrain/auspice#1512]
### Current Behavior
On the monkeypox tree it is possible to get a truncated display like 

![image](https://user-images.githubusercontent.com/19732295/169917486-7fae8223-64ec-4b4f-be48-4a179017cafe.png)

### Expected behavior
One does not get this issue

### How to reproduce
1. Seems to happen more when the pixel-width of the tree is small (narrow window)
2. Zoom into the outbreak node
3. Move back, perhaps 2 nodes up until this happens

### Your environment: if browsing Nextstrain online
 - Operating system: macOS
 - Browser: Chrome
 - Version Auspice v2.37.1

### Additional context
The console spams messages like 
![image](https://user-images.githubusercontent.com/19732295/169917681-6f805fb9-ed24-44d3-87d1-b5125305946f.png) referring to NaNs in a <path

Apologies if this is a known issue

**Comment by victorlin** [comment]
Hey @theosanderson, thanks for describing this! Yes this was brought up internally, and it's an Auspice issue so I plan to file an issue there.

In the meantime, the workaround is to make a slight adjustment the window size while it is buggy. This will make things appear correctly until the page is reloaded.

**Comment by theosanderson** [comment]
Thanks, please feel free to close/edit this issue as desired!

**Comment by victorlin** [comment]
@theosanderson whoops, updated my comment – didn't realize this was already the Auspice repo!

(Nice to see you outside of the the Serratus PRs 🙂)

**Comment by jameshadfield** [comment]
#1513 should fix this, I think. I could never find an easily reproducible way to trigger the :bug:, but it's related to the clipping mask becoming out of sync with the tree scales. I'll push that version of auspice up to dev.nextstrain.org where it should be easier to test (and add a message here when I've done so).
