### ISSUE TITLE
ENH: Annotate forward/reverse strand direction in genemap

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1515]
With monkeypox, we're now analysing a virus genome that has a number of genes on the reverse strand.

It would be nice if we could somehow indicate the direction in the graphical entropy viewer:
<img width="2221" alt="image" src="https://user-images.githubusercontent.com/25161793/171226058-4abd6aab-eacc-4381-bb39-c2d6a153b28b.png">

Maybe with an arrow?

**Comment by emmahodcroft** [comment]
So this is possible in Auspice with a two-strand view - see the TB build, which has genes on both strands. But it needs to specified in the gene annotation.

https://nextstrain.org/tb/global?gmax=4392666&gmin=4279469

Little hard to see but:
![image](https://user-images.githubusercontent.com/14290674/171228293-02d3f32f-7c09-44bd-be2b-40e0fa32b249.png)

A - Zoomed out view, no 'strand view' (same as single-strand viruses).
B - Zoomed in view - if annotated correctly - can show two stands, genes on top and bottom.

**Comment by emmahodcroft** [comment]
In the [TB GFF](https://raw.githubusercontent.com/nextstrain/tb/master/config/Mtb_H37Rv_NCBI_Annot.gff) (warning, big file) you can see in one of the columns it marks `+` or `-` for the strand.

**Comment by corneliusroemer** [comment]
Oh that's cool, I guess we should do this for mpox, that would make it much
nicer to look at.

**Comment by victorlin** [comment]
This will be fixed in Augur by nextstrain/augur#966
