### ISSUE TITLE
BUG: `-` lens sometimes zooms out 2 steps rather than 1

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1529]
### Current Behavior
When clicking the `-` lens, in some cases, Auspice zooms out more than one step

### Expected behavior
Auspice zooms out one internal node at a time

### How to reproduce
Steps to reproduce the current behavior:
1. Open https://nextstrain.org/monkeypox/hmpxv1?c=recency&label=clade:B.1
2. Click on the top branch
3. Click the `-` lens
4. Observe result

The error is reproducible given this tree, I've attached the json here for reproducibility in case we replace the build

Remove the `.txt` ending, it's just present so that I can upload into Github:
[zoomerror.json.txt](https://github.com/nextstrain/auspice/files/8986943/zoomerror.json.txt)

### Your environment: if running Nextstrain locally
 - Operating system:
 - Browser:
 - Version (e.g. `auspice 2.7.0`): 2.37.3

**Comment by corneliusroemer** [comment]
@jameshadfield this bug is quite annoying, I've heard others mention it too - it would be great if you could have a look :)

**Comment by jameshadfield** [comment]
On my to-do list, but probably not this week. Your screengrab looks like a :bug: for sure. Background: there is some complexity here as polytomies are often coded as bifurcations with branch length=0 (or very small) and so in these cases we do want to go back beyond the (literal) parent node.

**Comment by corneliusroemer** [comment]
Ah yeah - the bifurcation thing is annoying 😬 

This would be great to have addressed, it affects every user. Thanks!

**Comment by jameshadfield** [comment]
Looking into this now -- [this is the tree](https://github.com/nextstrain/nextclade_data/blob/master/data/datasets/MPXV/references/ancestral/versions/2022-09-13T12:00:00Z/files/tree.json) where one can reproduce the bug. (Note that it's no longer reproducible in our current https://nextstrain.org/monkeypox/hmpxv1?c=recency&label=clade:B.1)
