### ISSUE TITLE
Overlapping legend entries

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1547]
If the user successively changes the “Color By” parameter the legend entries can overlap. This is not resolvable in-app (as far as I can tell), but has no other side-effects.

![image](https://user-images.githubusercontent.com/8350992/190930740-62baa1e0-9293-4c00-a073-6ba8fab0fc0e.png)

First reported in https://discussion.nextstrain.org/t/captions-overlap-due-to-color-by-parameter/1241

**Comment by joverlee521** [comment]
I noticed the "rate" legend shows duplicate entires in the reported [build](https://next.nextstrain.org/community/KelianP/RYMV-WA?c=rate).

![Screen Shot 2022-09-19 at 12 23 58 PM](https://user-images.githubusercontent.com/40774762/191099830-4ed0daa4-047d-43fa-af5f-8a681b270aed.png)

So I downloaded and viewed the build locally and get console warnings of duplicate keys:

![Screen Shot 2022-09-19 at 12 32 34 PM](https://user-images.githubusercontent.com/40774762/191100330-045e18d1-0bc2-4bb5-b49f-9daf2417cc44.png)

I think the overlap somehow a result of the non-unique keys, but I'm not entirely sure how?

**Comment by jameshadfield** [comment]
Oh that could be it for sure -- react not reconciling the DOM properly due to duplicate keys.
