### ISSUE TITLE
ENH: Show nucleotides as first item in list for genotype coloriung

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1548]
### Context
I often colour by genotype. Particularly in monkeypox with ~200 genes, it's annoying that nucleotides come last. The chance that I care about the first gene in the list is low as there are 200 of them. It would be nice as a result if nucleotides came first.

As nucleotide is probably the most relevant unless there's a gene of particular interest.

It could be best if one could specify which genes/nt should come first. In SC2, for example, it'd be great to start with S, then have nucleotides.

Maybe it's possible to customize the sequence already and I'm just not aware of it? In that case, please close @jameshadfield 

![2022-09-19 18 19 59](https://user-images.githubusercontent.com/25161793/191065246-249d9caf-0e49-4993-9220-0565850e2529.gif)
![2022-09-19 18 20 27](https://user-images.githubusercontent.com/25161793/191065266-da9d37b0-24a4-4df0-aac0-9aa1c59faa3b.gif)

**Comment by jameshadfield** [comment]
> It would be nice as a result if nucleotides came first.

Yeah this does seem sensible in all cases.

P.S. you can start typing after selecting the dropdown, e.g. `nu` or `s` and it'll jump to those entries ;)

**Comment by corneliusroemer** [comment]
I know but then I need to reach for the keyboard 🙈

Just thought being able to specify which few come first before the rest
would be nice. We have a default gene in Nextclade too.

**Comment by emmahodcroft** [comment]
I would second this request, actually. It's long been on my mind, but with the monkeypox builds it's really become a thing, there are just so many genes. I think even without discussion of other gene orders, moving 'nucleotides' to the top of the list by default would be sensible. At the moment I think we just sort alphabetically(?), and so it's just by bad luck that nucleotide falls so far down the list!

**Comment by AngieHinrichs** [comment]
I too am often hunting for nucleotides.  This would be convenient!
