### ISSUE TITLE
Make gene order in genotype color-by customizable

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/auspice#1549]
### Context
Related to #1548 

### Description
Currently, the order of genes in the genotype color-by dropdown option is listed alphabetically, with the exception of "nucleotide" which is added last (which will soon be changed in response to #1548). 

Users may want to highlight an antigenically important gene (e.g. the "S" gene in SARS-CoV-2) and display the gene first in the dropdown. We should allow users to customize the display order of genes in this dropdown in the dataset JSON.

**Comment by jameshadfield** [comment]
They are only alphabetical because that's how augur is exporting them -- the order they appear in the `json→meta→genome_annotations` dict is the order they will appear in auspice's dropdown. It would be nice to be able to customise this, but I think that functionality belongs in augur. (Not sure whether the place for this is `augur translate` or `augur export v2`).

**Comment by jameshadfield** [comment]
I'm going to close this as https://github.com/nextstrain/augur/issues/1052 should resolve

**Comment by joverlee521** [comment]
Hmm, I was thinking the key ordering in `genome_annotations` is not reliable, so it should be a separate array field for listing the order of genes.

**Comment by tsibley** [comment]
JSON objects are technically unordered, but some languages (incl. Python and JS) preserve order when encoding/decoding their native equivalent type to/from JSON objects. So if we care about interop with other JSON encoders/decoders, we may not want to rely on ordering of object fields.

**Comment by j23414** [comment]
Linking the [Advanced Gene Viewing Options](https://discussion.nextstrain.org/t/advanced-gene-viewing-options/1308) question to this issue
