### ISSUE TITLE
Update supported node versions

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1553]
Currently our supported versions are "^12 || ^14 || ^16"

[v12 has reached end-of-life and should be dropped](https://github.com/nodejs/release#release-schedule)

We should support v18. I'm running it day-to-day without problems, apart from needing the `NODE_OPTIONS=--openssl-legacy-provider` flag. My understanding is that this should go away with webpack 5, introduced in #1520.

**Comment by victorlin** [comment]
Relatedly, I noticed that Auspice's Bioconda recipe is out of sync on Nodejs version compatibility. Opened a PR to fix it: https://github.com/bioconda/bioconda-recipes/pull/37229
