### ISSUE TITLE
BUG: Labels make branch covered by it unclickable 

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1580]
### Current Behavior
When there is label text that overlays a branch, the branch becomes unclickable

### Expected behavior
Labels do not act as a real layer that prevents clicks of the branch below 

### How to reproduce
![2022-10-21 12 38 37](https://user-images.githubusercontent.com/25161793/197177616-abe25388-e7ae-4a02-9a9b-a822fdbb0675.gif)

### Your environment: if running Nextstrain onlinee
 - Operating system: M1 Mac
 - Browser: Brave
 - Version (e.g. `auspice 2.7.0`): 2.40.0

**Comment by jameshadfield** [comment]
I think setting the appropriate [pointer-event](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events) on the SVG text element should fix this. I'll take a look...
