### ISSUE TITLE
DEV: Automatic vercel deploys

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1586]
### Context
I've found Vercel deploys of Nextclade very useful to test PRs and master.

Would it be possible to set up Vercel builds in the same way for Auspice?

Right now to test, one needs to test locally.

@ivan-aksamentov has experience setting up Vercel :)

**Comment by ivan-aksamentov** [comment]
As far as I know, [Vercel](https://vercel.com/docs) hosts only static apps, Next.js apps (with a server, but restricted to Next.js specifics), and apps with serverless and/or edge functions [[1](https://en.wikipedia.org/wiki/Serverless_computing), [2](https://vercel.com/guides/using-express-with-vercel)].

Auspice has a Node.js Express-based server component, so it is not possible to deploy it to Vercel as is. 

As far as I know, that server part does not do much other than fetching and re-serving static files, which seems redundant, plus some auth[n,z] for groups, which can probably mostly be moved to the client side, with a slim separate server component doing the required work. Auspice frontend itself just does not look like an app that should have a server app tightly coupled with it.

Alternatively, Heroku, the hosting of the the production Nextstrain website might also have preview deployment functionality and they can run arbitrary Node apps.

**Comment by corneliusroemer** [comment]
Thanks @joverlee521 - unfortunately these test apps disappear as soon as merged?

Do we have a master review app somewhere? It would be nice if nextstrain-bot could set up a master deployment whenever we commit - maybe this exists already?

**Comment by joverlee521** [comment]
> Do we have a master review app somewhere? It would be nice if nextstrain-bot could set up a master deployment whenever we commit - maybe this exists already?

Hmm, we have a staging app for Auspice (https://auspice-dev.herokuapp.com/) but I believe it requires manual deployments and it hasn't been updated since January 2021. I think we moved away from it in favor of the testing apps for nextstrain.org.

**Comment by jameshadfield** [comment]
> I think we moved away from it in favor of the testing apps for nextstrain.org.

Correct -- it only exists now because Heroku requires at least one app in a pipeline in order to have access to review apps.

We could set up a GitHub action to update this app every push to master if that's helpful? I would rather invest effort in making it much easier to release new versions of auspice and have them propogate to auspice.us and nextstrain.org, but perhaps I don't understand your use case correctly

**Comment by corneliusroemer** [comment]
Sure @jameshadfield since you're the main person working on Auspice :) I just found it hard to test your latest work and was wondering whether some easy improvements were possible. Easier and hence more frequent releases sound more useful indeed.
