### ISSUE TITLE
Provide direct URL access to detailed variant information already displayed in the tooltip panel

### ISSUE THREAD

**Issue by ciscorucinski** [nextstrain/auspice#1592]
### Context
Currently, when one goes to the following URL specifically for [Nextstrain: BQ.1.1](https://nextstrain.org/staging/nextclade/sars-cov-2/?s=BQ.1.1), it will not display any detailed information about BQ.1.1; however, with one click, you can view the tooltip panel which has all that information. This feature request is to bypass the need for a manual click to view this information, and to provide a direct link to this data.

This feature would provide the most benefits to 
- Web Scrapers
- Variant Trackers
- Other websites

### Description
This data is the most comprehensive information about each variant outside of the [Cov-Lineages' PANGO Designation Github Issues](https://github.com/cov-lineages/pango-designation/issues), which is harder to parse through. Already available URL's ([cov-lineages.org: BQ.1.1](https://cov-lineages.org/lineage.html?lineage=BQ.1.1) and [outbreak.info: BQ.1.1](https://outbreak.info/situation-reports?pango=BQ.1.1)) lack basic information that can be viewed in the current Nextstrain detailed information tooltip panel.

### Examples
| Display when webpage is loaded| Display when clicking on variant node |
|-|-|
| ![Screenshot from 2022-11-04 21-26-53](https://user-images.githubusercontent.com/8707125/199982994-5170d9d2-0349-4077-9fdd-dfa3864562ff.png) |  ![Screenshot from 2022-11-04 21-27-20](https://user-images.githubusercontent.com/8707125/199983043-a669cc39-50d4-4c34-bb73-0b7fb6ed385f.png) |
| This is what is displayed to users when they use the [Nextstrain: BQ.1.1](https://nextstrain.org/staging/nextclade/sars-cov-2/?s=BQ.1.1) link. Nothing is loaded in the HTML DOM for the detailed information | This is what is displayed to users when they click on a specific variant node. |

### Possible Solution
The solution doesn't even have to load the Nextstrain visualization. It can be something as simple as a JSON response, or anything from another webpage in Nextstrain to an addition to the visualization webpage.

It might be beneficial to allow easily changing ROOT.

**Comment by tsibley** [comment]
@ciscorucinski Everything you see on that nextstrain.org page is backed by data you can access.

For example, try this:

```
curl -fsSL https://nextstrain.org/staging/nextclade/sars-cov-2 \
  --header 'Accept: application/vnd.nextstrain.dataset.main+json'
```

The JSON object will fit the https://nextstrain.org/schemas/dataset/v2 schema.

Typically the source data (and code) that goes into making the Nextstrain datasets are also available, e.g. https://github.com/neherlab/nextclade_data_workflows in this case.

See also https://docs.nextstrain.org/projects/nextclade/en/stable/user/datasets.html for the Next<i>clade</i> datasets, which provide different information.

**Comment by jameshadfield** [comment]
The tip-clicked-modal is not currently stored in URL query state, which would achieve what you're asking for. It probably should be, but the way it's implemented (it's component state, not redux state) means that this hasn't been high enough on the priority list to get to. Hopefully Tom's solution works in the meantime!

**Comment by ciscorucinski** [comment]
Thanks for the input. I'm not certain curl a good method for me right now. I will try to weed through the schema, but I don't think I can directly get that data into Google Sheets as-is.

@jameshadfield 's idea would be perfect. I see the need to create a service that is more user-friendly for newcomers to start doing data analysis with the available data. Using all the tools that current variant trackers use takes too much time to understand and use properly. Potential new variant analyzers could come from such an implementation (given the data can be easily webscraped).

I might have further inquiries about the json dataset when I can figure out how to get it into Google Sheets.
