### ISSUE TITLE
Parse narratives as a single document before breaking into slides

### ISSUE THREAD

**Issue by tsibley** [nextstrain/auspice#1599]
While implementing https://github.com/nextstrain/cli/pull/235, I realized that currently narrative source documents are first split into slides via string manipulation and then converted from Markdown → HTML.

https://github.com/nextstrain/auspice/blob/a416642765e15881b025c23967bf2625f444b3e1/src/util/parseNarrative.js#L90-L118

This causes issues with intra-document references like links and images that reference a definition found elsewhere in the file, if the definition is in a different "slide" than the link/image reference:

```markdown
[some link that's a reference][1]
![an image that's the same][cat]

[1]: https://example.com
[cat]: https://http.cat/599
```

Anyone previewing the document outside of Auspice's narrative rendering would see the link/image references work, but they'd be broken when viewed thru Auspice. Since narrative documents are intended to gracefully degrade with conventional Markdown rendering and still be a viewable document (e.g. [on GitHub](https://github.com/nextstrain/narratives/blob/master/how-to-write_basics.md)), it would be nice to address this issue for that reason.

One approach I'd like to pursue is inverting the order of parsing to render to HTML first and then split into slides. We can make use of the DOM to split the HTML into slides, and it might even be easier than line-wise string manipulation. :-)

**Comment by jameshadfield** [comment]
Yup, this sounds like a good plan!
