### ISSUE TITLE
Move filter query params to redux

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#160]
Query params like `authors` and `geographic%20location` that filter tips via [`RecursiveFilter`](https://github.com/nextstrain/auspice/blob/master/src/components/controls/recursive_filter.js) should be moved from the current call to `changeRoute`:

https://github.com/nextstrain/auspice/blob/master/src/components/controls/recursive_filter.js#L31

To follow the redux / react-router pattern used for `layout`, `colorBy`, etc...

**Comment by jameshadfield** [comment]
closed in PR #182
