### ISSUE TITLE
Narratives with multiple datasets with measurements 

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/auspice#1603]
### Current Behavior
Narratives error when navigating between slides that contain different datasets that both have measurements sidecar JSONs.

### How to reproduce
Steps to reproduce the current behavior:
1. Drag this [test narrative](https://github.com/nextstrain/auspice/files/10118176/test_multiple_dataset_measurements.md) onto the [narratives debugger](https://next.nextstrain.org/edit/narratives).
2. Successfully navigate between slide 1 and 2. 
3. Navigating to slide 3 or 4 will result in error. 

### Additional context
First saw this error in a private narrative for seasonal flu that switched between builds of h3n2, h1n1pdm, and vic that all had measurements sidecars.

**Comment by huddlej** [comment]
@joverlee521 I get a slightly different error but maybe for the same reason when switching between slides in a narrative where the first slide is a standard Auspice view and the second slide has an `auspiceMainDisplayMarkdown` block. Neither slides reference the meaurements panel, but when toggling from the first to second slide, I get the error shown in the screen capture below of "Failed to load measurements collections (intermediate value).map is not a function".

https://user-images.githubusercontent.com/85372/226447589-bb549acb-f01c-4fc5-bb29-42fe8d1cd941.mp4

Sometimes this error happens on the first transition from the first to second slide. Other times it happens only during the second transition down, as shown in the screen capture.

**Comment by huddlej** [comment]
I should have noted that the first slide displays an NA tree while the next slide uses an HA tree as its data URL even though its a fully markdown slide.
