### ISSUE TITLE
Move dataset path to redux / react-router

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#161]
Currently logic of dataset path (ie `/flu/h3n2/3y` vs `/zika/`) is handled through direct manipulation of `window` via [`changeRoute` in App](https://github.com/nextstrain/auspice/blob/master/src/components/app.js#L293). This should be moved to redux / react-router. We'll have stored state in redux and use `router.push` to update URL.

I'd propose to put this in `store.controls` alongside `colorBy`, `layout`, etc..., where `store.controls.dataset` still follows the scheme set up by @rneher in [`parseParams`](https://github.com/nextstrain/auspice/blob/master/src/util/parseParams.js).

**Comment by jameshadfield** [comment]
Keeping this open for now, but moving to backlog, as we aim for launch.

For launch, RR will handle some paths, but `parseParams` will still be employed for the virus dataset logic.

**Comment by trvrb** [comment]
We've just decided that the current setup with react-router loading App (https://github.com/nextstrain/auspice/blob/master/src/index.js#L41) and then App querying the URL (https://github.com/nextstrain/auspice/blob/master/src/components/app.js#L77) is the right way to go.
