### ISSUE TITLE
Scatterplot not displaying negative values for ACE2 binding

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/auspice#1626]
The scatterplot view does not display the negative values for [ACE2 binding](https://nextstrain.org/ncov/gisaid/global/6m?c=ace2_binding&l=scatter&scatterX=ace2_binding):

![Screen Shot 2023-01-19 at 2 16 14 PM](https://user-images.githubusercontent.com/40774762/213574517-dc5ee4c1-2f0a-4e16-a330-fdba4e9435b4.png)

The negative values _**are**_ displayed properly for other continuous color-bys such as [Logistic Growth](https://nextstrain.org/ncov/gisaid/global/6m?branches=hide&c=logistic_growth&l=scatter&scatterX=logistic_growth) and [Mutational Fitness](https://nextstrain.org/ncov/gisaid/global/6m?branches=hide&c=mutational_fitness&l=scatter&scatterX=mutational_fitness):

 ![Screen Shot 2023-01-19 at 2 31 57 PM](https://user-images.githubusercontent.com/40774762/213577040-d6830a05-11c8-4d41-aa9f-0fb9573c9c2b.png)

This was a bug reported/discovered during Nextstrain office hours on 2023-01-19.

**Comment by joverlee521** [comment]
Looked at the underlying Auspice JSON and found that ACE2 binding field values are **strings** while the Logistic Growth and Mutational Fitness values are **floats**. The string values would cause the checks for the [minX](https://github.com/nextstrain/auspice/blob/c373bb21a45666120d34f158a18780e7802d84e4/src/components/tree/phyloTree/layouts.js#L362-L367) and [minY](https://github.com/nextstrain/auspice/blob/c373bb21a45666120d34f158a18780e7802d84e4/src/components/tree/phyloTree/layouts.js#L392-L397) values to not work as expected. 

All continuous field values should probably be converted to floats within Auspice, but maybe this is also an issue in `augur export`?

**Comment by corneliusroemer** [comment]
Thanks for looking into this @joverlee521 

Why do they end up as strings? In the nextclade_data_workflows/sars-cov-2 case:
- in metadata.tsv they are not quoted, just bare floats
- they are added in auspice_config as "continuous"
- but export turns them into `"ace2_binding": {"value": "-0"}`

I presume it's similar in ncov.

However auspice knows that this trait is continuous, so it should always parse it as a number, and not treat it as string.

So I don't think this is an export bug. It's an Auspice bug.

Could we move this out of backlog? I think this would be quite important to fix.

@jameshadfield

**Comment by tsibley** [comment]
All values in a CSV are strings, since CSV doesn't have data types. Types may be inferred upon parsing, but such inference is often fragile and prone to bugs. So I'd think if `augur export` knows a field should be numeric, then it should parse it as such and export it to JSON as such.

Auspice should maybe also force it to numeric regardless of its JSON data type, iff Auspice knows the field is supposed to be numeric.

**Comment by jameshadfield** [comment]
> consider it both a bug in export ... and a bug in Auspice

I think this is fair. For instance, here are the types seen across the tree for the 6 continuous traits in the 21L dataset (used in the duplicate #1653 issue), so it looks like augur is exporting as all strings or all numbers - perhaps conditional on the presence of negative values?

![image](https://user-images.githubusercontent.com/8350992/227054499-5a751d45-eb44-4fda-8748-f5cef79ab203.png)

I'll add a fix in auspice for this now, which may or may not be enough to fix this particular scatterplot bug.

**Comment by tsibley** [comment]
@corneliusroemer Yep, that's right.
