### ISSUE TITLE
Running Auspice On Development Mode Not Working

### ISSUE THREAD

**Issue by YasirKusay** [nextstrain/auspice#1627]
Hi,

I wanted to try to change something in the auspice output and installed this repo locally. After running NPM install, I had a problem. The initial problem was:

`Error: Cannot find module '../webpack.config.js' in both cli/build.js and cli/develop.js`. 

I did notice that there was a webpack.config.js in node_modules so I changed the lines: require("../webpack.config.js").default; in both files above to: require("webpack.config.js").default. However now this resulted in another issue: 

`TypeError: generateWebpackConfig is not a function`.

I also ran node augur.js build and got the same error.

Could someone help me out?

 - Operating system: macOS Monterey (version 12.5.1)
 - Browser: Google Chrome
 - Version 2.42.0 (downloaded directly from repo)

**Comment by tsibley** [comment]
Hi @YasirKusay. The `webpack.config.js` those files are looking for is in the root of the repository ([view it on GitHub](https://github.com/nextstrain/auspice/blob/master/webpack.config.js). It should be in your download of the repo.

Can you share more about the exact commands you're running and their complete output? I think we need that information to troubleshoot this effectively.

**Comment by YasirKusay** [comment]
Hi @tsibley, thank you for your reply. I ran:

```
node auspice.js build
```

The output was:

```
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '../webpack.config.js'
Require stack:
- /Users/yasir/Desktop/work/auspice/auspice/cli/build.js
- /Users/yasir/Desktop/work/auspice/auspice/auspice.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/yasir/Desktop/work/auspice/auspice/cli/build.js:3:31)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/yasir/Desktop/work/auspice/auspice/cli/build.js',
    '/Users/yasir/Desktop/work/auspice/auspice/auspice.js'
  ]
}
```

I am getting the same issue also when running ```npm install .```

**Comment by YasirKusay** [comment]
Hi @tsibley, 

The ```webpack.config.js``` was indeed missing from root. I added it to my root manually and now the program works. Thank you for your help.
