### ISSUE TITLE
Radial phyloTree bug

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#163]
I'm getting the following error:

```
Error: <path> attribute d: Expected number, " M NaN NaN L 258.06…".
```

when loading radial (http://localhost:4000/zika/?l=radial). Other layouts are fine.

**Comment by rneher** [comment]
I am not getting this. which branch?

**Comment by trvrb** [comment]
I'm getting this now on `master` (032d5948f2e84c7dfd29fbf0fc3a3c048d0bbb0a) when loading: http://localhost:4000/zika/ and then switching to radial.

Ah! But I'm not getting this in Firefox. Seems to be Chrome only.

**Comment by trvrb** [comment]
Nice catch.
