### ISSUE TITLE
Inconsistent Output between Similar Builds

### ISSUE THREAD

**Issue by YasirKusay** [nextstrain/auspice#1630]
Hi,

This is something I noticed while working on my own builds. Using the official zika build (https://nextstrain.org/zika), if I wanted to Color By genotype, using gene 2K and position 1, even though there is no diversity between this amino acid position, it still displays the amino acid on the chart. 

<img width="830" alt="Screen Shot 2023-01-30 at 7 05 41 pm" src="https://user-images.githubusercontent.com/59812220/215421258-8231a754-c5f1-4318-849e-19b2048dafe8.png">

However, this is not consistent with the results obtained when viewing the zika build on auspice.us. I built the dataset from here (https://github.com/nextstrain/zika) and when I wanted to do the same thing as above, the amino acid positions are not displayed and the tips are all grey. 

<img width="834" alt="Screen Shot 2023-01-30 at 7 05 14 pm" src="https://user-images.githubusercontent.com/59812220/215421180-334825fa-387b-4c75-b6b4-f867426c1e25.png">

When working on my own dataset, I originally though it may have been the result of additional options during the augur step or withing auspice_config.json but I found no such thing. Is it possible to have the tree be displayed similar to the official build?

**Comment by emmahodcroft** [comment]
Dear @YasirKusay - thanks for reaching out! My guess is that the problem behind this is whether Auspice (which interpret such output files) had access to the root sequence or not. My guess is that as well as the main result JSON you also have one called something like `zika_root-sequence.json`. This is Auspice has to get the base of any location where there's no diversity. Our default builds will have these files uploaded alongside the main JSON, so Auspice will load them as well.

You can drag both the main JSON and the root-sequence JSON into auspice.us at the same time, and it should then load both of them, allowing you to also colour by positions where there's no diversity!

**Comment by YasirKusay** [comment]
Thank you for this, it is working now! I do apologise for labelling this as a "bug" as I did not know what other tag to use.

**Comment by YasirKusay** [comment]
Just an extension to the above, if I was viewing my datasets locally, how can I add the root sequence file to this.

**Comment by emmahodcroft** [comment]
Glad it worked @YasirKusay ! If you are viewing locally, just ensure that the main `x.json` and `x_root-sequence.json` are together in the same location and Auspice will automatically look for any accompanying files to `x.json` (there can also be a `x_tip-frequencies.json` in some cases). This is how it works both online and locally - Auspice.us is the exception here only because obviously you have to drag the files to it!
