### ISSUE TITLE
Button to zoom directly to a filter

### ISSUE THREAD

**Issue by theosanderson** [nextstrain/auspice#1634]
### Context
At the moment as I understand it the pattern if you want to zoom to a particular sequence/clade with Auspice is to adjust visibilty until it the only thing you are filtering on, and then click "zoom to selected". IMO this isn't super intuitive as the only means of doing this, and it involves quite a few steps (this observation comes in part from doing some teaching with Auspice -- which was great in general).

### Suggestion
My suggestion is that the filter display offers a way of directly clicking to zoom to this filter, without altering visibility settings.
<img width="123" alt="image" src="https://user-images.githubusercontent.com/19732295/221588573-dade1e45-f88a-4716-bdc5-6bcc26df5676.png">

One could imagine another icon next to the eye with a magnifying glass, or potentially just clicking on the text could trigger the zoom, if there was an appropriate tool tip.

(Just an idea, no pressure)

**Comment by jameshadfield** [comment]
Hey @theosanderson 

Zooming could be improved more generally I think, but I haven't worked out a compelling generalist approach. For instance, it's really hard to zoom into basal samples. 

> My suggestion is that the filter display offers a way of directly clicking to zoom to this filter, without altering visibility settings.

This seems promising. The code is written such that visible / selected / filtered-on tips must always be in the viewport, and doing this would break that approach. It'd be easy to directly zoom to "19B" (and turn all the other filters off), but I don't think that's what you're getting at. I'll keep thinking on this...

**Comment by theosanderson** [comment]
Thanks @jameshadfield! I'm gonna close this to get it out of your hair. 

>The code is written such that visible / selected / filtered-on tips must always be in the viewport, and doing this would break that approach.

Ah yeah, I definitely hadn't (consciously) picked up on this, that I can click on a clade then filter on country and then I am specifically zooming to things from that country within that node. I can see that that (nice) feature makes the logic quite different.

In UX terms I could imagine a situation where mousing over 
<img width="110" alt="image" src="https://github.com/nextstrain/auspice/assets/19732295/43f1261b-b359-41d8-b509-e4a5b128219b"> causes those 52 nodes to visually indicate themselves (get bigger or something) and clicking causing the UI to zoom from wherever it was to encompass those 52.) but in terms of the practicalities of code I'm sure it doesn't make sense.
