### ISSUE TITLE
BUG: Minima tips not highlighting when hovering over coloring legend

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1654]
Bug similar to the one fixed in #1643 is still unfixed in 2.45.2:

Continuous scales where nodes are negative: The bound for the first (smallest) legend entry is never included as a match. When hovering over a legend swatch, it does not highlight (increase the radius of) matching nodes whose value are the minimum

When you hover over -3.62, it doesn't highlight the blue dot - the blue dot is never highlighted

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/25161793/226963878-2164aba4-d0aa-4761-a680-a43ae61ac0aa.png">

https://next.nextstrain.org/nextclade/sars-cov-2/21L?c=ace2_binding

_Originally posted by @corneliusroemer in https://github.com/nextstrain/auspice/issues/1643#issuecomment-1479836668_

**Comment by jameshadfield** [comment]
I expect this to be fixed by #1644 but I'll keep this issue open to double check (see https://github.com/nextstrain/auspice/pull/1643#issuecomment-1480157246)
