### ISSUE TITLE
Filtering being deactivated after clicking away from metadata popup

### ISSUE THREAD

**Issue by kvargha** [nextstrain/auspice#1701]
### Current Behavior
When you click on a filtered sample and click away from the popup, the filter becomes deactivated.

### Expected behavior
The filtered shouldn't be deactivated.

### How to reproduce
Steps to reproduce the current behavior:
1. Visit https://nextstrain.org/fetch/storage.googleapis.com/ucsc-gi-cdph-bigtree/CDPH_09_20_2023/CDPH-subtree-178.json?s=USA/CA-CDPH-2000016698/2021%7CEPI_ISL_2782613%7C2021-01-04,USA/CA-CDPH-2000016731/2021%7CEPI_ISL_2782386%7C2021-01-03
2. Click "Zoom To Selected"
3. Click on a sample
4. Click away the popup.
5. Samples filter should be deactivated.

### Your environment: if browsing Nextstrain online
 - Operating system: macOS 13.5.2 (22G91)
 - Browser: Chrome Version 117.0.5938.88 

### Additional context
![Auspice Recording](https://github.com/nextstrain/auspice/assets/35252220/bf520646-3d90-4c6a-ab32-cf05f24a8f0e)

**Comment by sabbymama** [comment]
I'm being ghosted by my sequences whenever I click on them.  Will this be fixed soon?

**Comment by joverlee521** [comment]
Noting this bug is part of the larger issue of the tip modal state not being accurately tracked in the redux state as described by @jameshadfield in https://github.com/nextstrain/auspice/issues/1243#issuecomment-977165516.

**Comment by kvargha** [comment]
Thank you for providing the background @joverlee521. Is there an estimate of when it will be fixed?

**Comment by kvargha** [comment]
@jameshadfield I'm still experiencing this issue.

**Comment by victorlin** [comment]
@kvargha the fix was merged and released in Auspice version 2.52.0, but nextstrain.org has not been updated yet. We may do that sometime this week. In the meantime, you can use https://next.nextstrain.org which is automatically updated with the latest version of Auspice.

**Comment by kvargha** [comment]
Gotcha. Thank you @victorlin.
