### ISSUE TITLE
Clade zoom and filter

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#172]
Currently, the info panel has separate options to "Zoom into this clade" and "Filter to this clade". I think this is going to be confusing to have both. I'd propose to combine these. If you zoom into a particular clade so it takes up the entire tree panel then other bits of the app (like the map) should reflect this change in perspective. Ie I can't think of good situations where you would really want to zoom and not filter or filter and not zoom.

This would have the additional benefit of simplifying the UI interaction. We could also consider restoring the click-on-branch-itself-to-zoom. This is a separate conversation however. I'll start a different thread for it.

**Comment by rneher** [comment]
`zoomIntoClade` calls a function of `phyloTree` that marks all children as `inView=true`  This could be combined with other filters in `tipVisibility`. But clade filters are data set specific

**Comment by trvrb** [comment]
This was resolved in PR #208.
