### ISSUE TITLE
[dev] hot-reloading broken

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1737]
Running `auspice develop ...` works fine initially, but as soon as the code rebuilds it is no longer viewable in the browser. Firefox displays "The page isn’t redirecting properly. Firefox has detected that the server is redirecting the request for this address in a way that will never complete". It looks like we're getting into a infinite loop of 302 redirects to the same page ("/"). 

### How to reproduce
Steps to reproduce the current behavior:
1. `auspice develop`
2. load localhost:4000 - note that all works as expected
3. Change some code, you should see "webpack building..." in the terminal 
4. Refresh localhost:4000

### Possible solution
The bug is present at current master (40befc6ea4ac02226db2f5658faa12beda52a3e1).
Bisecting indicates the bug was introduced in #1733

**Comment by victorlin** [comment]
Seems to be weird interaction between [Hot Module Replacement](https://webpack.js.org/concepts/hot-module-replacement) and [output.clean](https://webpack.js.org/configuration/output/#outputclean). A search led me to https://github.com/webpack/webpack-dev-middleware/issues/861. Odd that the comments seem to imply `CleanWebpackPlugin` shouldn't work, but it does in our case. I'll make a PR to revert.
