### ISSUE TITLE
Add URL parameters for the measurements panel options

### ISSUE THREAD

**Issue by huddlej** [nextstrain/auspice#1815]
## Description

Modifications to the measurements panel display state should modify the URL state accordingly and the measurements panel should set its state on load based on the parameters provided through the URL. This functionality will make the measurements panel behave like the rest of the Auspice panels and allow us to share curated measurement panel views with collaborators and in narratives.

Specific state changes that need parameters include:

- [x] selected collection (by collection key)
- [x] grouping (e.g., "reference_strain" or "clade_reference")
- [x] display mode ("raw" or "mean")
- [x] toggle to show overall mean/std
- [x] toggle to show thresholds
- [x] filters (e.g., `reference_strain=A/Stockholm/18/2011` or `reference_strain=A/Stockholm/18/2011,A/Wisconsin/67/2005` or `serum=TAIWAN/8/2002-MELB`)

## Design questions

 - Should measurements-specific URL parameters have a prefix like `m_` to distinguish them from other panel parameters and avoid conflicts?

**Comment by joverlee521** [comment]
Braindumping notes for keeping track of what happens in Redux state.

### Initial load of a dataset with measurements

1. `changePage` calls `chooseDisplayComponentFromURL` which should return `datasetLoader` and dispatches action `PAGE_CHANGE`.
2. This updates the Redux state `general.displayComponent`, which triggers a re-render of the `MainComponentSwitch`. 
3. This renders `DatasetLoader` the component, which dispatches `loadJSONs` and another `PAGE_CHANGE` action to switch to the `Main` component that displays the dataset.
4. `loadJSONs` uses the URL to determine the dataset to fetch then fetches the main dataset JSON and dispatches `CLEAN_START` action with the state returned from `createStateFromQueryOrJSONs`. 
5. Within `createStateFromQueryOrJSONs`, the default measurements state is set by `getDefaultMeasurementsState` but no measurements controls are set. Other controls are updated with `modifyStateViaURLQuery` 
    - **This is where measurements URL prams should be parsed to modify the measurements state/controls !** 
7. Once the clean start action is complete, back in `loadJSONs`, the sidecar JSONs are fetched and loaded. 
8. `loadMeasurements` is dispatched and the measurements controls are set to the initial state defined in the measurements JSON.
    - **This is where previously set measurements state from URL params need be used for initial load of the measurements**
