### ISSUE TITLE
CI: Should warnings should cause the lint job to fail?

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/auspice#1839]
Originally proposed by @victorlin in https://github.com/nextstrain/auspice/issues/1837#issuecomment-2315934134

> Proposal to prevent this in the future: warnings should cause the lint job to fail ([how](https://github.com/eslint/eslint/issues/2309#issuecomment-219828044) and [why](https://dev.to/thawkin3/eslint-warnings-are-an-anti-pattern-33np))

**Comment by joverlee521** [comment]
If the lint job fails due to warnings, the current publish job will not run:

https://github.com/nextstrain/auspice/blob/c5857225f2911091fac20395e091031c79683b11/.github/workflows/ci.yaml#L115-L117

This would force us to resolve all lint warnings before releasing

**Comment by victorlin** [comment]
> This would force us to resolve all lint warnings before releasing

Seems fine to me. I wouldn't expect this to happen often (if at all). Changes that make their way into `master` through a proper PR will surface warnings on the PR itself which should be resolved before merging. The only time when this might happen is if a commit is pushed directly to `master`. In that case I think it's reasonable to fix up before release. If we really wanted to for whatever reason, we could temporarily tweak the rule to remove the `lint` dependency from `publish`.
