### ISSUE TITLE
splash image licences

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#190]
Currently images styled in lunapic with the grey filter
Images:
* https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/197-Zika_Virus-ZikaVirus.tif/lossy-page1-800px-197-Zika_Virus-ZikaVirus.tif.jpg
* http://www.cidresearch.org/uploads/12/10/ebola_virus_particles_budding_VERO_E6_cell_blue_yellow_NIAID.jpg
* http://cdn1.bostonmagazine.com/wp-content/uploads/2013/10/flu-virus-main.jpg

### Todo:
* Check lunapic allows use of images
* Are we all happy with the _grey_ filter?
* Check licences of each image and replace if necessary

**Comment by trvrb** [comment]
* I think lunapic is fine: http://www.lunapic.com/support/content/3/36/en/can-i-use-images-modified-by-your-site-for-commercial-use-if-i-site-you-pages.html?highlight=copyright
* I think the grey filter is great.

Zika is CC BY 4.0: https://pdb101.rcsb.org/motm/motm-image-download. There are a whole bunch of illustrations by David Goodsell, but the only a limited selection of whole virion illustrations (though Zika, Ebola and dengue among them). Having trouble tracking down licensing for Ebola and flu.

**Comment by trvrb** [comment]
This needs to be resolved. Just adding attribution text will do it.
