### ISSUE TITLE
Branches change color on hover when coloring by genotype

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1903]
On next.nextstrain.org (v2.61.1) I encountered something super weird: branches would change color when hovering over them when coloring by genotype.

See attached GIF for a demonstration (this was captured on mpox clade I build):
![2024-11-16 17 09 29](https://github.com/user-attachments/assets/73ca3cf7-b6d0-4fe4-97e4-9f077a4c6042)

https://next.nextstrain.org/mpox/clade-I?c=gt-nuc_107670&gmax=108670&gmin=106670&m=div&r=location

It appears that the new color after hovering is correct - so it seems that the bug is that the color didn't update earlier, and also that the tips don't ever change color the way they should.

**Comment by jameshadfield** [comment]
We've had a bug similar to this in the past which was triggered by multiple d3 updates issued in quick succession (e.g. change colour and change position); the updates essentially overlap and cause the very strange out-of-sync errors that you see here. When hovering over branches we change the colour to highlight the hovered branch which has the side-effect of setting the correct colour; tips don't have this behaviour which explains what's happening in your screenshare above.

Loading the URL doesn't recreate the bug, which matches my expectation that it's generated by a particular set of actions. If you find a series of steps which reproduces it please share as I'd like to eradicate these kinds of bugs!

**Comment by corneliusroemer** [comment]
I will let you know if I find a way to reproduce! I need to up my repro skills 🫣
