### ISSUE TITLE
Known map issues for Feb release

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#198]
- [x] fix duplicate render regression
- [x] fix switch dataset regression
- [x] region vs country vs division switching
- [x] remove play button
- [x] fix lines wrapping around regression
- [x] colorBy date scales
- [x] arrows do not always appear and are not always properly sized
- [x] add zoom level as input to triangles so as not to add thousands of them as lines elongate (perf)
- [x] proper coloring when loading on region or division
- [x] branch thickness

**Comment by rneher** [comment]
I got `this.state.responsive is null` on data set switch called by `createMapDiv`

**Comment by rneher** [comment]
changing colorBy  seems to add new transmissions rather than replace the old ones.

**Comment by rneher** [comment]
Ignore stuff above, but I do get an error when loading http://localhost:4000/ebola?c=division directly. `this.state.d3DOMNode is null`

**Comment by trvrb** [comment]
Other issues (looking at `map-v2` / 798317045642a3f3be9d88fe2f3ca1a660908fa3):
* Remove "Play" button 
* If you zoom way into the map, it becomes super slow. Have to wait 5 seconds for a response after zoom.
* Initial load of http://localhost:4000/zika?c=region fails to color tree and fails to show the map. Note that `master` / 43ca13d886dd56cd83c043610c3febb3c8620438 correctly loads colored tree.

**Comment by colinmegill** [comment]
@trvrb pushing a hopefully 'good enough' fix where the map is only a *little* laggy and just on Zika at the most zoomed in. This accomplishes two complimentary tasks - showing a reasonable amount of arrows when Zika is fully zoomed out (default) and ebola when on division and fully zoomed in (where that one looks good). If it's not good enough for this week, we can tweak further and see where we want to have tradeoffs.

**Comment by colinmegill** [comment]
Fallback on first key in geo structure when we don't have a key
Zoom to bounds

**Comment by colinmegill** [comment]
Switching between country and division removes arrows

**Comment by colinmegill** [comment]
Branch thickness

**Comment by rneher** [comment]
I couldn't figure out why markers disappear -- but I now added them as mid markers of the path and that works well.
