### ISSUE TITLE
Frequencies data doesn't reflect accessor

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#2]
```
d3.json(path + file_prefix + "frequencies.json", function(error, json){
  console.log(error);
  frequencies = json;
  pivots = frequencies["mutations"]["global"]["pivots"].map(function (d) {
    return Math.round(parseFloat(d)*100)/100;
  });
```

http://nextstrain.org/data/Zika_frequencies.json

there is no ["mutations"], is this the right request url?

**Comment by trvrb** [comment]
This is an issue with the [current zika pipeline](https://github.com/blab/nextflu/blob/master/augur/src/Zika_process.py#L159). It's not fully estimating frequency trajectories the way the [flu pipeline](https://github.com/blab/nextflu/blob/master/augur/src/H3N2_process.py#L333) does.

At nextflu.org we show a panel with trajectories:

<img width="706" alt="frequencies" src="https://cloud.githubusercontent.com/assets/1176109/15713826/dfc5d1f2-27cc-11e6-8695-fbd111ddc305.png">

that's not present in the current page at nextstrain.org/zika/. With the full pipeline, there is a `frequencies["mutations"]` key. Take a look at [H3N2_3y_frequencies.json](http://nextflu.org/data/H3N2_3y_frequencies.json) for the full version of what the json should look like.

**Comment by rneher** [comment]
I think we should separate entropy from frequencies and have two different files `entropy.json` and `frequencies.json`. the latter could then be flat, i.e., `{`pivots`:[2014,2015,2016,], `mutation_1`:[0.1, 0.2, ...]}` (where `pivots` are values on the x-axis). I would also take the clade frequencies out of the tree (they are easily 500kb). the clade frequencies could simply be added to `frequencies.json`

**Comment by trvrb** [comment]
I like this suggestion.
