### ISSUE TITLE
Datasets and query params

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#21]
We should have a config JSON that gives all the options for which datasets can be loaded. This will look something like:

```
{
"viruses": {
  "flu": {
    "lineage": {
      "H3N2": {
        "duration": {
        "3y",
        "6y",
        "12y" }
      },
     "H1N1pdm": {
        "duration": {
        "3y",
        "6y",
        "12y" }
      }      
    }
  },
  "zika": {}
  }
}
```

This should be used to create a dataset file string. If this string changes then data should be refetched.

Whenever query params come in, go through this JSON and build dataset.

**Comment by trvrb** [comment]
e6c64d05497e0741d83d9811e57187d143a52e60 gives this JSON.

**Comment by trvrb** [comment]
Here's the proposed structure for currently computed datasets: https://github.com/blab/nextstrain-auspice/blob/datasets/data/datasets.json.

**Comment by rneher** [comment]
A similar json could specify host and `geo` granularity. 
```
{
'insects':{'fly':{}, 'moskito':{'tiger','nasty', ...}, ...},
'mammals':{'cattle':{}, 'hamster':{}, ...}
}
{'NorthAmerica':{'Mexico', 'US':{'CA', 'NY', ..}, 'Canada'},
}
```

**Comment by colinmegill** [comment]
Right now this is in globals, which is good enough for OSP

**Comment by trvrb** [comment]
Leaving this in globals for the moment seems okay. Will rely however on `zika_meta.json` and `ebola_meta.json` containing all the relevant auspice display parameters.

**Comment by rneher** [comment]
colors and geo all sit in meta now.
