### ISSUE TITLE
Throttle date slider

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#210]
Manipulating date slider in production (see dev.nextstrain.org) causes too many redux updates to fire. You can see the URL spin while the date slider catches up. Redux events should be throttled.

**Comment by jameshadfield** [comment]
Before I start this - do we still want the effects (tip vis) to change as often as they currently do? Because they get redux actions at the same frequency. Note that the URL is overwritten - it's not creating a bunch of history

**Comment by trvrb** [comment]
Yes. Great with the history. I _think_ you can just throttle redux actions to 100ms or whatever. Each event should update the URL and redraw tip visibilities. Okay to share redux updates.
