### ISSUE TITLE
Tree card is no longer responsive

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#211]
Something happened in the course of getting pan and grid and tooltip working. Here's the current behavior in `master` / c9979daef980b8537a6a933c6e8e540fe6d2f3d5:

![sidebar-collapse-bug](https://cloud.githubusercontent.com/assets/1176109/23336702/2de65c88-fb8c-11e6-8038-2177f5d44721.gif)

Resizing window or collapsing sidebar does not trigger a proper resize of the tree card.

I'm pretty sure this is something with the version of the ReactSVGPanZoom component. If I go back to 7c46876d833aba5dcccb24d11270ed2488a1111d and then run `npm install`, it's working again.

If I return to `master` / c9979daef980b8537a6a933c6e8e540fe6d2f3d5, leaving the old version of ReactSVGPanZoom, it's still working.

So, something wrong with `"react-svg-pan-zoom": "2.5.0"`. But we need the newer version to keep pan working (?). Will need to investigate more.

Maybe this is more obvious to you @rneher?

**Comment by trvrb** [comment]
_I see..._ We need the `id` to attach to. Colin added it here:

https://github.com/nextstrain/react-svg-pan-zoom/commit/78b5c92cdaf8ddc5ed5c164cd975b2b6bbf0e496

And then compiled to `dist` here:

https://github.com/nextstrain/react-svg-pan-zoom/commit/c189a81729500a65a5e7acefa2bcbd7813f55038

@colinmegill --- I've made an `auspice` branch on nextstrain/react-svg-pan-zoom: https://github.com/nextstrain/react-svg-pan-zoom/tree/auspice. Keeping this patch on a separate feature branch should make it easier to update to new upstream versions. I see what you did to create the dist, but I'm having trouble making it myself. Could you take care of this? And update our `package.json` as well?

**Comment by jameshadfield** [comment]
This happens when resizing the window as well (5c7b46fe354b46cea8a84b67844227782b9cbfc0)

![image](https://cloud.githubusercontent.com/assets/8350992/23371494/1dda85ac-fccd-11e6-844d-954f3d46ab5d.png)

**Comment by trvrb** [comment]
I think (hope) adding back in the `id="nextStrainTreeSVG"` will fix much of this, per above.
