### ISSUE TITLE
release script

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#230]
- [ ] update version number (in a js file and in `package.json`) & commit to `master`
- [ ] checkout `release` branch & merge `master`
- [ ] tag with version
- [ ] push to github
- [ ] push to heroku
- [ ] google-analytics code switches from dev to production based on `NODE_ENV`

(won't do until tomorrow so let me know if you favour a different approach)

**Comment by trvrb** [comment]
This looks super useful.
