### ISSUE TITLE
Grey line on clock improvements

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#234]
![image](https://cloud.githubusercontent.com/assets/1770265/23386665/9cb94798-fd0c-11e6-9ee4-3de815eac512.png)

- [ ] dark grey
- [ ] dashed
- [ ] thicker
- [ ] rate estimate next to the line in the top right

**Comment by colinmegill** [comment]
Also, should divergence selector be available on clock?

**Comment by trvrb** [comment]
No. "Branch length" metrics should be grayed out.

**Comment by colinmegill** [comment]
Ok, they are currently available, remove the grey line and rate estimate, do not change the axes, but do not break anything.
