### ISSUE TITLE
Dynamically add tip labels

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#237]
For SVG performance (especially when transitioning), we need to dynamically add and remove branchLabels and tipLabels from the DOM. With a zoomed tree with labels showing, I bet it's going to be safe to transition the ones that are visible.

**Comment by jameshadfield** [comment]
Somewhat temporarily fixed in c347f582bd4a4af9a25be6824e46618f8ded1fb3 where I draw them iff < 50 tips inView, and they appear after the branches/tips have transitioned

**Comment by jameshadfield** [comment]
- [ ] only active / "on" tips have labels
- [ ] new tips come into view via a L->R transition  
- [X] pan doesn't change active tips
- [ ] better tip in/out transitions

**Comment by kairstenfay** [comment]
@jameshadfield should tip labels be re-calculated each time `drawTips()` is called?

**Comment by kairstenfay** [comment]
I believe commit 579c524 addresses the final bullet point.

**Comment by kairstenfay** [comment]
https://github.com/nextstrain/auspice/pull/728 addresses the parts of this issue where tip label visibility would not update after Date Range change, and where tip labels would not re-appear after layout change.

**Comment by jameshadfield** [comment]
Closing in favor of #915 #916
