### ISSUE TITLE
Map bounds not quite right

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#238]
On `master`, I'm getting transition lines for Zika that go right to the border of the map, but look like they stop before they should:

<img width="1087" alt="map-bounds" src="https://cloud.githubusercontent.com/assets/1176109/23388596/128cf482-fd31-11e6-8cdb-d3daa62edb34.png">

**Comment by jameshadfield** [comment]
the (just pushed) dev.nextstrain.org version looks a bit different

![image](https://cloud.githubusercontent.com/assets/8350992/23388835/6b4aa51e-fd19-11e6-8c34-d884f826eca3.png)

**Comment by trvrb** [comment]
I'm getting the image above (in my post) on `dev.nextstrain.org` from my laptop when doing a shift-refresh.

**Comment by jameshadfield** [comment]
strange my image is from dev.nextstrain version 0.3 (the latest) so perhaps different browsers?!?

**Comment by trvrb** [comment]
My guess is just different screen widths.

**Comment by trvrb** [comment]
Fixed in #330.

**Comment by trvrb** [comment]
Closed by #330.
