### ISSUE TITLE
Color reload bug

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#246]
Going repeated from splash to app to splash to app causes colors to disappear. All tips show up as black.

![color-bug](https://cloud.githubusercontent.com/assets/1176109/23437385/f0acb8ce-fddb-11e6-9848-fa6c72a5f417.gif)

**Comment by trvrb** [comment]
Also, redux is not properly clearing when going back and forth between app and splash. Things like tree layout are divorced from URL.

<img width="1310" alt="tree-layout-bug" src="https://cloud.githubusercontent.com/assets/1176109/23437461/3c589054-fddc-11e6-9a08-5171db87943b.png">

**Comment by jameshadfield** [comment]
i've just fixed the second part

**Comment by trvrb** [comment]
My mistake. Sorry.
