### ISSUE TITLE
Linux friendly alternative to fsevents?

### ISSUE THREAD

**Issue by metasoarous** [nextstrain/auspice#248]
It would be nice if those of us without Macs could use the reload-on-save goodness of React in development, but this isn't possible with the default `fsevents` module for watching the filesystem. There appears to be a lib (https://www.npmjs.com/package/chokidar) that tries to use `fsevents` when possible, and reverts to some other node modules otherwise. Does this seem like a reasonable thing to add?

**Comment by metasoarous** [comment]
My mistake; Turns out there already is a fallback in the current setup. Not sure why the rebuild wasn't triggering initially, but it is now :-)

**Comment by rneher** [comment]
I have been running it on linux (ubuntu 16.04) all along -- there is a warning on build but it works.  thanks for the input!
