### ISSUE TITLE
Map node hover highlights, click subsets nodes in tree

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#266]

**Comment by trvrb** [comment]
Mouse over of map deme should definitely highlight tree tips (exactly like legend hover), I am unsure now, whether clicking a map deme should filter.

**Comment by trvrb** [comment]
Mouse over a map deme could highlight the underlying district / country polygon.

**Comment by trvrb** [comment]
I think that mousing over map demes should act just like mousing over legend items. Legend items don't click to filter. Clicking on map demes should also not filter.

**Comment by jameshadfield** [comment]
My view is that we _should_ be able to click on the legend icons to filter. For discrete traits this is identical to the filters as they exist. For continuous variables, we already create a mapping of the (continuous) variable to a discrete number of ranges, each of which is represented as a single colour in the legend. I propose clicking this should filter to that range. With the new info / title paragraph this can be effectively conveyed to the user. 

The map demes should always represent geographical filters - i.e. even if they are coloured by some other variable (e.g. date), clicking on a country should filter to that country.

**Comment by jameshadfield** [comment]
Moved to #264
