### ISSUE TITLE
tree legend click triggers filter

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#267]

**Comment by jameshadfield** [comment]
look into a "Filters Enable" bar to appear at the top (above map & tree)

**Comment by trvrb** [comment]
I thought about this for a little while and I was concerned about whether this is realistic across all legend items. It should only be implemented, if it can be implemented for everything. Easy to include for things we already have filters for, like country, but unclear how we'd approach something like LBI.

**Comment by jameshadfield** [comment]
behavior should be consistent with #266

**Comment by trvrb** [comment]
I'm in favor or tabling this for the moment. If our filters can't express this, then I don't think it works.

**Comment by jameshadfield** [comment]
agreed
