### ISSUE TITLE
Intelligently choose a centroid to minimize over dateline transmissions given latlong box

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#269]

**Comment by trvrb** [comment]
@colinmegill ---

I've just spent a couple hours with `Leaflet.Geodesic` plugin. I'm fairly convinced now that this will not be a simple fix. My suggestion is to shelve this. There is a bigger reason why however. If you look at a zoomed map near the South American equator for Zika, you'll see all the lines are nearly straight. This should be resolved per #279. We should go to Bezier curves or the like. In doing so, we can address this current issue. What do you think?

**Comment by trvrb** [comment]
This is (indirectly) resolved by #330. Being able to pan left or right fixes this.

**Comment by trvrb** [comment]
Closed by #330.
