### ISSUE TITLE
Local branching index

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#272]
a la nextflu

**Comment by trvrb** [comment]
Fastest way to get this working (and I think makes sense) is to do this in augur and pass in an attr. Won't interact with date slider, but no other coloring updates on date change. So I think reasonable to fix this as well. In which case, better to do in augur.

**Comment by jameshadfield** [comment]
Closed in bfe964a69f5188e326606e6a7eb05ddb1a171ca4
