### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#273]

**Comment by jameshadfield** [comment]
try muller plots over line graph

**Comment by sidneymbell** [comment]
### Purpose
The timeline panel will deviate from the augur "frequencies" output and does not rely on augur output. Thus far, auspice has been aimed at transparently visualizing a dataset. The goal of the timeline panel is to allow the user to visualize how the variable of interest (selected with `colorBy`) has changed over time within whatever subset of the data they have selected (via `filters`).

### Implementation
We discussed doing this in two ways: raw counts and proportions. 

Raw counts will be displayed as stacked bars. Proportions will be displayed as stacked area plots (see below). 

Counts will be calculated simply by tallying visible `nodes` in each `colorby` bin. 

There is still some discussion regarding what to use as the denominator for proportions when the user has used filters to select a subset of the data. 
Two options are: 
1) Denominator is total dataset, with the area proportional to the filtered-out data shown in gray.
2) Denominator is the selected subset of the data.

### Visualization 
I'll make up actual sketches tomorrow, but for now, we were thinking of starting with these D3 blocks for:  
[Stacked bars for counts](https://bl.ocks.org/mbostock/1134768)  
[Stacked area for proportions](https://bl.ocks.org/mbostock/3885211)   

### Future Expansions  
Eventually, adding named clades (like currently in nextflu, e.g. `3c.2a`) as a `colorBy` option would enable visualization of clade expansion through time.  
 
I am a little concerned about making it clear to users that these values represent __this dataset__, and not necessarily __all of dengue__, etc. Trevor and I had discussed possibly:

1) Moving the "dataset descriptions" to the bottom of each virus's page.
2) Making a small, unobtrusive static visualization  at the bottom that puts into perspective for each virus the total estimated prevalence (if known from other sources), the number of sequences available in the last X years, and the number of sequences in this particular dataset. This has the added benefit of highlighting how crucial it is to support pathogen genomics for public health.

@trvrb @jameshadfield - Here's the specs you requested. Let me know what your thoughts are. 
@colinmegill - Let me know if I've left anything out or if you had other ideas.  
I'll get started on this in earnest tomorrow.  Thanks, all.

**Comment by jameshadfield** [comment]
Looks great @sidneymbell 

regarding the filtering - I think option 2 is the best (by far)
> Denominator is the selected subset of the data.
Tree traversal should be pretty quick so I think this should work well. This is what i'll make the entropy panel reflect (it's kinda static at the moment)

I think clade frequencies (aka branch frequencies aka tree frequencies) is a separate panel with separate aims / problems...

**Comment by trvrb** [comment]
@sidneymbell --- Thank you. This is extremely clear. I fully agree with the direction. I echo @jameshadfield in preferring 
>Denominator is the selected subset of the data.
I also generally (outside of timeline) like the idea of an auto-generated paragraph that puts the particular dataset into context.

**Comment by jameshadfield** [comment]
@colinmegill @sidneymbell would you like this issue to stay open?

**Comment by colinmegill** [comment]
I leave it to you guys!

**Comment by trvrb** [comment]
I believe that `tip-frequencies.json` and the `Frequencies` component fulfilled exactly these requirements. The current frequencies panel fulfills:

>The goal of the timeline panel is to allow the user to visualize how the variable of interest (selected with colorBy) has changed over time within whatever subset of the data they have selected (via filters).

I would be in favor of closing.
