### ISSUE TITLE
Loading App is glitchy

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#276]
- [x] legend flashes
- [ ] sidebar flashes
- [ ] things don't have a proper initial size and snap back and forth
- [ ] there are no spinners

**Comment by jameshadfield** [comment]
i'll do the legend flashing stuff

**Comment by jameshadfield** [comment]
related to #298

**Comment by jameshadfield** [comment]
I believe this is all fixed in #463 - @colinmegill can you confirm and close if so.

**Comment by jameshadfield** [comment]
I think this issue is done.
