### ISSUE TITLE
Animation v1 

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#290]
- [x] setInterval 100ms for ebola, fire redux date change that pushes date change by 2 months 
- [ ] Play button → pause button
- [x] Draw transmissions with bezier and ditch great circle
- [ ] http://bl.ocks.org/duopixel/4063326? This, but stopping at arbitrary points via declarative state. Maybe draw to the ‘nearest marker’ and then smoothly interpolating between them when animating.
- [ ] Map options - sensible defaults of 100ms setInterval tick (maybe depending on number of nodes in tree for minimum ms) - and allow people to change them if they want a faster or slower animation - or presets for “animation speed” “slow” “fast”.

**Comment by trvrb** [comment]
Closed by #330.
