### ISSUE TITLE
Grid is not updating properly when changing dataset

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#295]
On current `master` (05038e75694aedb35efc61b399a7871e5613f05f) there is a bug when changing between datasets. Loading the app and toggling between Ebola and Zika will result in the tree changing, but the grid remaining the same as the previous dataset. Mousing over anything (causing a rerender) updates the grid to what it should be.

**Comment by jameshadfield** [comment]
@sidneymbell could you please check branch `fix-295` to confirm that this is fixed?

**Comment by sidneymbell** [comment]
Thanks @jameshadfield - this is working for me! :)
