### ISSUE TITLE
export tree svg and newick/nexus

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#296]
It would be nice to be able to export the tree for example as newick or nexus prepared by augur, or as svg with the current coloring. A derivative of the old auspice did this as 
```
	function exportTreeSVG(){
		var tmp = document.getElementById("treeplot-container");
		var svg_tmp = tmp.getElementsByTagName("svg")[0];
		// Extract the data as SVG text string
		var svg_xml = (new XMLSerializer).serializeToString(svg_tmp);
		var blob = new Blob([svg_xml.replace("cursor: pointer;", "")], {type: "text/plain;charset=utf-8"});
		saveAs(blob,'tree.svg');
	}
	d3.select("#svgexport")
		.on("click", exportTreeSVG);
```
this worked pretty well but for fonts

**Comment by trvrb** [comment]
For an Application Note this would be useful.

**Comment by jameshadfield** [comment]
There is a concern that this will facilitate people using nextstrain trees (often with unpublished data) in papers. Thoughts?

**Comment by rneher** [comment]
I think the functionality should be there. We would like ppl to use nextstrain results if they are ok to be shared and reused. In other cases, we will have to restrict the information that is available. But nwk really is no worse than json. Could strip mutations if that is a concern. I don't think an svg would be problematic.

**Comment by jameshadfield** [comment]
related to this: this script https://github.com/nextstrain/augur/blob/json_import/scripts/json_tree_to_nexus.py in augur turns auspice tree JSON to nexus, with options to resolve polytomies and to measure branch lengths in time

**Comment by jameshadfield** [comment]
What are people's thoughts on the following modal design, triggered when clicking on a `download` button:
![image](https://user-images.githubusercontent.com/8350992/29097099-eccdcd70-7c4c-11e7-8ea8-b4aaa300d89e.png)

* Models detailed would be dependent on the current view - treetime / titers etc
* Wording could be dataset specific, depending on the source of the data

**Comment by jameshadfield** [comment]
The prototype for this is working* on branch `296-download-modal`. @trvrb @colinmegill please commit (or comment on) aesthetic / language / design changes to the modal. I'll start working on the code for SVG / newick / CSV output soon.
 
![image](https://user-images.githubusercontent.com/8350992/29197288-2e23f26a-7def-11e7-9308-dde949f72b41.png)

* augur files may need updating, so some text may be missing.

**Comment by colinmegill** [comment]
Paragraph should have a max width (say 600), other than that it looks great!
