### ISSUE TITLE
entropy gene annotation

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#299]
Overlapping genes are an issue. Our only example is "sGP" vs "GP" in Ebola. Will be worse with overlapping reading frames.

**Comment by jameshadfield** [comment]
This would be advantageous to have for SARS-CoV-2 where there are already overlapping ORFs in nextstrain.org/ncov/global and the situation is even more complex than this, e.g. see Figure 1 from [Nelson et al., eLife (2020)](https://elifesciences.org/articles/59633#fig1). 

Here is how we are currently displaying SARS-CoV-2:

![image](https://user-images.githubusercontent.com/8350992/105936820-3d624a00-60b9-11eb-9319-1c8d92466b70.png)

Here is a proposed version which gives us a number of improvements without making any drastic changes. This is an area where we must strike a balance between simplicity and covering all the the weird and wonderful ways in which genomes are translated such as ribosomal frameshifting, transcriptional slippage, splicing etc. We also wish to label the upper axis using codon numbering were possible (#1032).

![image](https://user-images.githubusercontent.com/8350992/105937480-823ab080-60ba-11eb-9639-7e703f4a1145.png)

**Comment by emmahodcroft** [comment]
This would be great James!
