### ISSUE TITLE
∆colorBy should ∆geoResolution where possible

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#305]
note that the reverse _must not_ be true

**Comment by trvrb** [comment]
I don't follow / remember this. Could you clarify @jameshadfield?

**Comment by jameshadfield** [comment]
My proposal / question was: if (e.g.) `geoAttribute=region` and the colorBy is changed to `country`, should `geoAttribute` also change to `country`?

**Comment by jameshadfield** [comment]
The status quo seems to be ok.
