### ISSUE TITLE
display notifications / warnings / errors

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#306]
I'd like to implement a system similar to https://github.com/atom/notifications

Namely, a `notifications` component and reducer plus some actions

thoughts?

**Comment by jameshadfield** [comment]
current progress on branch `notifications`

![notification](https://cloud.githubusercontent.com/assets/8350992/25644491/659add90-2f5b-11e7-8066-49c4434f679d.gif)

**Comment by jameshadfield** [comment]
to do:
- [ ] persist "error" notifications

**Comment by jameshadfield** [comment]
See branch `notifications`

**Comment by trvrb** [comment]
@jameshadfield: I see the `awaiting_merge` flag. Are you suggesting that `notifications` be PRed? Or that you're waiting on a different branch to be merged before you can proceed here?

**Comment by trvrb** [comment]
@jameshadfield: Can you PR `notifications`? Seems to be the proper way to request feedback.

**Comment by jameshadfield** [comment]
now merged
