### ISSUE TITLE
Make branches properly visible when filtering date

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#311]
Currently a narrow date range will not filter branches properly. If a date range is 2014.4 to 2014.6 and a branch is 2014.0 to 2015.0 we still want to draw the branch.

**Comment by jameshadfield** [comment]
even if no descendent tips are visibile?

**Comment by trvrb** [comment]
Even if no descendent tips are visible.

**Comment by trvrb** [comment]
This was mostly resolved in #330. However, now a branch tip shows it's tip when it shouldn't.

![tip-visible](https://user-images.githubusercontent.com/1176109/27973855-5fb51c0e-6310-11e7-9952-0da0085e7d66.png)

I'll fix this small issue. Larger issue remains that we draw the whole length of the branch when the semantically appropriate thing is to just draw a subsection of the branch corresponding to the time slice. This is difficult and can for later.

**Comment by jameshadfield** [comment]
I think this may be hard - the terminal branch and the tip are the same node object, which is currently visible or it's not.

**Comment by trvrb** [comment]
@jameshadfield: Ah. I see. Thanks for the heads up. I'm going to close this in this case. The original issue has been resolved and figuring out how to do draw subsections is a separate thing.
