### ISSUE TITLE
date parsing warning

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#317]
Occurs on Dengue datasets. Error:

> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

**Comment by trvrb** [comment]
I'm not able to reproduce. Was this just from navigating to `dengue/` or did it require something else to trigger?

**Comment by jameshadfield** [comment]
seems to have solved itself 🎉
