### ISSUE TITLE
Date range no longer updating from URL

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#320]
On current `master` the date slider and the redux date range is no longer properly loading from the URL. Go here to see the behavior:

http://www.nextstrain.org/zika?dmax=2015-06-21&dmin=2015-02-25

Date range should be subsetted, but it is not.

**Comment by jameshadfield** [comment]
comment out https://github.com/nextstrain/auspice/blob/master/src/actions/loadData.js#L77 and https://github.com/nextstrain/auspice/blob/master/src/reducers/controls.js#L128 (and L129) and the old behavior is restored

**Comment by jameshadfield** [comment]
@colinmegill I wonder if we should look into async await (or similar) - it would definitely make race conditions like easier to handle...

**Comment by colinmegill** [comment]
Regardless of whether async / await is used, the underlying infrastructure
will be this:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
which
is a safe bet to go ahead and use.

**Comment by colinmegill** [comment]
Here's the polyfill: https://github.com/stefanpenner/es6-promise
And the compat table: https://caniuse.com/#search=promise

**Comment by colinmegill** [comment]
Here's an example from the creator of Redux:
https://github.com/reactjs/redux/issues/723

**Comment by trvrb** [comment]
Sounds like this is more complicated than I initially imagined.

**Comment by jameshadfield** [comment]
Thanks @colinmegill - From the docs:
> The Promise.all() method returns a single Promise that resolves when all of the promises in the iterable argument have resolved, or rejects with the reason of the first promise that rejects.
But we want to allow some `404`s (e.g. zika doesn't have `frequencies.json`). This kind of functionality isn't even in ES6 AFAIK. Seems like `Q.allSettled(promises)` from https://github.com/kriskowal/q is what we're after.

Or maybe we can do `promise.all` on the meta + tree, and allow sequences, frequencies, entropy etc to load similarly to now... i'll try this approach today.
