### ISSUE TITLE
genotype text input box bugs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#328]
* only seems to allow numeric input (despite "NS1_348" being a valid input)
* cannot delete first character
* should be debounced to allow entering of "1234" without changing the coloring to "1", "12", "123"

**Comment by rneher** [comment]
Trevor explicitly wanted the "1", "12", "123" back when we implemented nextflu. I think we settled for a 200ms delay. The rest of this is very weird.

**Comment by jameshadfield** [comment]
Proposal (after talking to @trvrb):
When `colorBy` -> `genotype` is selected in the dropdown, a second dropdown appears below with a list of genes and "nucleotide position", with a integer-only text box to the right of that.

**Comment by rneher** [comment]
I like that idea. would you also want to trigger this after clicking on the entropy panel?

**Comment by jameshadfield** [comment]
I think so, yes (and it would be filled in)
