### ISSUE TITLE
transmissions without colorBy

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#333]
For traits where the internal nodes have an undefined color by (e.g. `colorBy="country"`, for seasonal flu we have chosen not to infer ancestral country states) these show up as grey transmission lines. If I understand how `map` works, for the screenshot, for all the `region` transmissions (these exist, and the geo resolution is region) the country `colorBy` (which is all grey for internal nodes) is being averaged - is this right?

![image](https://user-images.githubusercontent.com/8350992/27304634-8bd7ce56-54f3-11e7-8528-baf8093fcc2a.png)

Would the best solution be to drop transmission lines in this case? 
This would mean we could reinstate `country` as a `geoResolution` which would always show only demes (since there will be no `country` transmissions in the tree). I think this would be valuable.
cc @sidneymbell @trvrb @colinmegill @rneher

**Comment by rneher** [comment]
I would prefer not to show the transmissions for flu. I don't think that we have any concrete evidence for the majority of the transmission events and explicitly drawing generates a false impression of confidence.

**Comment by jameshadfield** [comment]
@rneher remove the transmissions for region as well?
I still think we should show demes - otherwise the map should be removed completely!

**Comment by rneher** [comment]
its probably a little less bad for regions, but I'd rather have only demes (which report data) than a hairball of unreliable transmissions.

**Comment by jameshadfield** [comment]
demes only on branch `map-with-no-tranmissions` - only works with the seasonal flu datasets (these are on S3) with `geoResolution`->`country`
![image](https://user-images.githubusercontent.com/8350992/27305469-9a93bf9c-54f6-11e7-9b73-95888988698a.png)

**Comment by trvrb** [comment]
I think in general principal having some attrs that color tips only and then don't have an ancestral reconstruction is great. I agree these should have gray branches in the tree and show no transmission lines on the map. For seasonal flu I would do country as tip only, but still keep the region transmission inference / coloring. This looked like it was working fairly well on the test data.

**Comment by colinmegill** [comment]
To respond to James' original message, the colors are no longer averaged on transmissions (they are on demes) as we treat each transmission individually now for the animation.

**Comment by jameshadfield** [comment]
OK. In an effort to get seasonal flu working today I'm going to use the demes only code (the second screenshot) for situations where the geoResolution has no associated transmissions. 

Once the map animation branch is merged I will remove the transmissions that appear in the first screenshot.

**Comment by sidneymbell** [comment]
Nice work, @jameshadfield. 

I'd love to implement this idea:
>I think in general principal having some attrs that color tips only and then don't have an ancestral reconstruction is great. I agree these should have gray branches in the tree and show no transmission lines on the map.
for dengue as well eventually. 

>I don't think that we have any concrete evidence for the majority of the transmission events and explicitly drawing generates a false impression of confidence.
is the reason I don't currently have country `colorBy` or `geoInference` for dengue.

**Comment by trvrb** [comment]
Indeed, I think the map animation branch significantly decreases hairball appearance. Compare live:

![live](https://user-images.githubusercontent.com/1176109/27458632-ed6c0eb2-575e-11e7-878d-c4aa66ca33d4.png)

to animation:

![animation](https://user-images.githubusercontent.com/1176109/27458635-f29fc8f6-575e-11e7-95f1-562473c70034.png)

**Comment by jameshadfield** [comment]
Yeah it looks amazing :) 
I imagine the stacking will make it appear slightly more complex.

**Comment by trvrb** [comment]
I think this is now resolved. @jameshadfield feel free to reopen if you think differently.
