### ISSUE TITLE
Region filter should be split

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#336]
Currently region filter combines "regions" and "countries":

![region_filter](https://user-images.githubusercontent.com/1176109/27400854-549b551e-5676-11e7-8e4e-527280de2798.png)

This should be fixed to be separate filters. For Zika, this should be one titled "region" and the other titled "country". 

Somehow Ebola's "geographic location" filter is just showing countries:

![ebola_geo_filter](https://user-images.githubusercontent.com/1176109/27400935-9efb65d6-5676-11e7-9b05-db0f15b4fd0f.png)

This should be fixed to be separate filters titled "country" and "division" to match available attrs.

**Comment by jameshadfield** [comment]
closed in d984c93d8206b8295033295847c24d4580aa066d
