### ISSUE TITLE
Switching tree layouts triggers confidences

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#337]
On live site if I go to Zika:

http://www.nextstrain.org/zika

then click "Radial" then click "Rectangular", I get confidence intervals on all nodes despite "Show confidence intervals" being toggled off.

**Comment by jameshadfield** [comment]
Here's the _why_:
confidences is a redux state, and working as expected, but `PhyloTree` doesn't see that and so draws confidences at every opportunity (i.e. when the rectangular layout is selected).

I'm not 100% sure how to go about this - i've got 2 ideas: (A) make a flag in `PhyloTree` and try to keep it in sync with the redux state? Or (B) make every relevant call to PhyloTree pass in the `redux.confidenceOn` state?

@colinmegill @rneher @trvrb thoughts appreciated

**Comment by trvrb** [comment]
I'm not sure I follow. Shouldn't this use the same pattern as we have for layout vs distance metric? We have `this.props.layout` and `this.props.distanceMeasure` in redux, but there's no problem for `PhyloTree` to remember what state to draw. Ie. can click radial, then change to divergence and then click rectangular and we get a rectangular tree with divergence.

**Comment by jameshadfield** [comment]
Yes - that's option (A) - namely `phyloTree` sets `this.distance` and this is kept in sync with redux. If @colinmegill agrees i'll implement something similar for confidences.

**Comment by trvrb** [comment]
Tagging @colinmegill here.

**Comment by jameshadfield** [comment]
ok i'm going to go ahead and implement option A (above)
