### ISSUE TITLE
Coloring of AA states from entropy plot is buggy

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#340]
To reproduce go to:

http://www.nextstrain.org/flu/h3n2/ha/3y?c=region&r=country

This will color the flu tree by region. Next click on column corresponding to HA1 site 159 in the entropy plot. This should recolor according to `gt-HA1_159`. However, only the tips get recolored. Branches stick with the original region coloring, like so:

![coloring](https://user-images.githubusercontent.com/1176109/27503766-7b18ec78-5834-11e7-844a-31cbbc2bfe4d.png)

Additionally, trying to load this directly doesn't work as well:

http://www.nextstrain.org/flu/h3n2/ha/3y?c=gt-HA1_159&r=country

Shows region colors.

I'm getting the same buggy behavior with Zika.

@jameshadfield Do you have an obvious idea here?

**Comment by jameshadfield** [comment]
Nothing obvious - I thought I'd removed the URL genotype bit, but clearly not.

I'll look into this next week.

**Comment by jameshadfield** [comment]
Hovering over the nodes restores them to the correct colour - so I think the redux state is correct but phloTree isn't displaying it correctly.
