### ISSUE TITLE
Tree doesn't always fill panel

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#341]
Occasionally I get situations best explained in the screenshot:

![image](https://user-images.githubusercontent.com/8350992/27562457-84739e22-5a81-11e7-8b76-15bb01bbce5f.png)

The SVG dimensions are being correctly set and interpreted both by `treeView`->`computeResponsive()` and `phyoTree`->`mapToScreen`->`setScales`. 

My guess is that it's a `ReactSVGPanZoom` problem, but I have no experience with this library. @colinmegill have you seen situations similar to this?

**Comment by rneher** [comment]
I just ran into this as well. It happens to me if you zoom by `ctrl-+` and subsequently do `return to entire tree`. My guess is that this has to do with resetting SVG dimension after window zoom.

**Comment by jameshadfield** [comment]
Haven't seen this bug since I implemented `phylotree.change()` - will reopen if it appears again
