### ISSUE TITLE
color goes black when switching AA<->NT

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#347]
when you color by genotype (via click on diversity panel) and then change NT <-> AA (or vice versa), everything goes black. IMO color shouldn't update in this case, and it doesn't if color is region or similar.

**Comment by jameshadfield** [comment]
Interesting - what dataset is this on @rneher ?
On nextstrain.org/zika it's reverting to `country` coloring when I follow those steps (I'm not sure why it's doing that, but it looks ok!)

![347](https://user-images.githubusercontent.com/8350992/27692138-cd1dc240-5c9a-11e7-8809-0481c221de23.gif)

**Comment by jameshadfield** [comment]
(this may have been fixed overnight with the merge and release of https://github.com/nextstrain/auspice/pull/342)

**Comment by jameshadfield** [comment]
just found this bug on `flu` - will look at it today

**Comment by rneher** [comment]
zika works for me as well. as you wrote, its flu.
