### ISSUE TITLE
Map state on animation conclude

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#350]
From James:

- [x] (on the non-cumulative mode) at the end of the animation the date slider should return to the full date range and the button should change back to Play. It currently shows a small slice at the end so nothing is visible, and the button shows Pause.

cc @trvrb

**Comment by jameshadfield** [comment]
For what it's worth I think this issue is essential for PR #330 
(context: issue #351 raises the possibility that non-essential parts of PR #330 are being moved to issues)

**Comment by colinmegill** [comment]
Yup! We should figure it out before we merge. Broke out so we could discuss
