### ISSUE TITLE
Display author and title when filtering by author

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#354]
It would be good to provide a method for individuals to share their own datasets and give prominent credit to contributors. I feel like this is currently overly hidden. My suggestion is when filtering by author, just show author and title at the top. Something like:

![faria](https://user-images.githubusercontent.com/1176109/27878364-da017510-6172-11e7-86da-05fd63a8766e.png)

when filtering to "Faria et al". Additionally, we need to fix the URL handling of filters, as this is only really useful if a URL to this view can be shared. This should look something like: http://www.nextstrain.org/zika?f:authors=Faria%20et%20al. This might be able to be streamlined further.

**Comment by jameshadfield** [comment]
:+1:
I can make the title bar prototype today. 

* I agree the author's should be in the URL but really don't like the long format - we'll get ridiculous stuff like `X%20et%al&Y%20et%al&Z%20et%al...` I'll try and think of a smarter way of doing things.
* What should the header look like if 2 authors are selected? what about 3, 4...?

**Comment by trvrb** [comment]
Excellent. Thank you James.

* I agree that figuring out a system for URL filters would be excellent. A simple fix would be to keep the snake case we're using internally: http://www.nextstrain.org/zika?f:authors=faria_et_al&black_et_al. Alternatively, we could drop the "et al". This would make parsing author filter a special case compared to parsing geo filter and the like. There might be a cleverer way to do this however.
* Alternates are either "Faria et al. Establishment and cryptic transmission of Zika virus in Brazil and the Americas and Black et al. Genetic characterization of the Zika virus epidemic in the US Virgin Islands" for the above Faria + Black author filter. Or just don't display a title when we have 2 or authors filtered to. I don't know which is best.

**Comment by jameshadfield** [comment]
current status:
![image](https://user-images.githubusercontent.com/8350992/30232511-4a516856-94a5-11e7-8d79-c448c8454572.png)

we require augur rebuilds of other datasets in order to have the appropriate information to display this (only zika has this so far I believe).

**Comment by jameshadfield** [comment]
This issue is currently "on hold" while we sort out fauna / augur URL / citation updates for flu / mumps etc
