### ISSUE TITLE
panel display via (augur defined) attributes

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#356]
(re-)implement augur control over the display of panels, via a `meta.json` attribute named `panels`. This will allow custom control over which panels are displayed.

On the auspice side, JSON loading will be:
* (synchronously) fetch meta, tree & sequences
* as the `panels` attribute dictates, load additional JSONs

Depends on: `simplify` branch merged.
Things depending on this: Frequencies & Timeline
Timeframe: around a month (I'll be in england for a while)

**Comment by trvrb** [comment]
This is currently being exported by augur, for example: http://data.nextstrain.org/zika_meta.json with 

```
panels: [ "tree", "map", "entropy" ],
```
