### ISSUE TITLE
Frequencies

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#357]
Here is the specification of the frequencies streamgraph. I think this would be a great feature to work collaboratively on. Please edit this post as required - perhaps ~strikethrough~ previous ideas instead of removing them?

![img_2985](https://user-images.githubusercontent.com/8350992/27932643-59f3f69a-6253-11e7-9124-8a32205c8776.JPG)

* data computed in augur (already done)
* streamgraph shape is "fixed", i.e. does not change with filters / time slicing
* colouring of each stream is the inferred ancestral state
  * unclear how this works with uncertainty
  * if ancestral states are not computed, display grey
* opacity of each stream is related to the number of tips visible (similar to branch thickness)
* internal nodes which are not visible (outside time slice) are either grey or mostly transparent.
* tip colours not used
* branch hover enhances the stream, similar to how a branch is highlighted
  * this will involve moving branch hover state to redux I imagine
* lines demarcating streams are always displayed

**Comment by rneher** [comment]
The above proposal works for nested/exclusive frequencies such clades or all variants at a specific position. If such nesting/exclusiveness is not guaranteed, a more traditional line graph would be more straight-forward and easier. Why not implement both? Some of the underlying machinery will be the same and it is maybe easier to get started on the line graphs.

**Comment by jameshadfield** [comment]
Closed in #497
