### ISSUE TITLE
check map conditionals regarding tree ready status

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#361]
depends on: merge of #349

**Comment by trvrb** [comment]
This is especially relevant for a particular bug:

1. Go to http://localhost:4000/ebola
2. Change dataset to "Avian"

Voila:

![ebola_avian](https://user-images.githubusercontent.com/1176109/27973393-c20bd7dc-630e-11e7-9769-054e29f9ebf8.png)

Also, my current code for checking bad: https://github.com/nextstrain/auspice/blob/master/src/components/map/map.js#L272. There should be a cleaner way to do this.

cc'ing @colinmegill for his input as necessary.
