### ISSUE TITLE
Ebola date range

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#364]
Ebola has absolute date range of 2014/03/04 to today. This makes it so half the date slider is non-active. Should fix to have absolute max date equal to the final sample. I don't know how much of this is augur vs how much is auspice.

This impacts animation in that a bunch of animation happens with a blank display.

**Comment by jameshadfield** [comment]
auspice currently assigns the minimum dates to the root node https://github.com/nextstrain/auspice/blob/master/src/reducers/controls.js#L64

similarly, one could traverse the tree to find the max date

**Comment by trvrb** [comment]
I think this seems like a good default. For things like flu that have data coming in fast enough we'll default to a date close to the present. For Ebola, we'll default to the relevant end of the epidemic.
