### ISSUE TITLE
changing datasets map issue

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#365]
Load http://localhost:4000/avian/h7n9/ha?c=country&r=country (current `master`)

Use the dropdown to change to flu.

This results:
![image](https://user-images.githubusercontent.com/8350992/27973526-2914cb3c-630f-11e7-9ab6-959aee65043e.png)

(refreshing the page fixes things)

**Comment by jameshadfield** [comment]
`simplify` has fixed this. Will close when #349 merges.

**Comment by trvrb** [comment]
Particular combinations seem to cause this, like Ebola to Avian. If see that it's also Avian to Flu. Flu to Zika has the issue. But Zika to Ebola does not.

Seems to have something to do with non-geo resolved trees (like for Avian and Flu).
