### ISSUE TITLE
cumulative map animation should be able to start at user selection

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#380]
steps to explain
* go to zika
* toggle cumulative animation on
* drag maxDate slider back to (say) half way
* begin animation

Current behavior: animation starts from beginning (i.e. maxDate jumps back to ~minDate)

Proposed behavior: animation starts from user selected time slice

Caveats: clearly if maxDate is at (or near?) the end of the available time we should start the animation from the beginning.

**Comment by colinmegill** [comment]
Interesting, I thought this worked, I suppose it doesn't in this case. If cumulative is toggled while the animation is running (with a time window, not cumulative) cumulative does pick up where it left off.

**Comment by trvrb** [comment]
Yeah. This is tricky. Thinking about this in terms of UX with least surprise...

If you do a "cumulative" animation when dateMax is all the way right, dateMax jumps left and increments from there. This makes sense. If it jumps left when the bar is full, why wouldn't it jump left when the bar is half full?

I'm not super confident here, but I lean toward preserving current behavior.

**Comment by jameshadfield** [comment]
> If it jumps left when the bar is full, why wouldn't it jump left when the bar is half full?
If someones modified the date slider, then one could make the case for a different behavior. 

Added the "revisit" label as this is currently very low priority

**Comment by jameshadfield** [comment]
Closing this as the current behavior is perfectly acceptable 👍
