### ISSUE TITLE
improve bezier speed

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#381]
Related to #367 but better served as its own issue

**Current Data Flow**

each tick calls `updateVisibility`, which has `D3` data binds to the demes and transmissions. This data bind is for all transmissions, whether visible or not (at time of writing, n=147 for zika). The bezier calculation (see below) is calculated for all transmissions, and SVG elements created (and modified at each tick) regardless of whether visible or not. The stroke-width attr effectively hides those which are not visible, but they're always calculated and SVG elements exist.

**Current Bezier calculation**

The Bernstein polynomial is calculated for each transmission, for each tick. 15 points are then calculated for the fraction of the path present in the current time slice (negative fractions are mathematically sound and are currently passed through for curves outside of the time slice). 

**Steps to make things better**

* For each transmission`A-B`, pre-calculate a single Bernstein polynomial (or `n` if there are `n` separate transmission events from `A-B` that we don't want over top of each other)
* Only run D3 data binds for visible transmissions (requires using a key to keep data binds in sync)
* Either
  * take the pre-computed polynomial and make a curve of 15 points representing the current time slice (15 shouldn't be hardcoded, but related to the length of the visible path)
  * (faster, my preferred option) pre-compute (when we make the polynomial) a curve of (say) 5-150 points (depending on length), then at each tick, slice this array of points so that it's relevant to the time window and draw this.

**Potential Increases**

Vast. E.g. current `zika` @ medium speed takes around 300 ticks (flu will take way more, so will zika as we move to animation frames)
* Bernstein polynomial: 45000 calculations can be reduced to 150.
* Curve interpolation: 45000 calculations can be reduced to 150 precomputed arrays, with (computationally cheap) array slices at each tick
* SVG elements: number in the DOM will be number visible, not all 150
* SVG updates only on visible elements, not all 150

**Comment by jameshadfield** [comment]
cc @colinmegill @trvrb

**Comment by colinmegill** [comment]
Fully support, though no opinion on which direction. Seems like this will be a dramatic speedup for the bezier side.

**Comment by jameshadfield** [comment]
I'm strongly voting for precomputing the curves array and taking slices during each tick. We have to optimise a lot in order to get map animation ticks fast enough and this is an easy gain.

**Comment by trvrb** [comment]
I agree about precomputing curves and slicing.

Generally, I think it might make sense to have a `transmissionsData` object in `map.state` that has this informative in addition to lat/longs etc... so that this can be combined with issue #392. It's the same object list at heart.

**Comment by trvrb** [comment]
@colinmegill: With PR #392 merged, this should be a lot easier. You can attach a `bezier` attribute to `transmissionData` that gets pre-computed along with everything else.

**Comment by colinmegill** [comment]
@trvrb bezier pre computation is accomplished https://github.com/nextstrain/auspice/pull/406, but taking correct slices on date slider is still outstanding.
