### ISSUE TITLE
Dengue is silently defaulting to divergence

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#382]
Switching to any of the dengue datasets displays `m=div` instead of `m=num_date`. This is an okay design decision. (I think it's pretty equivalent for these datasets) However, on initial load the "DIVERGENCE" button is not active. It should be blue.

**Comment by sidneymbell** [comment]
Yes, this is an intentional decision (default exported from augur)
motivated by the deeper phylogeny of the 'all' dataset. I can look into the
display issue on Thursday.

**Comment by trvrb** [comment]
Great. Thanks.
