### ISSUE TITLE
why does maybeDemesAndTransmissions run multiple times during an animation tick

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#391]
console logs (https://github.com/nextstrain/auspice/pull/389#issue-242077111) indicates it runs once, and that a single action is dispatched during each tick, however the profiling (see https://github.com/nextstrain/auspice/issues/367#issuecomment-314493473) indicates it runs up to 7 times each tick.

It appears that on ebola it only runs once.

**Comment by trvrb** [comment]
My recent testing here (https://github.com/nextstrain/auspice/issues/367#issuecomment-322014207) has indicated that map code is now only running once each animation tick. I believe this issue is resolved, though feel free to reopen if you believe it not to be fixed.
