### ISSUE TITLE
Standard format for JSON filenames?

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#4]
The nextstrain app route to dataset pipeline will look like this:

`nextstrain.org/:virus/:strain/:timeperiod`, thus: `nextstrain.org/flu/h3n2/3y`

How we map this to a REST route on the server, and then to string names on s3 is an open question

**Comment by trvrb** [comment]
Good question. The current practice for S3 is obviously:

```
/data/h3n2_3y_tree.json
/data/h3n2_3y_sequences.json
/data/zika_tree.json
```

The issue is, some viruses (like Ebola and Zika) have only one "resolution" (timeperiod) and only one lineage (strain).

What about just doing the exact same structure for S3? So

```
/data/flu/h3n2/3y/tree.json
/data/flu/h3n2/3y/sequences.json
/data/zika/tree.json
```

**Comment by colinmegill** [comment]
That's ideal, if it's not too inconvienient, as we can construct the request on the client

**Comment by trvrb** [comment]
Seems entirely reasonable. Shouldn't be an issue with the builds.
