### ISSUE TITLE
Remove minTransmissionDate from map logic

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#403]
Currently, we calculate and store `minTransmissionDate` this eventually gets passed to [`extractLineSegmentForAnimationEffect`](https://github.com/nextstrain/auspice/blob/master/src/util/mapHelpers.js#L210)
and then to  [`computeMidpoint`](https://github.com/nextstrain/auspice/blob/master/src/util/mapHelpers.js#L53). Where it's called as `modify`. However, `modify` is commented out. `minTransmissionDate` is currently doing nothing in the codebase. I'll plan to strip this out unless @colinmegill can tell me a good reason why it exists. I'm assuming it was there to do give the shallower vs wider arcs like Gytis used in his solution. However, our planned banding together of multiple arcs won't use this logic.

**Comment by jameshadfield** [comment]
closed in f578936e6f60152017b1bfebffe6df396645e764
