### ISSUE TITLE
Improve animation timing

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#404]
Currently, with calls to `setInterval`, map animation will lag if the interval is requested for (say) 50ms and each frame takes 100ms. In this case, the animation will take 60 seconds to complete rather than 30. @colinmegill and I discussed doing `requestAnimationFrame` instead where we know exactly what time to set the date slider for at any moment. This would give an animation that always completes in 30 seconds (or whatever) but uses as many frames in that time as possible. This should also benefit Zika and sparser datasets where we could then have higher FPS than current `globals.animationTick` specifies.

**Comment by jameshadfield** [comment]
Can we close this since this is live and RAF has been abandoned?

**Comment by trvrb** [comment]
Note that `map-raf` "solves" this issue. However, in so doing we discussed that `setInterval` was actually the right solution. Pulling frames as fast as possible results in frequent judder if computer is slow or if performing other tasks. Will keep `map-raf` branch around for posterity for the next while.
