### ISSUE TITLE
drag & drop CSV colorBy information

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#421]
This is a feature proposal to allow (client side) addition of `colorBy` data to a dataset by means of dragging and dropping a CSV file with a column of `strain` (matching the taxa in the tree) and additional columns processed as `colorBy` variables. Ancestral state reconstruction is not performed. 

This feature would work well with the ability to download line lists. It is a mechanism by which "private" data can be added to public analyses.

**Comment by jameshadfield** [comment]
Branch `421-drag-csv` has a working prototype of this functionality (commit ed9d305c5e48cc42bc58b51db46ddcb1d1439f9a)

**Comment by jameshadfield** [comment]
This is now working for CSV files - if it is satisfactory I plan to merge into `296-download-modal` as they are tandem features. 
@huddlej would you mind testing this?

**Comment by jameshadfield** [comment]
This feature is working has been merged into branch `296-download-modal`. Will become part of that PR.

**Comment by trvrb** [comment]
Excellent. Thanks James. This is a great direction. Could you provide a working tsv to test this on Zika? Didn't know the best way to go about this.
