### ISSUE TITLE
Add meta options to metadata.json

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#43]
- [ ] Colors
- [ ] Authors

Only show epitope for flu, for instance

(controls, ie., what things you can click on, what options there are to click on)

**Comment by trvrb** [comment]
Zika, Flu and Ebola each need a list of colors associated with geo entities. Currently have

```
 "geo": {
  "country": {
   "american_samoa": {
    "latitude": -14.27806, 
    "longitude": -170.7025
   }, 
```

for countries and regions. Suggest adding `color` to this data structure.

**Comment by rneher** [comment]
makes sense. not only geo, but any color options

**Comment by colinmegill** [comment]
@rneher what's the status on this one?
