### ISSUE TITLE
vaccine strain info through tree decoration

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#439]
This issue aims to display custom information (such as vaccine strains) when encoded in the `tree.json` similar to nextflu:

![image](https://user-images.githubusercontent.com/8350992/29945982-3f634764-8e58-11e7-8b6c-7c6899afbc14.png)

* I imagine the data is encoded in the node of the tree as, e.g. `decoration` (similar to `attrs`)
* Should/can tree labels use this framework as well?

**Comment by rneher** [comment]
not sure what a clear distinction between `attrs` and `decorations` would be. We already have an `attrs.serum=false/true` and that would also need to correspond to a decoration. Would be great to get the titer stuff into nextstrain though.

**Comment by jameshadfield** [comment]
Closed in 3fea6e43044ca1b091c979b84fbb01645758de93
