### ISSUE TITLE
Dengue display broken on live

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#446]
There was a bug introduced in PR #437 that fully breaks display of dengue.

http://localhost:4000/dengue/all works on commit 323511056778c18af55ef03b497edd7987096f64, while it fails on the child commit ffabb17e063f4e02a5cac400c8969857640869b2.

The issue is something to do with getting the `startsWith` attribute of `colorBy`. I can't just fix this line because `master` has had a bunch of other stuff added here that I don't fully follow:

https://github.com/nextstrain/auspice/blob/master/src/reducers/controls.js#L149

@jameshadfield --- Could you take a look at this first thing tomorrow? This is one more reason we should invest in some automated tests.

**Comment by jameshadfield** [comment]
fixed in 
https://github.com/nextstrain/auspice/commit/d7b1431f88b410590998dc51f6a472eb4a18484c
