### ISSUE TITLE
tree branch visibility is incorrect

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#473]
As it stands, any branch that is present within the selected time slice is "visible". E.g. the branch joining a tip from 2016 with a parent in 2013 will be selected if the max date is 2014.

Furthermore, as both tips & branches use the same visibility array, the 2016 tip (in the above example) is shown as visible. 

This screenshot indicates zika filtered to a max date of 2014:
![image](https://user-images.githubusercontent.com/8350992/31964052-a0232acc-b8b7-11e7-839a-a681f35bea85.png)

**Comment by trvrb** [comment]
I've been annoyed by this as well. My only thought for a solution has been to break up branches into multiple subbranches, each with 1 parent and 1 child node. However, I was worried about this for performance reasons as it would significantly increase the number of SVG objects, which has already shown to be a performance bottleneck.

Alternatively, there could be some way to change x-values for nodes dynamically based on time interval selected. This would give more of a growing tree effect than the current approach.

**Comment by jameshadfield** [comment]
You could do it with one extra SVG object (branch) and using `stroke-dasharray` or changing the `d` attribute. With the way phylotree works, this isn't easy.

**Comment by trvrb** [comment]
Yes. I'm afraid of digging too deep into Phylotree and would instead be thinking of solutions that change the "data" supplied to phylotree.

**Comment by jameshadfield** [comment]
@evogytis and I have a possible solution to this:
* On the initial rendering of a tree (or after layout changes, zoom into clade etc etc) draw the skeleton tree - the entire tree with thin branches - what's currently the "not visible" state.
* When rendering "true" branches, only render those which are visible.
* If a branch is visible, but intersects the time slice, only draw the portion of the branch which is in view (i.e. modify the x co-ordinates)

This should actually make animation, filtering etc much faster, as the skeleton tree is left unchanged and so we are rendering far fewer branches at each time point.

**Comment by jameshadfield** [comment]
Closed in #639
