### ISSUE TITLE
Truncate AA muts in Mouseover Bubble

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#484]
Currently when viewing NT mutations in the mouseover, long lists of mutations are truncated and replaced with '+953 more'. For AA muts, this currently doesn't happen. Though this probably hasn't been a problem so far, for bacterial data sets this list gets very long, so similar functionality would be very useful to ensure the whole 'bubble' is visible.

**Comment by jameshadfield** [comment]
Thanks @emmahodcroft - this should be pretty easy. I'll be able to take a look early next week.

**Comment by jameshadfield** [comment]
Hi @emmahodcroft - I think the problem was the number of genes, not the number of mutations in any one gene (I think!). Can you check this branch and see if this solves the problem?
 https://github.com/nextstrain/auspice/tree/limit-prots

**Comment by emmahodcroft** [comment]
Thanks @jameshadfield ! We're at a departmental symposium all day/evening today, but I'll test ASAP and let you know!

**Comment by emmahodcroft** [comment]
@jameshadfield Yes, this seems to be working! Thank you!
![protein-truncation-working](https://user-images.githubusercontent.com/14290674/35090322-998cb7bc-fc39-11e7-84d9-73c8517d30ab.PNG)
