### ISSUE TITLE
Path in footer.js crashes Auspice?

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#487]
The latest Auspice `master` crashes completely for me, with the error: 

> `loadMetaAndTreeJSONs error: ReferenceError: router is not defined
    at getAcknowledgments (footer.js?8b98:34)`

I think the problem is in line 34 of `footer.js`:
`if (router.history.location.pathname.includes("mumps")) {`

This seems to be a mismatch from the code either side which says
`if (window.location.pathname.includes("zika")) {`

If I change line 34 to similarly use `window.location.pathname.includes`, Aupice runs!

**Comment by jameshadfield** [comment]
thanks @emmahodcroft 👍
