### ISSUE TITLE
stop computeResponsive causing a forced reflow

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#499]
Pass in sidebar on/off as an argument rather than querying the DOM for the widths of the sidebar - see https://gist.github.com/paulirish/5d52fb081b3570c81e3a

**Comment by trvrb** [comment]
I thought I hacked a fix for this via: https://github.com/nextstrain/react-sidebar/commit/ff11a42fcc2c2e371feb4f2dbb6d05cc12280072.

**Comment by jameshadfield** [comment]
That probably helps, but it's this line: https://github.com/nextstrain/auspice/blob/master/src/util/computeResponsive.js#L44 -- the mere act of querying the DOM causes the reflow :-1:
