### ISSUE TITLE
Missing nextflu features

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#502]
## Overview

This issue is meant to document features that currently exist on nextflu.org (via https://github.com/blab/nextflu/tree/master/auspice) that should be ported into nextstrain/auspice. Fortunately, we currently use the same flu JSONs for nextflu.org and for nextstrain.org, so that the builds are the same, although nextstrain.org may need some additional info in `meta.json` to load features.

This looking at migration of nextflu.org to nextstrain.org. Migration of who.nextflu.org is a separate matter and will need attending to after migration of nextflu.org.

I've organized this into:
* Features necessary to migrate live nextflu.org to nextstrain.org
* Features that are nice to have but not required
* HI (titers) features

## Necessary

1. Strain name search. I use this all the time when interacting with nextflu. I'd think this would work like any other filter. Would be amazing to live filter tips as search string is honed in on...
2. ~Frequencies. PR #497 is a fantastic direction for this.~
3. Annotation of AA mutations to branches. This is way nicer to work with than having to mouseover everything and is critical when digging into flu trees. I would default this to off the way it is on live nextflu.
4. ~local branching index colorBy (I'm okay with this being computed in augur rather than live updated in auspice --- might even prefer)~, ~clade colorBy~

## Nice to have

5. Legend bounds need fixing to be properly rounded like they are on nextflu. The four decimal places with random cuts looks strange.
    * _EDIT_ #506 
6. Nextflu populates genotype colors in a more pleasing fashion so that majority is the pleasing blue-green and mutates are brighter colors. Nextstrain often has the reverse.
    * _EDIT_ #503
7. Fix colorBy ordering. I think this might be random at the moment (due to dictionaries not being sorted), when there should be a clear ordering, like so: https://github.com/blab/nextflu/blob/master/auspice/_data/color_options.json.
    * _EDIT_ fixed
8. Allow multiple `colorBy`s
    * _EDIT_ #509
9. keep controls state if possible - i.e. switching 3y -> 6y should maintain colorBy, tree display...
    * _EDIT_ #510

## HI titers (EDIT: will revisit)
10. Password protection
11. JSONs (HI, tree, subs) contain egg, cell, hi, fri, center information (i.e. there's 3 JSONs in total). @trvrb @rneher @huddlej to build these / design this schema.
12. HI distance, subs model, tree model
13. Titer matrix panel?

_Edited to remove LBI_

_Edited after meeting_

**Comment by jameshadfield** [comment]
Thanks @trvrb. 

#### 4 (colorBys)
* LBI is already part of live nextstrain (http://www.nextstrain.org/flu/h3n2/ha/3y?c=lbi). Happy for someone to move this code to augur if they would like.
* How are the clade colorBy attributes set in nextflu? I don't see them in `augur:master` - if we could export them as a "normal" colorBy then they would be in nextstrain too.

**Comment by trvrb** [comment]
Thanks @jameshadfield. I had (obviously) missed LBI. Nice to have it. Clade colorBy is entirely an augur export issue.

**Comment by jameshadfield** [comment]
Everything here is fixed / in separate issues. Everything except where to put the flu reports. @trvrb will discuss in person.
