### ISSUE TITLE
fix legend ordering

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#503]
fix legend ordering for genotypes to reflect when particular genotypes were first observed

#497

**Comment by trvrb** [comment]
There are a couple situations where this comes up:

With genotypes, where the ancestral state is not the first thing in the legend.

http://www.nextstrain.org/flu/h3n2/ha/3y?c=gt-HA1_135

<img width="1056" alt="freq-1" src="https://user-images.githubusercontent.com/1176109/36743250-aa1022ca-1b9e-11e8-97dc-c22ef94512ba.png">

But also with clades where unassigned is not the first entry in the legend:

http://www.nextstrain.org/flu/vic/ha/12y

<img width="1062" alt="freq-2" src="https://user-images.githubusercontent.com/1176109/36743365-fe42b222-1b9e-11e8-8d80-96efab27a918.png">

Generally, I don't think this is a huge issue, but I could imagine eventually separating colorBys into continuous, ordinal and categorical. Examples of continuous are `ep` and `num_date`. Examples of ordinal are `country` (where there's a reason two countries are placed next to each other on the color ramp). Examples of categorical are `clade_membership` and `genotype`.

I think just categorical variables would want to be reordered according to tree appearance, while continuous and ordinal should stick to their natural ordering.
