### ISSUE TITLE
Reset layout visibility bugs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#515]
![image](https://user-images.githubusercontent.com/8350992/36713103-c0882330-1b40-11e8-8845-876dd44d96c7.png)

@trvrb do you have a way to recreate this, or is it sporadic?

**Comment by trvrb** [comment]
Okay. This is a strange bug. I can reliably recreate on local when running `npm start`, going to http://localhost:4000/zika, clicking on a branch to zoom the tree and then clicking the gray "reset layout" button. If I click the blue "view entire tree" button it works fine. The weird part is that I'm not getting this behavior on Heroku dev running from the same branch.

**Comment by jameshadfield** [comment]
It's probably a race-condition bug -- the production bundle (heroku dev) is fast enough that it doesn't show up. But... I can't recreate it as described above (in dev mode).

The "view entire tree" button simply resets the tree bounds. The "reset layout" button actually nukes the entire tree and resets everything.

Will look into it tomorrow.

**Comment by jameshadfield** [comment]
Closing as the functionality of the rest layout button has been changed.
