### ISSUE TITLE
Add confidence intervals to URL state

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#522]
For an introduction to how we store (and read) redux state to a URL, I suggest exploring how we do this when a color-by or geographic resolution changes. Happy to help more if anyone takes this issue on :)

**Comment by eharkins** [comment]
Working on this in https://github.com/eharkins/auspice/tree/522-url-conf-intervals , will PR when I've had a chance to testing with nextstrain.org build.
