### ISSUE TITLE
Genotype coloring is incorrect

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#530]
Genotype coloring is incorrect. Coloring H3N2 by HA1 site 131 demonstrates the issue.

From https://nextflu.org/deprecated/h3n2/ha/2y/:

<img width="951" alt="old" src="https://user-images.githubusercontent.com/1176109/37784568-5b2c9ac0-2db5-11e8-8d8c-96fdf654625b.png">

With a single T131K mutation corresponding to clade A2.

From https://nextstrain.org/flu/h3n2/ha/2y?c=gt-HA1_131:

<img width="1190" alt="new" src="https://user-images.githubusercontent.com/1176109/37784687-9f2aea92-2db5-11e8-8ee3-cbef06f49908.png">

Branches list the correct mutations, but tooltips list things like "Amino acid at HA1 site 131: R", which is incorrect.

I've confirmed that this is also broken for Zika and Ebola. Not all genotypes are broken, but many are. It looks like the displayed colors are a superset of what it should actually be, ie branches with mutations are treated appropriately, but other branches without mutations also result in color changes. I think I see how this can result from an incorrect tree traversal (it looks like colors are propagated backwards from tips incorrectly).

**Comment by rneher** [comment]
@jameshadfield please check, but I think this fixes it
https://github.com/nextstrain/auspice/commit/5b467de3ad6dff14dd423f7ac9cc074bc0006533

**Comment by trvrb** [comment]
@rneher: This appears to fix everything. I'll merge and deploy.
