### ISSUE TITLE
Define color_options schema

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#571]
Currently, `vmin` and `vmax` are set for LBI in augur here: https://github.com/nextstrain/augur/blob/master/builds/flu/flu.process.py#L599, resulting in a `meta.json` that looks like:

```
  "lbi": {
   "vmin": 0, 
   "vmax": 0.7, 
   "legendTitle": "local branching index", 
   "key": "lbi", 
   "menuItem": "local branching index", 
   "type": "continuous"
  }, 
```

However, this actually hard coded in auspice here: https://github.com/nextstrain/auspice/blob/master/src/util/colorScale.js#L134. The auspice hard coding should be removed and values taken from `meta.json`.

I tested and you can't set `vmin` and `vmax` via `meta.json` for things that aren't LBI either.

**Comment by jameshadfield** [comment]
cc @trvrb are you happy with this proposal?

**Comment by trvrb** [comment]
* I would merge `sidebarDropdownLabel` and `legendTitle`. I just looked through the site and I couldn't find any examples where these should be different. Call this `title`.
* I need to think more about how `color_map` would be used. (I don't remember if `meta.json` uses CamelCase or snake_case, but we should be consistent).

I think this needs an in person discussion to work through all the details.

**Comment by tsibley** [comment]
If you're going to document a structure for this bit of data, can it done by writing a [JSON Schema](https://json-schema.org)?  Seems like it'd be a nice way to get the ball rolling a little bit.

**Comment by jameshadfield** [comment]
Moved to https://github.com/nextstrain/augur/pull/158
