### ISSUE TITLE
Split view broken

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#574]
Chrome, PC

![image](https://user-images.githubusercontent.com/1770265/40933569-ddf9a87e-67ff-11e8-9861-b774e4b4bfe1.png)

**Comment by trvrb** [comment]
Thanks @colinmegill. This is almost certainly an issue with the scrollbar width we're using. I turned it off Mac where they are thinner.

**Comment by colinmegill** [comment]
Hmm... I've got the same problem on Mac - do you repro there?

**Comment by trvrb** [comment]
Mac / Chrome is working fine for me. Haven't encountered this issue. Works at all window sizes and browser-zoom levels.

<img width="1323" alt="lassa" src="https://user-images.githubusercontent.com/1176109/40935732-db895ab0-67ed-11e8-8c7c-fa9bf80b7043.png">

**Comment by colinmegill** [comment]
Interesting! It looks like you do have your scrollbar turned off there, are you able to turn it back on?

**Comment by jameshadfield** [comment]
This still happens periodically on different browsers / OSs.

**Comment by colinmegill** [comment]
Same

**Comment by rneher** [comment]
* ubuntu 16.04/firefox: ok
 * ubuntu 16.04/chrome/chromium: broken
 * andoid/duckduckgo: ok

**Comment by emmahodcroft** [comment]
Windows 10 Pro:
- Firefox, Chrome, IE, Edge - all broken

**Comment by jameshadfield** [comment]
@rneher / @emmahodcroft could you change this line https://github.com/nextstrain/auspice/blob/master/src/util/computeResponsive.js#L28 and see if you can fix it? 

Perhaps there's a fundamentally different (and better) way of calculating this.

**Comment by rneher** [comment]
if I change it to 100, it works on linux/chrome and firefox. reducing it to 56 breaks it on linux/firefox. status quo works for firefox, not chrome

**Comment by rneher** [comment]
this surely has to do with all the different paddings that are added here and there. I don't see why we need to get this right to the pixel. I don't think it matters if there are 30px of white space on the right.

**Comment by colinmegill** [comment]
The right thing to do here is probably to measure the size of the
container. https://www.npmjs.com/package/react-measure or another similar
package, or a custom implementation based off of them (they aren't
complicated) and base the subsequent computations off of that.

**Comment by tsibley** [comment]
Given the [reason for existence cited in the code James pointed at](https://github.com/nextstrain/auspice/blob/f808ab0/src/util/computeResponsive.js#L2-L13), I wonder if using appropriate `viewBox` attributes on our `<svg>` elements might be a better alternative to measuring and calculating dimensions ourselves.

**Comment by jameshadfield** [comment]
I think i'll change the value to ~100px so that it's not broken now for people.

Going forward, something like `react-measure` or viewBox may be better.

**Comment by jameshadfield** [comment]
Please reopen if it's still broken on v1.23.2.

**Comment by colinmegill** [comment]
This is fixed here on windows and looks beautiful. It's a fine solution,
especially now that cards are gone.
