### ISSUE TITLE
Double scrollbars on narrative content

### ISSUE THREAD

**Issue by tsibley** [nextstrain/auspice#578]
This is due to both the `Narrative` and `Sidebar` setting `overflow` to `scroll`.  Using `overflow: auto` will generally do the right thing, but in this case its not the complete solution.  The `Sidebar` element—either through excess padding or an over-tall `Narrative`—is being pushed taller than the viewport height.  I'm slightly hesitant to start futzing with the styling myself, because while I could fix the double scrollbar, I'm not familiar enough right now with the rest of the UI to know if I'd make anything else worse in the process.

![selection-003](https://user-images.githubusercontent.com/79913/41053856-97cdfdbe-6971-11e8-9a0c-9dcad2116995.png)

I suspect the scrollbars aren't as noticeable on macOS because of how they're rendered on that platform.

**Comment by trvrb** [comment]
![yo-dawg-heard-you](https://user-images.githubusercontent.com/1176109/43998565-27a3691e-9dad-11e8-919d-07c504911e7c.jpg)

**Comment by jameshadfield** [comment]
@tsibley are these still present in current `master`?

**Comment by tsibley** [comment]
The double scrollbars are not! \o/

There is still a single scrollbar which seems to uselessly scroll just a tiny bit of padding/margin, sliding the menu/logo up a smidge.

![screenshot from 2018-08-31 15-32-21](https://user-images.githubusercontent.com/79913/44938340-23c74780-ad33-11e8-926b-12dd356a8460.png)

**Comment by jameshadfield** [comment]
Sweet. I don't get these on any browsers on OS X, so hopefully someone else can take this one.
