### ISSUE TITLE
Changing second tree via navigation bar doesn't update tree label

### ISSUE THREAD

**Issue by barneypotter24** [nextstrain/auspice#579]
When visualizing tangle trees, if I switch from one secondary tree to another using the drop-down menu in the navigation bar, the label for the first will remain at the top of the page. For example, if I am visualizing a tangle-tree with HA and NA, and I switch the second tree to be MP by selecting `Second Tree` ->  `mp`, the tree, URL, and displayed label in the navigation bar will change, but the tree label will still be NA.

<img width="920" alt="image1_tree_name_bug" src="https://user-images.githubusercontent.com/14949788/41058279-3f9d8f4e-697e-11e8-86bd-b0510d494ee7.png">

I can get around this issue by selecting `Second Tree` -> `REMOVE` first, then selecting `Second Tree` -> `mp`.

<img width="910" alt="image2_tree_name_bug" src="https://user-images.githubusercontent.com/14949788/41058367-75d0f51a-697e-11e8-80ae-5cc0ead885d1.png">

This issue is not specific to NA being the original second tree, it can be reproduced using other segments as the initial second tree selection.

<img width="902" alt="image3_tree_name_bug" src="https://user-images.githubusercontent.com/14949788/41058403-92b13082-697e-11e8-92df-de0bd9480834.png">

Everything seems to work as expected when navigating to a specific secondary tree via URL.

**Comment by jameshadfield** [comment]
Thanks @barneypotter24 - super clear explanation 👍
