### ISSUE TITLE
num_date Colour Extrapolation Fails for TB Data

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#580]
I'm having an odd intermittent bug where colouring by `num_date` sometimes colours the most recent tips black:
![image](https://user-images.githubusercontent.com/14290674/41151182-5119a27e-6b10-11e8-8e3b-db054e19ac7e.png)

It seems that in the newer (live) [Zika dataset](https://nextstrain.org/zika?c=num_date) this is also a problem: (though not as black?)
![image](https://user-images.githubusercontent.com/14290674/41153202-61f2c66a-6b16-11e8-91c5-ed716f941d89.png)

I think the source of this may be:

On [line 165](https://github.com/nextstrain/auspice/blob/master/src/util/colorScale.js#L165) in colorScale.js the `scale` function is set from `d3-scale.scaleLinear()` with `domain` and `range` specified above. However, `domain` has length 11 and `range` has length 10. According to `d3-scale` [docs](https://github.com/d3/d3-scale#continuous-scales):
> If the domain and range have different lengths N and M, only the first min(N,M) elements in each are observed.

and

> If the given value is outside the range, and clamping is not enabled, the mapping may be extrapolated such that the returned value is outside the domain.

This seems to be what is happening, as if you enable clamping the "last" (most recent date's) colour generated changes for (my older dataset of) Zika and TB to match the previous colour. 

Clamping off:
![image](https://user-images.githubusercontent.com/14290674/41151594-824d90f2-6b11-11e8-8cbf-5e6d1471735c.png)

Clamping on:
![image](https://user-images.githubusercontent.com/14290674/41151616-8f48caba-6b11-11e8-9e81-c77d1e1ca3ae.png)

I thought the problem might be related to the difference between the second-to-last and last value in `domain` being too large, but I've not been able to reliably show this, so I'm unsure what exactly is causing the extrapolation to end up generating black (or nearly black) in some cases.

Changing [line 159](https://github.com/nextstrain/auspice/blob/master/src/util/colorScale.js#L159) in colorScale.js to:
`range = colors[n+1]` 
Seems to fix this, but it may also be that what goes into domain should be reduced by 1, depending on the thinking behind the code.

TB with the `n+1` fix:
![image](https://user-images.githubusercontent.com/14290674/41153351-bf93420e-6b16-11e8-8b9b-0ebb644e4b0d.png)

**Comment by jameshadfield** [comment]
Thanks @emmahodcroft!
