### ISSUE TITLE
Source JSONs from github repos

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#588]
URLs such as nextstrain.org/community/X/Y should attempt to source JSONs from the github organisation `X` and repository `Y`. This requires that augur-produced JSONs are committed, e.g. to `repoName/data/auspice` or `repoName/auspiceJSONs`. 

If it's multi-part dataset (e.g. nextstrain.org/community/X/flu/seasonal/h3n2/3y), then the repository should be called `flu` and the JSONs named `flu_seasonal_h3n2_3y_tree.json` etc.

Considerations:
* use rawgit including compression
* allow the repo `Y` to be named `nextstrain-Y` (e.g. you can imaging that `myLabGitHub/flu` is already taken, and it isn't obvious that it's a nextstrain related repo) -- @trvrb do we want to enforce this?

**Comment by trvrb** [comment]
I wouldn't enforce "myLabGitHub/nextstrain-flu". I picture it being useful and (hopefully) common to have a few auspice JSONs in a repo that is largely not devoted to being a Nextstrain build. We'd do this with blab/zika-usvi for example, where we can include the tree that matches dataset used in paper, but Nextstrain is not the focus of the repo.

**Comment by trvrb** [comment]
Partly for these reasons I like using top-level "auspice/" for JSONs meant to be shared, rather than putting them in "build/auspice/" or "data/auspice/".

**Comment by trvrb** [comment]
_Moved discussion to https://github.com/nextstrain/zika/issues/7._

**Comment by jameshadfield** [comment]
working in 13a20dcc04c979758bef57056b5481d0ec46973c
