### ISSUE TITLE
Duplicate Legend Dates & Date Formatting Issue

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#591]
### Duplicate Date Choice
For TB data, many samples only have year, and similar samples often have the exact same decimal date inferred by TreeTime. Because the legend dates are selected from sample dates ([line 173](https://github.com/nextstrain/auspice/blob/master/src/util/colorScale.js#L173)-4 in colorScale.js), many samples with the exact same date means a higher chance that the same date is picked multiple times for the legend. 
![image](https://user-images.githubusercontent.com/14290674/42268294-6dce74d8-7f7b-11e8-9a5c-07d498d7ff5f.png)
In the above, the second two '2012' legend items are both 2012.072333515651, and are the same colour orange. It also causes a warning that two children have the same key: 
![image](https://user-images.githubusercontent.com/14290674/42268408-b401368e-7f7b-11e8-87a7-6a79015c5393.png)

One option may be to filter `vals` (sample dates) to take only unique values. This changes the legend from the above to:
![image](https://user-images.githubusercontent.com/14290674/42269359-3a6c9d2e-7f7e-11e8-92ee-fab09377f3dd.png)
It doesn't seem to have too much effect on my local Zika build legend, but this would need to be checked in other builds.

I also tried incrementing the index to be used from `val` by 1 until the value wasn't already in `domain`. This works, and has a smaller impact on the spacing of the legend values compared to the current version, as it only changes 1 value:
![image](https://user-images.githubusercontent.com/14290674/42270109-515e57fa-7f80-11e8-8b79-72ef8255741d.png)
But could in theory give some strange results depending on the date distribution and number of duplicates.

### Date Formatting
Because the tree for TB spans more than 10 years, they're processed as integers ([line 141](https://github.com/nextstrain/auspice/blob/master/src/components/tree/legend/legend.js#L141) in legend.js), resulting in (as in the above with 2012) multiple entries for a year with different colours, but no sense of spacing between them. For some pathogens having only year makes sense, but it looks odd when you have multiple values from the same year. Changing from 10 years to 200 (and using the second fix above to avoid duplicate dates) produces:
![image](https://user-images.githubusercontent.com/14290674/42270649-b0f78a96-7f81-11e8-8e34-f0905f0857f0.png)

But this wouldn't preserve using year-only for pathogens like [West Nile](https://nextstrain.org/WNV/NA?c=num_date). 

Alternatively, using the 'only unique dates' option above solves this for this particular TB dataset (see above), but may not in all cases.

**Comment by jameshadfield** [comment]
How about filtering the domain to unique values (https://github.com/nextstrain/auspice/blob/master/src/util/colorScale.js#L175), then you'd have the original legend but with only one 2012 entry (although there would be less than 10 now).

re: date formatting. Ten years is arbitrary but I wanted to avoid appearing precise for dates which are usually outside the sampling frame and likely contain large errors (e.g. specifying "Jun 1921" seems silly to me). You could instead change it to "if the date is in the last 10 years then add the month", so the legend contains both for TB.

**Comment by emmahodcroft** [comment]
Yes, happy with filtering domain to unique values as long as having less than 10 points is ok with general auspice-thinking. 

And yes, I completely agree that for distant dates it doesn't make sense to include the month! Following your idea I tried modifying to show month if the label is within 10 years of the 'last' (most recent) label. It ends up (when combined with the above filtering) like this:
![image](https://user-images.githubusercontent.com/14290674/42318566-b04866b4-804f-11e8-9962-b7e5d49ff676.png)

This will also impact how datasets like West Nile display - is that ok? If so, I can create an branch on auspice with those two changes.


(And unfortunately it may still look a little weird for some runs because of slight changes in inferred dates... :
![image](https://user-images.githubusercontent.com/14290674/42318760-51231b6a-8050-11e8-859a-d1dc9725cdd8.png) )

**Comment by jameshadfield** [comment]
I think this is pretty good for now :+1: Must have been some serious sampling in Jan 2012...

**Comment by jameshadfield** [comment]
Closed in #592
