### ISSUE TITLE
Load schema 2.0 JSONs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#595]
Can we make this backwards compatible?

**Comment by tsibley** [comment]
A general approach to backwards compat in matters like this is to write a transformation function that takes a version 1.0 data structure and returns a best-effort version 2.0 data structure. Auspice can then always work with 2.0 data structures and convert 1.0 → 2.0 on load. This follows the principle of converting/transforming data at the "edges" of the application and using a single standard representation within.

**Comment by jameshadfield** [comment]
Yup. In this case it would require maintaining the code to fetch both the tree & meta JSONs, then combine them & patching them to (roughly be) v2.0.

**Comment by jameshadfield** [comment]
The server now combines (v1) meta & tree JSONs into a unified JSON. This function https://github.com/nextstrain/auspice/blob/master/src/server/fetchV1JSONs.js can, over time, begin to patch the newly unified JSON to v2 spec, and the client code simultaneously updated
