### ISSUE TITLE
Nodes removed by dateslider don't return

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#6]
What? 

If you move the bottom handle on the date slider, on http://nextstrain.org/zika/, it removes nodes. Move it back, and not all of them return.

![](https://media.giphy.com/media/l46C7VVGHiC9pxrji/giphy.gif)

**Comment by colinmegill** [comment]
Found this while reproducing functionality in new codebase, @rneher any ideas as to where this might be?

**Comment by rneher** [comment]
these nodes have incomplete dates as in `2015-XX-XX`. Probably the reason for them not returning -- not a good reason though.

**Comment by colinmegill** [comment]
Ah interesting, ok. Well, that's actually on the better side of the problem - I was curious whether or not it might be a problem with the slider, hence wanting to figure it out before digging into converting it

**Comment by rneher** [comment]
will be something along the lines "all nodes are initially shown, upon slider update criterion `date in range` evaluates to smth silly..."
