### ISSUE TITLE
Narratives won't load without a manifest file

### ISSUE THREAD

**Issue by huddlej** [nextstrain/auspice#601]
While trying to get a narrative markdown file to load without a manifest, auspice tries to load an `undefined` pathogen. Adding a proper `manifest_guest.json` file to the data directory corrects the issue.

**Comment by jameshadfield** [comment]
Thanks @huddlej -- i'm currently moving the manifest stuff to the server which will fix this (and the myriad other manifest errors hopefully)

**Comment by tsibley** [comment]
@jameshadfield What are your plans for adding manifest stuff to the server?

**Comment by jameshadfield** [comment]
@tsibley it's happening on branch `server-side-json`, should be ready for PR soon. Generally moving v1->v2 schema stuff, manifests etc to the server. The format of the manifest is completely up for grabs, i'm not changing it but someone can in the future.
