### ISSUE TITLE
Changing datasets crashes with genotype colorby

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#611]
@jameshadfield ---

I generally like the new behavior where visualization state is preserved when switching between datasets via the dropdown. Ie, if I'm at https://nextstrain.org/zika?l=clock and switch to ebola I arrive at https://nextstrain.org/ebola?l=clock. However, if the original visualization state doesn't exist in the target dataset then the app crashes out to 404. For example, if you start at https://nextstrain.org/zika?c=gt-NS1_349 and switch to ebola then the get the crash as ebola doesn't have `NS1` to color by. 

Actually... for non-genotype color bys you don't get a 404, but it's still unexpected behavior. For example, go from https://nextstrain.org/WNV/NA?c=wnv_strain and select zika and you end up at https://nextstrain.org/zika?c=wnv_strain, which then shows coloring by date.

This issue exists for geo resolutions in addition to color bys. For example, https://nextstrain.org/zika?r=region switches to https://nextstrain.org/ebola?r=region, which doesn't exist.

I don't know the best treatment for this. One option would be to return to the previous behavior of nuking state, but this is bad for things like panel grid. Fixing the crash on genotype color by seems like an obvious first step.

**Comment by jameshadfield** [comment]
> https://nextstrain.org/zika?l=clock and switch to ebola I arrive at https://nextstrain.org/ebola?l=clock

Aha... This wasn't intentional - but yes, it's nice in some situations!

Geographic resolution & colorBy are "dataset specific" (as opposed to grid etc) so perhaps these should be nuked on dataset change... Other things work but remain in the URL (e.g. having the frequency panel in the URL and going to zika doesn't raise any errors, but the frequency panel is still specified in the URL, which isn't correct)

**Comment by trvrb** [comment]
There are situations where it's nice to keep colorby when changing datasets for example going from https://nextstrain.org/flu/seasonal/h3n2/ha/3y?c=ep to 12y it's nice to keep coloring by epitope. But maybe this is too difficult to accomplish generically, as going from https://nextstrain.org/flu/seasonal/h3n2/ha/3y?c=ep to vic lacks epitope as a coloring option.

Nuking everything except "grid" seems like a pretty good option. Grid layout feels very natural to keep when changing datasets.
