### ISSUE TITLE
Changing datasets on staging is buggy

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#618]
Thanks for humoring me with these @jameshadfield. I just noticed an issue when changing between staging datasets. If I start at:

https://nextstrain.org/staging/flu/seasonal/h3n2/ha/3y

I can select "2y", "6y", etc... in the Dataset dropdown just fine. However, if I change lineage to "H1N1pdm" or "Vic" the app 404s out. Similarly, if I'm on https://nextstrain.org/staging/zika and change virus to "Flu" the app also 404s.

**Comment by jameshadfield** [comment]
Well that's not good!

The JSONs seem to be on the (staging) S3 bucket, and indeed https://nextstrain.org/staging/flu/seasonal/vic/na/12y works just fine.
The manifest also looks ok there... i'll do some investigating

**Comment by trvrb** [comment]
Thanks for fixing this @jameshadfield.
