### ISSUE TITLE
genotype coloring/zoom broken in firefox

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#635]
@jameshadfield genotype coloring is broken in firefox with 
```
TypeError: "r.event.sourceEvent.srcElement is undefined"
```
This is triggered by `changeColorBy` which in turn triggers a brush move and it ultimately fails in brush finished.
![image](https://user-images.githubusercontent.com/8379168/44540442-1bee1e80-a707-11e8-83aa-3f0773b9a1f6.png)

**Comment by rneher** [comment]
the page turns blank...

**Comment by emmahodcroft** [comment]
😕 I'll have a look tomorrow

**Comment by emmahodcroft** [comment]
The event property `srcElement` is non-standard and originates in IE, but doesn't exist in Firefox. I've replaced this with standard property `target` that hopefully should work more widely. Tested on FF, Chrome, Edge, and IE and seems to work. @rneher could you check PR [637](https://github.com/nextstrain/auspice/pull/637) and ensure it fixes the issue?

**Comment by rneher** [comment]
yes. works now! Thanks!

**Comment by jameshadfield** [comment]
Nice! Closed in v1.27.1
