### ISSUE TITLE
Dates in info text should refer to tips and not to nodes

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#640]
@jameshadfield ---

Working with Lassa made me notice this just now...

Currently, we have some very weird language like 

>Showing 78 of 78 genomes, from 0 countries, from 11 divisions, dated Jul 1662 to Mar 2018.

for Lassa and 

> Showing 1470 of 1470 genomes, from 208 authors, from 10 regions, from 84 countries, dated Nov 1633 to Jul 2017.

for dengue. The text here is referring to "genomes". These are tips in the tree. Dates should be collected from tips rather than nodes.

The date filter doesn't have to change. Still makes sense to write

> Filtered to Jul 1662 to Dec 1942

**Comment by lixingguang** [comment]
@trvrb Do you notice my email?
