### ISSUE TITLE
npm start should work

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#651]
@jameshadfield ---

I find it quite strange to have `npm start` deprecated: https://github.com/nextstrain/auspice/blob/master/package.json#L20

It's standard across npm packages to be able to run `npm start` as the standard default option. `npm start` could do the production server rather than the dev server, but it should be the standard entrypoint.

**Comment by jameshadfield** [comment]
Absolutely, this has now been fixed.

**Comment by trvrb** [comment]
Thank you @jameshadfield!
