### ISSUE TITLE
Include bin with auspice install

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#652]
@tsibley and @jameshadfield ---

Related to https://github.com/nextstrain/augur/issues/147.

I was doing some work on https://github.com/artic-network/artic-ebov/blob/master/pages/ebov-phylogenetics-sop.md / http://artic.network/ebov/ebov-phylogenetics-sop.html and wanted an easy way to bring up an auspice view. The current ARTIC install relies completely on conda (http://artic.network/ebov/ebov-it-setup.html) and so I didn't want to ask for docker to be installed if we can avoid it. I got `augur` / `nextstrain build --native` installed easily as part of the conda install and was then trying to do the same for `auspice`.

Take a look at the `bin` branch. This adds
```
"bin": {
  "auspice": "./server.js"
},
```
to `package.json`. I also pushed this to npm at https://www.npmjs.com/package/auspice with the idea that you can then run `npm install -g auspice` to get a globally callable version of auspice.

However, calling `auspice` results in
```
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'dist'
    at Object.readdirSync (fs.js:759:3)
    at findAllCompressionFiles (/usr/local/lib/node_modules/auspice/node_modules/express-static-gzip/index.js:127:24)
```
due to `server.js` looking in the wrong place for files in `dist/` I believe.

You can reproduce this by checking out the `bin` branch and running `npm uninstall` followed by `npm install -g` from within the `auspice/` directory.

If you think it's a good idea, could one of you work on this?

**Comment by tsibley** [comment]
I think this is a good idea, yes. It should eliminate the need for https://github.com/nextstrain/docker-base/blob/master/auspice-wrapper.  I see @jameshadfield has assigned this to himself, so I won't work on it.

One thing to note is that with the `postinstall` script should probably go away for global installs.
