### ISSUE TITLE
Blue dots bunch to left on IE/Edge/iPhone

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#655]
In Internet Explorer, Edge, and on iPhone (maybe others?) the blue dots at the top of narratives bunch to the left.

![image](https://user-images.githubusercontent.com/14290674/45081545-b41cd800-b0f7-11e8-8228-bd2f443492fa.png)

**Comment by kairstenfay** [comment]
Closed by #875 thanks to @ivan-aksamentov
