### ISSUE TITLE
fix travis npm deploy issues

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#658]
While I followed https://docs.travis-ci.com/user/deployment/npm/ (and this example https://github.com/bcoe/travis-deploy-example/blob/master/.travis.yml), it is failing with

```
Preparing deploy
NPM version: 5.6.0
Authenticated with email jhadfiel@fredhutch.org and API key ****************sR8=
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
~/.npmrc size: 48
dpl.3

Deploying application
npm ERR! publish Failed PUT 401
npm ERR! code E401
npm ERR! 404 You must be logged in to publish packages. : auspice
npm ERR! 404 
npm ERR! 404  'auspice' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

We can publish manually in the meantime.

**Comment by trvrb** [comment]
I can show you how to add auth keys to Travis CI.

**Comment by jameshadfield** [comment]
Yup, however https://docs.travis-ci.com/user/deployment/npm/ says nothing about needing auth keys. And you can see from the log that it (seems to) login and authenticate to npm, despite the latter message.

**Comment by jameshadfield** [comment]
May or may not be related to https://www.npmjs.com/package/auspice only showing @trvrb as the collaborator (despite me being able to deploy via `npm publish`)
