### ISSUE TITLE
NPM_TOKEN not defined

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#661]
Bug that I just introduced, when running `npm start`, or anything really the value of `NPM_TOKEN` that's specified here https://github.com/nextstrain/auspice/blob/master/.npmrc is not defined. This causes the following error:
```
Leda:auspice trvrb$ npm start
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /usr/local/lib/node_modules/npm/lib/config/core.js:415:13
```
Maybe there's a simple way to define a fall back in the `.npmrc` file? Sorry about this.

**Comment by tsibley** [comment]
@trvrb I believe PR #662 will fix it. It is untested because it requires pushing to `release` to test.

**Comment by tsibley** [comment]
I made a new release, 1.30.2, to test that my fix works. It does!
