### ISSUE TITLE
release script broken on MacOS

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#667]
The changes to the `sed` command (commit e210987950ad3fae0a70e000b0f94f00b6a4ae68) mean it no longer works on MacOS.

Error:
```
sed: 1: "package.json": extra characters at the end of p command

Script Failed at step 2 (Line 70)
```

**Comment by tsibley** [comment]
Ugh, sorry, I tried to ensure it'd still work there by closely reading the BSD sed manual (since I didn't have access to the executable).  But clearly something's goofy still.  I can fix this, but will need someone to test.
