### ISSUE TITLE
change community builds CDN

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#672]
Community URLs currently source the JSONs from github via the rawgit CDN.
Rawgit is shutting down -- see https://rawgit.com/
We should migrate the CDN -- https://www.jsdelivr.com/rawgit looks simple.

**Comment by tsibley** [comment]
Trevor and I chatted about this on Slack this morning. jsDelivr has size limits that we bump into pretty easily. It looks like Github's own raw content server (raw.githubusercontent.com) is using Fastly these days and serving compressed, highly cached content. Trevor's preparing a branch to switch to it which I'll review.

**Comment by jameshadfield** [comment]
Nice one. Thanks!
