### ISSUE TITLE
colorBy query string gets corrupted when switching between builds

### ISSUE THREAD

**Issue by huddlej** [nextstrain/auspice#691]
When I select a non-default colorBy (e.g., antigenic advance) for a seasonal flu build of HA and then switch to the corresponding build for NA, the query string for the selected colorBy gets split into separate query strings with one entry per letter of the colorBy value. A complete example to recreate this problem is given below.

1. Navigate to seasonal flu build: https://nextstrain.org/flu/seasonal/h3n2/ha/3y
2. Select a color by from the dropdown (e.g., antigenic advance): https://nextstrain.org/flu/seasonal/h3n2/ha/3y?c=cTiter
3. Select a different segment from the dropdown (e.g., NA) and inspect new URL: https://nextstrain.org/flu/seasonal/h3n2/na/3y?0=%3F&1=c&2=%3D&3=c&4=T&5=i&6=t&7=e&8=r

I only noticed this issue after the recent auspice update, but it might have existed prior to that.

**Comment by tsibley** [comment]
> splitting it into an array of individual characters

Ah, not an actual `split`, but implicit by treating a string as an array. The `PAGE_CHANGE` event dispatched by the commit above should pass `query` as a parsed object returned by `queryString.parse()` instead of a bare string. (The bug existed in the previous version of the code too in certain circumstances it seems.)

**Comment by huddlej** [comment]
Thank you for digging into this @tsibley ! @jameshadfield had mentioned that this bug occurred in the past somewhat randomly and without a clear way to reproduce it. Do you have time to submit a PR for this fix?

**Comment by jameshadfield** [comment]
>@jameshadfield had mentioned that this bug occurred in the past somewhat randomly and without a clear way to reproduce it.
That was referring to a different bug: namely that the date slider handle often doesn't appear on the right hand side as it should (it's there, but on the left instead). 

I can look into this issue today and see if there's an easy fix
