### ISSUE TITLE
Slider should recover gracefully from consolidation:

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#7]
![](http://i.giphy.com/l3vRkBmj8nFY8kGhq.gif)

**Comment by trvrb** [comment]
The way to solve this will be to keep the right hand circle from ever overlapping with the left hand circle (and vice versa) in the data slider. Ie. never allow the "consolidated" state to occur in the first place.

**Comment by trvrb** [comment]
This is fixed in df5ad4b467d79334ba967f3016d263ffd7d07957 in `styles-pass` branch.
