### ISSUE TITLE
404 page should preserve URL

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#700]
Currently, if auspice 404s it punts back to the base URL. For example, http://nextstrain.org/zika1 404s, but the URL is changed to https://nextstrain.org/. I don't think this is good behavior. Often, there's just a slight misspelling and this also breaks the use of the back button. I believe 404s should resolve as they do on bedford.io for example: https://bedford.io/zika.

**Comment by jameshadfield** [comment]
Sounds very reasonable to me, i'll try and get a fix up ASAP.
