### ISSUE TITLE
Sorting of dataset dropdown could be improved

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#705]
Currently, if the manifest lists something like:
```
            "h1n1pdm": {
              "segment": {
                "ha": {
                  "resolution": {
                    "2y": "",
                    "3y": "",
                    "6y": "",
                    "12y": "",
                    "pandemic": "",
                    "default": "3y"
                  }
                },
```
It will display as:

<img width="569" alt="h1-options" src="https://user-images.githubusercontent.com/1176109/53061692-3feeaa80-3473-11e9-969b-4eb59d52fabc.png">

where the default option of `3y` gets sorted above all other options.

I think this looks strange in this case to have a list of menu options that go: 3y, 2y, 6y, 12y. I'd recommend just sticking with the ordering in the manifest JSON rather than moving default to top.

**Comment by tsibley** [comment]
This is the same request as #696.

> I'd recommend just sticking with the ordering in the manifest JSON rather than moving default to top.

Note that regardless of the source text, JSON objects `{…}` don't have a particular key order defined: “An object is an unordered set of name/value pairs.” The select widgets must choose an explicit order to use at display time.

**Comment by trvrb** [comment]
I see. I'll close this in favor of #696.
