### ISSUE TITLE
Tangletree URL does not match for Lassa

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#706]
Small bug I just noticed. If you go to:

https://nextstrain.org/lassa/s:l

You properly got the "s" segment / "l" segment tangletree, but the URL is updated to:

https://nextstrain.org/lassa/s

**Comment by jameshadfield** [comment]
Fixed in nextstrain.org via commit: https://github.com/nextstrain/nextstrain.org/commit/8fcbe074e86a1147795ba64347d46d2ad7f4e5c1
And in auspice via commit: 51ccced9618017ae35c3fa5ef62349ef3f477acc

Note that addressing #687 will shift the logic for this back to the client.
