### ISSUE TITLE
Code splitting has broken d3 transitions

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#708]
This bug was introduced between v1.35.5 and v.1.36.0 by PR #701 (code splitting). Nextstrain.org is still on v1.35.5 and it's recommended to continue to use that version until this bug is fixed.

## Description:
For some datasets (!) clicking on branches / tips in the tree causes the app to crash. Zika, flu/seasonal/h3n2/ha/3y, and flu/seasonal/h3n2/na/3y appear to work fine, however http://localhost:4000/flu/seasonal/h3n2/ha:na/3y is broken. To reproduce, click on (any?) branch / tip in the tree(s).

## Cause:
Error message given is `svg.selectAll(...).filter(...).transition is not a function`. The selection is not empty, but rather `transition` is not being added as a prototype to the `Selection()` object.

**Comment by trvrb** [comment]
If this proves difficult to immediately fix, we may want to push a hot fix to 1.36.1 that reverts the code splitting PR. Even though live site is working. We won't be able to make small fixes to footer, etc... and anyone installing auspice from npm will have this issue.
