### ISSUE TITLE
Docusaurus dependency

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#711]
I believe the Docusaurus dependency (https://github.com/nextstrain/auspice/blob/master/package.json#L71) is only used when building the docs site. Running `npm install -g` to get the command line tool `auspice` shouldn't need this I believe.

I bring this up, because `gifsicle` when is a sub-dependency of Docusaurus:
```
└─┬ docusaurus@1.7.2
  └─┬ imagemin-gifsicle@6.0.1
    └── gifsicle@4.0.1 
```
But installing gifsicle requires Unix `autoreconf`. The lack of this utility is causing Docker builds to fail:
https://travis-ci.com/nextstrain/docker-base/builds/103098560#L1055

I can include this utility in the Dockerfile, but I think generally cleaner to move docs dependencies to a `package.json` file under `docs-src/`. Would you agree @jameshadfield? Want to generally reduce the capacity for these sorts of conflicts.

**Comment by tsibley** [comment]
I noticed the first `gifsicle`-related Docker image build failure last week, but it's been low on my priority list to fix since the new releases of auspice don't change much for the Docker image use cases.

++ for reducing the deps auspice requires for typical usage.

**Comment by trvrb** [comment]
Alternatively, we could move Docusaurus to dev dependencies in the main package.json.

**Comment by tsibley** [comment]
I believe `npm install` installs `devDependencies` by default unless you specifically ask it not to via flags like `--only=production` or `--production`.

I'm not sure what the full implications are for a second `package.json` under `docs-src/` with regard to the current scripts/workflow for building the docs. @jameshadfield might know more here without having to investigate.

**Comment by jameshadfield** [comment]
> I can include this utility in the Dockerfile, but I think generally cleaner to move docs dependencies to a package.json file under docs-src/. Would you agree @jameshadfield? Want to generally reduce the capacity for these sorts of conflicts.

Seems sensible to me, the doc-building scripts will just need to run `npm install` from the relevant directory (we do this for the gatsby-built static part of nextstrain.org: https://github.com/nextstrain/nextstrain.org/blob/master/set-up.sh#L17).

Note that a lot of "dev-dependency" libraries actually need to be in "dependencies" for things like `auspice build` to work, but this isn't one of them.

**Comment by trvrb** [comment]
BTW the proximal issue with Docker and docusaurus has been resolved:

* https://github.com/nextstrain/docker-base/commit/f3291c52c8aebda358d0974c62e4f84df3f1200f
* https://travis-ci.com/nextstrain/docker-base/builds/103307302

**Comment by tsibley** [comment]
Thanks, @trvrb!
