### ISSUE TITLE
Change port 4000

### ISSUE THREAD

**Issue by vagnerfonseca** [nextstrain/auspice#718]
Hello,

I would like to change the application access port (4000), which file do I need to update for this to take work?

**Comment by trvrb** [comment]
Hi @vagnerfonseca, the easiest way to change the port is by running the Nextstrain CLI (https://github.com/nextstrain/cli). With this installed, you can run 

```
nextstrain view --port 4001 auspice/
```

This will be equivalent to running `auspice view --datasetDir auspice/` Let me know if this doesn't work for you.

**Comment by jameshadfield** [comment]
Hi @vagnerfonseca -- If you'd prefer to use auspice directly, you can set an environment variable:
```bash
export PORT=3000
auspice view ...
```

**Comment by hackerchenzhuo** [comment]
so kind of u
