### ISSUE TITLE
how to develop v2

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#721]
This issue is a request for comments regarding the github branching structure for the next 1-2 months, as some people may feel strongly about this, as well as the general development plan.

As discussed in 2019-04-22, we plan to move auspice to epiphyla in June. Between now & then I plan to work on the following features, all of which will result in some 2.0.0 alpha/beta testing versions (including PR #720).

1. Documentation (including a plan for contributions 🙏 )
2. Clean up client customization interface
3. Investigate new client-server API
4. Improve GitHub-pages creation
5. Move narrative parsing to client (needed for static sites)

During this time I don't anticipate any substantial work on auspice 1.x.x, but there may a small number of bug fixes. I plan to create a new branch (`v2`, or something) and merge PRs into this, with any small bug fixes for v1 going into master (and released as normal). The plan would be to merge `v2` in June, together with the move to epiphyla & new documentation.

**Comment by tsibley** [comment]
This sounds fine to me. Long-lived trunk branches (`master`, `v2`, etc) are typical when dealing with multiple major versions.
