### ISSUE TITLE
Test `npm install --global` on different setups

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#724]
> ... After more Googling, this seems to work for me... `sudo npm install --global auspice@alpha --unsafe-perm=true --allow-root`

_Originally posted by @emmahodcroft in https://github.com/nextstrain/auspice/pull/720#issuecomment-491893236_

@emmahodcroft were you using nodejs inside a conda environment, or a system nodejs install?

**Comment by emmahodcroft** [comment]
I believe it's a system install. If there's anything I can fun to produce more useful information just let me know :)

**Comment by jameshadfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test global auspice install on your system](https://trello.com/c/pQyDTI0Q/13-test-global-auspice-install-on-your-system)

**Comment by jameshadfield** [comment]
Rolling updates on what works, and what doesn't!

## Works
- ubuntu using `nvm` to manage nodejs (kairsten)
- macos using `conda` (james)

## Doesn't work
- ubuntu using system nodejs install (kairsten)
- windows using system nodejs install (emma)

**Comment by joverlee521** [comment]
on macos `npm install --global auspice@alpha` worked for me

**Comment by jameshadfield** [comment]
thanks @joverlee521 -- did you have a system install of node/npm, or were you using nvm, or conda?

**Comment by joverlee521** [comment]
@jameshadfield I have a system install of node/npm
