### ISSUE TITLE
ordinal color scales

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#726]
we allow discrete and ordinal color scales in v2 schema. the order of discrete scales is determined by abundance. ordinal scales should be sorted by value. This is currently not implemented but would easy to add here:

https://github.com/nextstrain/auspice/blob/master/src/util/colorScale.js#L137

any thoughts?

**Comment by jameshadfield** [comment]
Hi @rneher -- this is definately needed, however it should happen on the v2 branch. Currently (v2 branch, for v2 JSONs) ordinal & discrete both use the same scale,
