### ISSUE TITLE
2.0: Source Color By Title from menuItem in V1 JSONs

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#730]
Currently it seems Auspice 2.0 (both when displaying and in `auspice convert`) uses `legendTitle` as the drop-down Color By text when processing `augur export` V1 JSONs. It should use `menuItem`. 

This should be a quick fix, hopefully :) Thought you could do it quicker, James, but I can come back to it if needed.

**Comment by jameshadfield** [comment]
closed by c575384
