### ISSUE TITLE
Coloring display when tree is missing attribute

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#737]
This bug was discovered for seasonal flu here: https://github.com/nextstrain/seasonal-flu/issues/33 and can be seen live at https://nextstrain.org/flu/seasonal/h1n1pdm/na/2y?c=ep. Basically, the auspice config specifics `ep` as a coloring attribute, but `ep` does exist as an attribute anywhere in the tree. This could be viewed as augur user error (and we should fix this in seasonal flu), however, it would be nice if auspice handled this a bit more gracefully.

I would say this is low priority, but I suspect not too difficult to deal with.

**Comment by jameshadfield** [comment]
Good find. Did `augur validate` pick this up? I hope that after augur v6 all the builds will start validating the JSONs, but I agree that auspice should handle this better 👍

**Comment by trvrb** [comment]
Looks like this resolved itself. I'm closing the issue now.
