### ISSUE TITLE
genotype color-by not shown in sidebar dropdown on page load

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#738]
When setting a genotype color-by via a URL (e.g. go to https://nextstrain.org/zika?c=gt-nuc_255), the colors are correct in the app, but the sidebar color-by dropdown hasn't updated to reflect this state (it shows the blank "Select..." placeholder). This issue is not present for non-genotype color-bys.

**Comment by charlie-jones** [comment]
@jameshadfield I would be happy to work on this. It seems like the solution is to call gtGeneSelect() and gtPositionInput() and fill them in respectively; my proposal is to split the value  by "-" and "_" if the first two characters are "gt".

**Comment by tsibley** [comment]
@charlie-jones There already exist functions to parse the serialized URL parameter `c`. Values from the "controls" Redux store flow into the ColorBy component via props. The issue here may be that the "controls" Redux store isn't being properly initialized from the URL param.

**Comment by charlie-jones** [comment]
@tsibley I appreciate the advice, thank you! The initialization of the store was, in fact, the problem, so I will submit a PR after finishing up testing.

**Comment by jameshadfield** [comment]
This issue is no longer -- perhaps closed by the above linked PR?
