### ISSUE TITLE
Nucleotide colorby is broken

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#749]
via @emmahodcroft 

If I click on sites in NT view, either entropy or events, the entropy bar zooms correctly and everything, but the tree doesn't recolor... it acts like there is only 1 base at this position (no variance/variants).

This doesn't work for V2 JSONS generated by augur export V2, V2 JSONS generated from V1 (via auspice convert), or V1 JSONS. Must be Auspice 2.0 problem.

**Comment by emmahodcroft** [comment]
I'd forgotten about this but does indeed still seem to be broken for me...
