### ISSUE TITLE
Conda install for auspice

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#762]
This would be fantastic to have to remove the need to run `npm install --global auspice` once the conda environment is set up.

**Comment by ccarson-publicsalesforce** [comment]
I have a proposal to sidestep the issue entirely - support the use of VSCode development containers. This wraps the global install for auspice to just the docker container, rather than the bare metal machine.

**Comment by tsibley** [comment]
Resolved by https://github.com/bioconda/bioconda-recipes/pull/27188.
