### ISSUE TITLE
map breaks on missing coordinates

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#763]
I played around with augur v6 and converted some builds I have been helping people with to v6/v2. In one case (json on slack) I manage to break auspice. Validation reports internal inconsistency (asia is a region that is not defined). 
```
WARNING: region->asia did not have an associated lat/long value (matching performed in lower case). Auspice won't be able to display this location.

Validating produced JSON
Validation succeeded
Validating that the JSON is internally consistent
	WARNING:  "asia", a value of the geographic resolution "region", appears in the tree but not in the metadata.
	WARNING:  	This will cause transmissions & demes involving this location not to be displayed in Auspice
	WARNING:  The filter "author" does not appear as a property on any tree nodes.
Validation failed
```
filtering to `Asia` produces dangling transmissions
http://localhost:4000/krisp/eduan/crf01?f_region=asia
![image](https://user-images.githubusercontent.com/8379168/62547873-3cef4700-b866-11e9-8c2e-2e248b205933.png)

changing map-resolution to `region` (with missing coordinate) breaks auspice completely:
http://localhost:4000/krisp/eduan/crf01?f_region=asia&r=region
![image](https://user-images.githubusercontent.com/8379168/62547999-6e681280-b866-11e9-9f03-b65f278e6434.png)

**Comment by rneher** [comment]
I have the same problem with other builds that lack certain geo info. This is likely a common scenario as our default geo defs are rather specific. We don't have asia as a region, for example. so graciously handling missing geo data will be important.

**Comment by rneher** [comment]
transmission links remain independently of missing geo data. 
![image](https://user-images.githubusercontent.com/8379168/62551029-8aba7e00-b86b-11e9-86b5-13ce9a00ad2b.png)

kind of pretty, but probably not intended, right?

**Comment by emmahodcroft** [comment]
I can replicate your first issue (dangling transmissions), but not the second exactly - just changing to geo->region doesn't crash for me. It does produce warnings:
![image](https://user-images.githubusercontent.com/14290674/62791276-1c74f600-bacd-11e9-82c1-404fc587e58e.png)

If I use your link, it works.
If I filter->Asia and then geo->region it works.
If I geo->region and then filter->Asia, it crashes. 

However, in either of the 'working' scenarios, if I then go to clear the filter, it breaks.

**Comment by emmahodcroft** [comment]
So I think the dangling transmission may be 'normal' - at least, they happen on my other maps where no geo data is missing. So how we want to handle this may be another issue.

For the crashing, it seems a simple check for whether `demeIndices[location` exists fixes it. I'll do a PR. I didn't check for whether this sorts countries too, but it should I think.

**Comment by jameshadfield** [comment]
Closed via @emmahodcroft's https://github.com/nextstrain/auspice/pull/766
