### ISSUE TITLE
`Maintainer` Missing in Auspice 2.0 with V1 JSON

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#773]
Using a V1 JSON (exported with `master` version of `augur export`) but looking at it in Auspice 2.0, `maintainer` seems to be missing:
![image](https://user-images.githubusercontent.com/14290674/63175796-0f17b880-c045-11e9-8ce1-200ba799d4d2.png)

It's in the `meta.json`:
![image](https://user-images.githubusercontent.com/14290674/63175858-22c31f00-c045-11e9-8e03-47b03bc39743.png)

And it shows up in Auspice 1.0:
![image](https://user-images.githubusercontent.com/14290674/63175889-31a9d180-c045-11e9-92a6-7143f8544032.png)

**Comment by emmahodcroft** [comment]
Also true if the JSON was made with `v6` version of `augur export v1`. So expect this is a issue of finding `maintainer` on the Auspice side.

**Comment by jameshadfield** [comment]
eek -- accidentally removed during development of the pie charts! Back now via b4a531d1b33b9848b80d9cb5cacad3b79e458769
