### ISSUE TITLE
Add available tangle-tree options to available datasets JSON

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#776]
## Current behaviour (v1 auspice)

The "tree name" (e.g. `na` or `ha`) is injected by the nextstrain.org server into the dataset JSON which is delivered to the client, under the top-level property `_treeName` (or `treeName`?). The auspice client uses this information to work out which other datasets are suitable candidates for a second (tangle) tree, and displays them in the dropdown. Logic here: https://github.com/nextstrain/auspice/blob/8790e3d27b2513b60adb7e482256e7b5d52b0c9a/src/components/controls/choose-second-tree.js#L33. 

Note 1: this information is _not_ required to actually access the tree - i.e. you can leave this information out and type in the correct URL (e.g. `na:ha`) and it'll work fine. It's only used to prepare a list of candidates for the sidebar drop-down. 

Note 2: Since the "tree name" is not actually stored in the JSONs anywhere, the server often has to guess at the name. This is what we want to avoid.

## Desired behaviour
The candidate trees should be detailed in the JSON returned by the `getAvailable` API request. Note that auspice makes this request every time it accesses any dataset -- that is, the whenever auspice makes a `charon/getDataset` request, there is also a `charon/gerAvailable` request. 

The `getAvailable` request is handled by the nextstrain.org server here: https://github.com/nextstrain/nextstrain.org/blob/master/auspice/server/getAvailable.js#L6. The generation of the data which is returned happens earlier. You can see what's currently returned by this request via: https://nextstrain.org/charon/getAvailable or localhost:5000/charon/getAvailable (the latter is running `npm run server` from the nextstrain.org repo). 

Ultimately, as you trace things upwards, you find that the data (for the datasets part of `getAvailable`) comes from a "manifest" json which the server fetches & parses. This can be found here: http://data.nextstrain.org/manifest_guest.json. That file is fetched & parsed here: https://github.com/nextstrain/nextstrain.org/blob/master/auspice/server/setAvailableDatasets.js#L67. 
The schema of this JSON document may need modifications, but I hope not. If so, please make them in a backwards-compatible fashion. 

This request should include, for each dataset, a list of possible second trees which the client can then display in the dropdown. The code relating to fetching of the second tree shouldn't need to be changed. 

Note: Currently we'll need to enforce that these candidates only differ by one "part" of the URL, but in the future this can be relaxed. (I.e. currently you can't match `h3n2/ha/3y` and `h3n2/na/2y`, due to how we represent tangletrees in URLS, but we will be able to in the future.) This is due to how we encode the second tree in the URL, which is a separate issue.

Note: This may disable the drop-down functionality for auspice running locally (i.e. using the auspice server), but this can be restored separately.

## Branches
Please create branches off nextstrain.org master and auspice v2.

**Comment by trvrb** [comment]
Nice! I think generic tangle trees would be a great feature. Would be a really frictionless way to compare datasets across groups even. Eyeballing tree differences is difficult, but that's the standard way this is done now.

**Comment by jameshadfield** [comment]
d390b50a4f249aa3a869754ffa02f7703c141cec
