### ISSUE TITLE
Frequencies behave unexpectedly after filtering

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#784]
After filtering (eg. to country or region), frequencies still show fraction of total rather than fraction of the filtered total.
![image](https://user-images.githubusercontent.com/8379168/64058108-89e4e580-cba6-11e9-932e-8ff3f34ce139.png)

**Comment by rneher** [comment]
The tool-tip wasn't captured. it shows 3% for the big sector that is clearly at >70% percent.

**Comment by jameshadfield** [comment]
Not sure I completely understand 🤔 

No filtering shows A1b/135K at 40%

![image](https://user-images.githubusercontent.com/8350992/64058273-b9264180-cbfc-11e9-8aa9-062bfacc457f.png)

Filtering down to 2 clades (A1b/135K + A2) still shows 40%

![image](https://user-images.githubusercontent.com/8350992/64058300-f559a200-cbfc-11e9-9e30-854344a8fd2d.png)

**Comment by rneher** [comment]
![image](https://user-images.githubusercontent.com/8379168/64058321-78e9a380-cba9-11e9-922c-d1d5fd488952.png)
this is filtered down to Japan/Korea

**Comment by rneher** [comment]
The question is what should the denominator be after subsampling: only the shown tips, or all tips. In most cases, I would expect the former.

**Comment by trvrb** [comment]
This was intended behavior to cover scenarios like: https://nextstrain.org/flu/seasonal/h3n2/ha/2y?clade=A2/re, where filtering to a clade should accurately show its frequency through time. Perhaps best here to just update the tooltip to have something like "Total frequency" and also "Filtered frequency".

**Comment by rneher** [comment]
I think the "total denominator" makes sense when filtering and coloring are along the same category. Otherwise, I feel the result is unexpected. If one colors by clade and filters to region, I would expect to see the clade distribution in a region. But low counts with excessive filtering is hard. This is a case where diffusion frequencies are more robust.

**Comment by rneher** [comment]
I am wondering whether we should revisit this now. I am picturing a situation where you want to look at clade frequencies in a particular region and filter down to that region. Currently, you would see the frequencies modulated by total sequence availability in that region. It would be difficult to see whether one clade increased at the exponse of another.
