### ISSUE TITLE
Unassigned Branches get a Colour

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#785]
I am not 100% sure if this is `augur`, `auspice` or both. I think it is `auspice` - seems to happen for older datasets too - but I haven't tested this super-extensively.
Seems to be new behaviour from sometime last week?

Branches with unassigned attributes are getting a colour other than grey:
![image](https://user-images.githubusercontent.com/14290674/64121053-0beb2f00-cd9e-11e9-94c6-7f274ec7a7ca.png)

Also true for other traits:
![image](https://user-images.githubusercontent.com/14290674/64121084-1efdff00-cd9e-11e9-882a-e0015236abb9.png)

Is also reflected in the pie charts:
![image](https://user-images.githubusercontent.com/14290674/64121561-7355ae80-cd9f-11e9-803b-78b0fb059237.png)

I am running the latest v2 `auspice` (or 2.0), and latest `augur` `master` and `v6`. 

This occurs both when I use `augur export` in `master` and `augur export v1` in `v6`.  

It does *not* occur if the colours have been assigned via `colors.tsv`:
![image](https://user-images.githubusercontent.com/14290674/64121324-c5e29b00-cd9e-11e9-8a31-69e2e059749d.png)

Happens on the Heroku Server thingy: (*test dataset to replicate*)
(slightly different tree to what's pictured above, but basically same dataset)
https://nextstrain-dev.herokuapp.com/community/emmahodcroft/echo30/vp1/all

**Comment by jameshadfield** [comment]
Closed in 162824bbed4789a58e1f45930e0dfdc12806fd43. Thanks @emmahodcroft 👍
