### ISSUE TITLE
Option to Filter to 'No Value'

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#787]
In `auspice` 2.0, if not all tips have a trait, and this is set to be a filter option, there's a weird filter to only show those that *don't* have that trait:
![image](https://user-images.githubusercontent.com/14290674/64190485-ccdcdc80-ce76-11e9-9fd7-781cc90b040f.png)

This does not show if every tip has a trait:
![image](https://user-images.githubusercontent.com/14290674/64190506-d8c89e80-ce76-11e9-9f68-618e8b5f7d88.png)

If you click on it, it does indeed filter to those without the trait:
![image](https://user-images.githubusercontent.com/14290674/64190696-3a890880-ce77-11e9-87bd-9a065caf62f5.png)
(note the branch colour is because of issue #785 where unassigned branches get a colour)

The above examples can be see on the Heroku thing:
https://nextstrain-dev.herokuapp.com/community/emmahodcroft/echo30/vp1/all-clin

In `auspice` 1.0, this is not the case:
![image](https://user-images.githubusercontent.com/14290674/64190566-f990f400-ce76-11e9-9d55-d0c5faad6f47.png)

This is the same dataset, but can be seen using 'real' Nextstrain.org:
https://nextstrain.org/community/emmahodcroft/echo30/vp1/all-clin?c=group

---

I don't know if we want to start giving an option to filter to those without a trait? (I can't think of a use-case here.) If so, we should make this clearer. If not, we should get rid of this behaviour. Possibly tied to #785 ?

**Comment by jameshadfield** [comment]
I think this is now fixed 😄 see https://nextstrain-dev.herokuapp.com/community/emmahodcroft/echo30/vp1/all-clin

Please reopen if not.
