### ISSUE TITLE
AA and Nuc Muts Not Showing Up on Branch Mouseover

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#788]
In `auspice` 2.0, AA and nut muts are not showing up in the branch mouseover bubble.

Compare -

'Normal' Nextstrain.org server:
https://nextstrain.org/community/emmahodcroft/echo30/vp1/all-clin
![image](https://user-images.githubusercontent.com/14290674/64247090-63a8a800-cf0e-11e9-8720-084ae546011a.png)

Heroku thing:
https://nextstrain-dev.herokuapp.com/community/emmahodcroft/echo30/vp1/all-clin
![image](https://user-images.githubusercontent.com/14290674/64247126-79b66880-cf0e-11e9-8139-83fc7a2ddcce.png)

Same is true for nucleotide mutations (not shown).

**Comment by jameshadfield** [comment]
Closed in f1fc6d7
