### ISSUE TITLE
`auspice view` Doesn't work for Some V2 JSONS (`dev` does)

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#791]
I haven't had time to look into this in more detail - also, I never use `auspice view` so I'm not familiar with it...

Yesterday in the workshop an advanced user was using `auspice` `v2`. He produced a `v2` JSON via `augur export v2` (possibly notable that he was working from a starting tree rather than from sequences), and it would not display using `auspice view` with the argument where you specify the folder (did not try without this folder). Error was something about `n not defined` in React. 

When he ran `auspice` `v2` using `npm run dev` and copied the JSON into the `data` folder there, it displayed perfectly fine. 

Think there must be some difference between `view` and running in `dev` mode which isn't processing `v2` JSONs properly?

I will try to see if I can recreate this to give more info, when I can, but solving it is almost certainly outside my ability, as I've never looked into this side of `auspice`!

**Comment by jameshadfield** [comment]
> there must be some difference between view and running in dev mode

Yes there is. 

`auspice view` uses a pre-built bundle and is generally much faster. 

`develop` (or `npm run dev` or `node auspice.js develop`) generates a bundle every time (that's the ~10seconds it takes to start up), watches for code changes as you modify the source code, and generally has a lot of nicer features for development. These features come with a speed penalty. It should only be used if you are developing the auspice client.

However, if you have changed the source code (e.g. by switching to the `v2` branch) then you'll have to rebuild the bundle before you can successfully use `auspice view` (or `node auspice.js view`). 

Please reopen if this bug remains after rebuilding the client (e.g. in the auspice directory run `node.js auspice build`)

**Comment by emmahodcroft** [comment]
@rneher is it possible to get in touch with the SIB person and ask him if this fixes it? 

He reinstalled while on `v2` while I was working with him, but perhaps that doesn't re-build. I couldn't replicate his error in `v1`, but possibly he had an earlier build of the `v2` branch - I dunno how long he's been working on this.

**Comment by tsibley** [comment]
> He reinstalled while on `v2` while I was working with him, but perhaps that doesn't re-build.

Yeah, `npm install` only installs deps; it won't rebuild. `npm run build` (or one of the variants James suggests) is required to rebuild.

**Comment by emmahodcroft** [comment]
Ok! Thank you @tsibley, that probably explains it! I think he's happily using `dev` now but can let him know if I see him at the conference again :)
