### ISSUE TITLE
Mis-ordered (partly-reversed?) legends in v2

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#797]
Unexpected flip and mis-ordering of legends for categorical values. May be partly related to commit 5b5ba7b4c5cf632ef2b094eba128b671b9eff863?

Seems to have been a change in order of legend values, most surprisingly a rough reversal of order, changing the look of the tree quite significantly (was this intentional? I find this very surprising!).

Compare the EV-D68 vp1 [live build](https://nextstrain-dev.herokuapp.com/enterovirus/d68/vp1?c=country):
![image](https://user-images.githubusercontent.com/14290674/65772857-5fe9f900-e13b-11e9-8d4c-b1f39bad09d0.png)

With EV-D68 vp1 on [Heroku](https://nextstrain-dev.herokuapp.com/enterovirus/d68/vp1?c=country):
![image](https://user-images.githubusercontent.com/14290674/65772833-55c7fa80-e13b-11e9-90c6-67be21961395.png)

As far as I can remember we've always ordered the other way (USA has always been at the top for me), and the switch is jarring since I've learned to associate colours with countries to some degree (I realise that's user specific and I've spent too much time looking at these trees, but...)

It's also weird because it's not a complete reversal based on counts. Here are the legend order and the corresponding counts for the live build vs Heroku:

Live build |   |   | Heroku |  
-- | -- | -- | -- | --
USA | 373 |   | India | 2
France | 192 |   | Haiti | 1
Japan | 160 |   | Mexico | 2
China | 119 |   | Ireland | 4
Canada | 93 |   | New Zealand | 10
Germany | 89 |   | Gambia | 5
Spain | 84 |   | Tanzania | 1
Italy | 72 |   | Sweden | 62
Hong Kong | 71 |   | Kenya | 11
Sweden | 62 |   | Finland | 2
Senegal | 54 |   | Belgium | 10
Netherlands | 48 |   | Netherlands | 48
Taiwan | 47 |   | Switzerland | 6
Philippines | 99 |   | Senegal | 54
United Kingdom | 32 |   | United Kingdom | 32
Denmark | 20 |   | Italy | 72
Malaysia | 12 |   | Canada | 93
Vietnam | 11 |   | Denmark | 20
Kenya | 11 |   | Philippines | 99
Belgium | 10 |   | France | 192
New Zealand | 10 |   | Spain | 84
South Africa | 8 |   | Germany | 89
Thailand | 8 |   | Malaysia | 12
Switzerland | 6 |   | Hong Kong | 71
Gambia | 5 |   | Vietnam | 11
Ireland | 4 |   | Thailand | 8
Finland | 2 |   | Japan | 160
Mexico | 2 |   | China | 119
India | 2 |   | Taiwan | 47
Tanzania | 1 |   | South Africa | 8
Haiti | 1 |   | USA | 373

As you can see, they are kind of reversed on Heroku, but not exactly!

If there are only two options they are more reliably reversed (change color-by to `sex` and `symptom` in live and Heroku to observe).

I would vote to go back to original ordering (most counts being first in legend), as I think people who are used to looking at particular trees will be used to seeing this, and, particularly if they are not paying attention that colours have swapped, could really throw you off.

**Comment by jameshadfield** [comment]
I think this bug has been fixed but perhaps the dev-heroku server hadn't been updated to reflect the changes. The d68 dataset looks good right now 🎉 

![image](https://user-images.githubusercontent.com/8350992/66020825-f2780700-e544-11e9-836b-02255341376c.png)

**Comment by emmahodcroft** [comment]
Great, thanks! 
Weirdly I can't get it to show correctly on my Chrome, even after clearing cache and hard reload. But it looks right on Richard's, and in Firefox, so my Chrome just can't let go of the past, I guess...!
