### ISSUE TITLE
Date Slider should handle 'nothing shown' case

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#8]
![image](https://cloud.githubusercontent.com/assets/1770265/17755956/e0bed17e-6491-11e6-83a4-cf6bfcf648c7.png)

**Comment by trvrb** [comment]
This should end up with a tree with all the branches, but no tips visible, rather than the current blank page.

**Comment by trvrb** [comment]
Current `master` is working now for this. Leaves tree with all branches no tips drawn.
