### ISSUE TITLE
frequencies in community builds

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#812]
I just encountered a problem loading v1 community analyses with frequencies with v2 auspice. this one works fine in v1

https://nextstrain.org/community/rivm-syso/Dutch-NIC-EMC-RIVM/h3n2_ha_2y

but errors out with 'frequency loading failed' here:

https://nextstrain-dev.herokuapp.com/community/rivm-syso/Dutch-NIC-EMC-RIVM/h3n2/ha/2y

the problem seems to be that auspice attempts to fetch:

https://raw.githubusercontent.com/rivm-syso/Dutch-NIC-EMC-RIVM/master/auspice/community_rivm-syso_Dutch-NIC-EMC-RIVM_h3n2_ha_2y_tip-frequencies.json 

that it seems to have gotten confused with where to insert an underscore and where a slash and fantasized a 'community' into the url. 

@jameshadfield: this probably happens when assembling the fetch path, right?

**Comment by jameshadfield** [comment]
@rneher now fixed -- this was an issue with the nextstrain.org server. nextstrain-dev.herokuapp.com is now running off nextstrain.org's "upgrade-to-auspice-v2" branch in preparation for a v2 launch which has fixed this bug 😄
