### ISSUE TITLE
is font-awesome actually used

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#828]
The font-awesome CSS has been part of auspice from [the very beginning](https://github.com/nextstrain/auspice/commit/6b9204f7bdcb49d963f9721930e0fc81e196ca02#diff-eacf331f0ffc35d4b482f1d15a887d3b), and thanks to #826 is now bundled as part of the auspice distribution. 

I don't believe we actually use these styles in auspice & they should therefore be removed. Needs double checking as there may be something i've missed here. 

_In general, the styling in auspice is too complicated and reflects a project which has grown over the years without a prescribed way of handling styles. But this is a separate issue_ 😉

**Comment by trvrb** [comment]
@jameshadfield: The first thing that comes to mind is: https://github.com/nextstrain/auspice/blob/master/src/components/framework/footer.js#L381. I'll look for other uses though.

**Comment by jameshadfield** [comment]
Ahh yes, we do use it. I've been a fan of `react-icons` in other projects which allows you to do things like
```js
import { ICON_NAME } from "react-icons/fa";
```
Given that we are using it, this issue is very low priority.

**Comment by jameshadfield** [comment]
Closing as this is listed in #702
