### ISSUE TITLE
document how to use `auspice view` serve on heroku

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#829]
`auspice view` no longer works when used as the server on a heroku app, with this error in the heroku log:
```
Web process failed to bind to $PORT within 60 seconds of launch
```

This is a reversion from previous behavior as a result of https://github.com/nextstrain/auspice/commit/16341e53627bbc119f31fbece6e34556cdc0c5bd. Note that `$HOST` wasn't set on the heroku app, and doesn't appear to have a default.

My short term fix is to revert the commit (tested, working). @tsibley is this ok, or is there another solution you can implement in the short term? (It may be as simple as setting `$HOST` on the heroku app.)

**Comment by tsibley** [comment]
I would prefer not to revert that commit (listening on all network interfaces by default is not great), but instead set `HOST` to `0.0.0.0` in the Heroku app's configuration.

**Comment by jameshadfield** [comment]
Cool, that works. Thanks!

**Comment by jameshadfield** [comment]
Using `auspice view` as the web process on heroku apps is reasonably common. To do this, the heroku config variable `HOST` must be set to `0.0.0.0` (`localhost` doesn't work). This needs to be documented.
