### ISSUE TITLE
Auspice contributing docs contain version information

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/auspice#832]
The contributing information in `docs-src/docs/contributing/overview.md` contains information about Releasing New Versions of Auspice. 

It seems out of place. Namely, we wouldn't expect or want third-party contributors to release new Auspice versions. Can this paragraph find a better place to live?

Also -- my goal is to use most of this page (minus "Releasing new versions...") for the content of a new CONTRIBUTING.md.

**Comment by jameshadfield** [comment]
Agree -- release instructions should be moved to github.com/nextstrain/documentation/

> my goal is to [make] a new CONTRIBUTING.md

That'd be great, but please make sure it also appears in the github-pages documentation. Have a look at how the CHANGELOG.md also appears in the built documentation, you may want to do it that way.

**Comment by kairstenfay** [comment]
Hey James, I'm having trouble seeing how CONTRIBUTING.md is converted to HTML. Could you please point me more specifically to the script that does that?

**Comment by kairstenfay** [comment]
Or rather, I'm having trouble seeing where CONTRIBUTING.md gets pulled into the built docs folder under `/releases`

**Comment by jameshadfield** [comment]
Closed by #833
