### ISSUE TITLE
Tree flickers oddly during animation

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/auspice#848]
Looks like maybe an edge case for small trees, where the default label rendering logic is creating an odd flicker.

![bug](https://user-images.githubusercontent.com/12618847/72946737-b0154880-3d34-11ea-807b-4ac51ba157d1.gif)

**Comment by trvrb** [comment]
Thanks @sidneymbell! This is indeed quite jarring: https://nextstrain.org/ncov?animate=2019-11-25,2020-02-01,0,0,30000. I think the best way to deal with this will be to hide tip labels when animating. I don't think we did testing previously with small trees + animation.
