### ISSUE TITLE
Screen blanks to white after loading for flu builds on live site

### ISSUE THREAD

**Issue by huddlej** [nextstrain/auspice#854]
There is a bug with auspice in the live Nextstrain site where after loading the 2y flu build (https://nextstrain.org/flu/seasonal/h3n2/ha/2y) and hovering over the tree, the page goes blank.

The console view shows the following errors when the screen blanks:

![image](https://user-images.githubusercontent.com/85372/73223179-1fff4680-411a-11ea-82d4-a3bdab686088.png)

I recreated this problem on my laptop with auspice 2.3.4 and found that the screen blanks at the same time the debugging message below about getting available datasets and narratives is printed.

```
GET DATASET query received: prefix=/flu/seasonal/h3n2/ha/2y
GET DATASET query received: prefix=/flu/seasonal/h3n2/ha/2y&type=tip-frequencies
GET AVAILABLE returning locally available datasets & narratives
```

I downgraded stepwise to previous versions of auspice and found the issue starts with v2.3.0. This bug affects the other flu segments and resolutions besides HA and 2y. The issue does not appear to affect other pathogen builds (at least not Zika, measles, or Ebola).

**Comment by trvrb** [comment]
Thanks John! Looks related to the recent tooltip work. Does rolling back to 2.3.2 resolve?

**Comment by joverlee521** [comment]
My local testing shows it's because of this line: https://github.com/nextstrain/auspice/blame/master/src/components/tree/infoPanels/hover.js#L272

I'll push up a branch shortly that _should_ resolve this.
