### ISSUE TITLE
Regression rate calculation is wrong for mutation-scaled divergence

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#858]
Please see https://github.com/nextstrain/ncov/issues/17.

Given that we don't specify in the Auspice JSON what units divergence has, my best idea would be to:

1. For the time being remove regression rate calculation from Auspice.
2. Have `augur refine` include subs rate estimate in `branch-lengths.json`.
3. Package up this rate estimate when running `augur export`
4. Use this rate estimate in Auspice rather than running a regression

This should be more accurate as well as the rate estimate produced by TreeTime is not just a regression.

**Comment by jameshadfield** [comment]
This is good long-term (& treetime estimates would be better), but requires rerunning every single dataset. Short term (and for JSONs without this key) would just removing the "subs per site per year" be enough? Means people have to interpret themselves the units, which isn't great, but maintaining the number is important info.

**Comment by trvrb** [comment]
That's a good point James. I agree with this. So, this would be:

1. For the time swap "subs per site per year" to "per year"
2. Have augur refine include subs rate estimate in `branch-lengths.json`
3. Package up this rate estimate when running `augur export`
4. If Auspice JSON has the appropriate key, use this rate estimate in Auspice rather than running a regression, if not, continue to run regression

2-4 can happen down the road at our leisure.

**Comment by emmahodcroft** [comment]
Could we auto-detect (or intelligently guess) the units and thus what to display ("subs per genome per year" or "subs per site per year") in Auspice? 
For the moment I imagine something rough and ready like "do the units go higher than 2" would work. No other dataset we display will be anything like the subs/genome we are showing for nCov.

**Comment by trvrb** [comment]
That's a great idea Emma.
