### ISSUE TITLE
"END OF NARRATIVE" page should have its own pagination dot

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/auspice#872]
Right now in 2019-ncov narrative (currently https://nextstrain.org/narratives/ncov/sit-rep/2020-01-30) one can jump to the "Detailed scientific credit" page (which is the one before last), by clicking on the *last* pagination dot icon.

However, there is no way to jump to "END OF NARRATIVE" page.

I believe it would be a better UX if we'd allow that. Thoughts?

**Comment by tsibley** [comment]
I agree. I noticed that the "end of narrative" page also doesn't get an updated `?n=…` URL parameter.

**Comment by joachimschmidt557** [comment]
I also agree that the "end of narrative" page should be counted as an actual page. This would fix the issue that scrolling up from the "end of narrative" page goes to the second-last page, not the last page. I will work on a PR for this.
