### ISSUE TITLE
Non-string tree labels do not work when loading from URL queries

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#888]
For instance, a label such as `clade=3` doesn't work when loading via URL query (which includes navigating between pages in a narrative). I believe this is due to URL queries always being strings, where `"3"=== 3` is false. My proposed solution is to treat all branch label values as strings.

**Comment by TAM360** [comment]
Hey @jameshadfield  I would like to work on this issue. Can you explain the exact steps in order to reproduce this bug?

**Comment by jameshadfield** [comment]
Absolutely -- I've been meaning to write a small example for this. 

The following dataset https://nextstrain.org/staging/test/tree-labels-2020-05-26 (JSON [here](https://s3.amazonaws.com/nextstrain-staging/test_tree-labels-2020-05-26.json)) has two branches  with labels (`"string-value"` and `42`). Clicking on either of those branches zooms the tree & updates the URL query to indicate we're zoomed to a branch with the label. These resulting URLs are
* https://nextstrain.org/staging/test/tree-labels-2020-05-26?label=test:string-value
* https://nextstrain.org/staging/test/tree-labels-2020-05-26?label=test:42

However only the first URL can correctly be used to restore state, with the second URL resulting in the following error
![image](https://user-images.githubusercontent.com/8350992/82857013-d279d580-9f63-11ea-9d16-472424918074.png)

**Comment by tsibley** [comment]
@jameshadfield Seems like the JSON Schema wants an update here as well to enforce those labels are strings in the JSON? I don't know if there are backwards incompat considerations here, though. And Auspice may still want to explicitly stringify label values for backwards compat.

**Comment by TAM360** [comment]
@jameshadfield So I was going through the code-base & found it a bit difficult to navigate. Is there any document available which explains the structure in brief manner. I want to get maximum understanding before I start working on this issue.

**Comment by jameshadfield** [comment]
@TAM360 unfortunately there's not. It would be nice to have. This issue turned out to be very simple to fix (essentially a one line change). If you let me know what aspects of auspice best suit your background I can recommend another issue and try to provide some background to help as needed.

**Comment by TAM360** [comment]
@jameshadfield I can't pin point the exact aspects of auspice I am comfortable with. I guess as long as it has a **good first issue** label, I'll be fine working on it. I also think that having a domain knowledge would be helpful too. So if I can get help in this aspect too, that would be great.
