### ISSUE TITLE
single-deme zoom level

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#889]
Auspice (as of 2.5.0) zooms the map to the boundaries of the visible data (unless a user has interacted with the map). This woks great most of the time, but for data selections with only 1 deme it's zoomed too much. 

E.g. https://nextstrain.org/zika?f_country=Canada shows:
![image](https://user-images.githubusercontent.com/8350992/73979547-3b2c4a80-4993-11ea-9314-2e18afbd857d.png)

But this would be better:
![image](https://user-images.githubusercontent.com/8350992/73979578-4bdcc080-4993-11ea-8686-59cbef5e3715.png)

We need to treat different geographic resolutions differently -- e.g. if you select a city it should be zoomed in more than the country. This is complicated by different demes (e.g. countries) being vastly different sizes. 

---

Auspice could have hardcoded defaults for different resolutions (country, division) if none are specified and one could store a max-zoom (or similar) within the JSON per-geo-resolution (e.g. at https://github.com/nextstrain/augur/blob/master/augur/data/schema-export-v2.json#L120). But this would look very different for, say, canada vs USVI, so perhaps isn't the ideal solution.

**Comment by trvrb** [comment]
Thanks for putting together the issue James. I think my suggestion to dynamically figure out this zoom level would be to calculate bounds on all demes and use this to guess a max zoom level. If we have flu in Basel, the overall bounds will be narrow, while overall bounds for Zika will be wide. This would be pretty heuristic however.

**Comment by trvrb** [comment]
But I guess selecting city for current nCoV we'd want closer zoom than selecting country. I agree with your proposal James. Just have a small handful of hardcoded geo resolutions.

**Comment by jameshadfield** [comment]
Closed by #891
