### ISSUE TITLE
Blend branch coloring

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#896]
Right now, a branch inherits tip color as shown here:

![Screen Shot 2020-02-13 at 4 13 15 PM](https://user-images.githubusercontent.com/1176109/74489925-c158fd00-4e7b-11ea-9d77-c1e02ceff83f.png)

However, this color is only really true at the right-most edge of the branch. Ie each of these tips is definitely in their place of sampling at the time of sampling but as we go back things should get more uncertain. In fact the left-most edge of the branch should be the same gray as the right-most edge of the parent branch. This should appear as a continuous process.

I actually think it shouldn't be too difficult to have a SVG gradient for each branch line (https://stackoverflow.com/questions/42874203/linear-gradient-across-svg-line). The gradient end points would be chosen as:
- right: current branch color
- left: parent branch color

I suspect this will result in a more natural, interpretable visualization.

**Comment by jameshadfield** [comment]
Yes -- the way we draw branches can often be misleading like this (see discussion on https://github.com/nextstrain/auspice/issues/200 for our thoughts 2 years ago!). SVG computation / rendering is a sizeable bottleneck in animations, so perhaps we'd have to fall-back to the current method if this slows things down, but I don't see a problem there. [Seems to be pretty simple](http://bl.ocks.org/pnavarrc/20950640812489f13246) to implement in d3.

**Comment by trvrb** [comment]
I didn't think of this animation issue. Thanks James!

**Comment by jameshadfield** [comment]
Update -- this issue has a partial solution, but is in need of further work to complete, as detailed in https://github.com/nextstrain/auspice/pull/897#issuecomment-588014096. Contributions on top of this PR #897 are very welcome -- please leave a comment there if you start work on it!

**Comment by cpsandbox** [comment]
Contributed pr #947 for this

**Comment by cpsandbox** [comment]
updated pr #947

**Comment by jameshadfield** [comment]
closed by the merge of #947
