### ISSUE TITLE
How do we show nodes with undefined dates in various circumstances?

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#9]
Richard suggests: "either show but grey, or hide as soon as the date range doesn't include everything."

Currently it is: 

![image](https://cloud.githubusercontent.com/assets/1770265/17801701/6c8ca708-65a0-11e6-944a-be1e75d18691.png)

And this may be a different decision for different kinds of filters.

**Comment by trvrb** [comment]
This general issue should arise in geography as well (and possibly other situations). For geography, tips will have different levels of precision as well. One tip could be "Bahia" state and another tip could be "Brazil". If we filter to "Brazil" both tips should remain, but if we filter to "Bahia" one the first should remain.

This is analogous to having two tips, one that is "2016-04-01" and another that's "2016-XX-XX". If we filter to an end date of "2017-01-01" then both should remain and if we filter to an end date of "2016-06-01" then just the first should remain.

For dates this could be solved by having Augur make two attributes per node: `num_date_lower` and `num_date_upper`. A precise date like "2016-04-01" will have both these attributes be the same thing. Dates like "2016-XX-XX" will have the attributes be different things.

Then, when deciding whether to draw a node can compare the upper end of the date slider to `num_date_lower` and the lower end of the date slider to `num_date_upper`.

**Comment by trvrb** [comment]
Just realizing, we're need an additional attribute for `num_date` that would be used as the x-coordinate when doing a time tree.

So, filter based off of precisions and display based on point estimate.
