### ISSUE TITLE
Add legend open/close state to URL query

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#900]
Will be very beneficial to iframe embedding and narratives

**Comment by emmahodcroft** [comment]
@jameshadfield you are a mindreader, I had a rant about this just the other day and it's on my 'auspice wish list' door, but I never got around to making an issue 😆

**Comment by jameshadfield** [comment]
The best example to follow for this would be to follow how we currently store the state for being able to control the sidebar open/closed state via the URL query (see https://github.com/nextstrain/auspice/search?q=sidebarOpen&unscoped_q=sidebarOpen). Please note that it's not applicable for this to be set via the dataset JSON. 

The default state for the legend open/closed should be set as it currently is, and any user-interaction will result in a URL query (via the redux middleware). For instance `?legend=open` or `?legend=closed`.

**Comment by ncallaway** [comment]
I'm starting work on this now, I expect I'll be able to have a PR for you shortly.

**Comment by jameshadfield** [comment]
Closed by #923
