### ISSUE TITLE
Missing `annotations` field causes auspice to crash on v1 JSONs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#906]
V1 meta JSONs missing the `annotations` key do not work in auspice. The v1-v2 conversion code should automatically inject

```json
  "annotations": {
    "nuc": {}
  },
```
in this case. (Note that these do fail augur validation, but we have had multiple problems from this and the fix is so easy that we should do it.)

Should also test if this is essential on v2 JSONs.

**Comment by HeeTatt** [comment]
In the  `examples` directory, the v1 files` minimal_v1_meta.json` and `minimal_v1_tree.json` seem to be displayed correctly without containing the `annotations` key. 
Is there an example of a problematic v1 file to look at?

**Comment by jameshadfield** [comment]
@HeeTatt you're correct -- this bug is no longer present! 🎉
