### ISSUE TITLE
Tip labels should only count visible tips

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#915]
## Background: 

Currently we only display tip labels when the total number of tips in-view is below a certain threshold. This prevents hundreds of tips being displayed on big trees, and allows small trees, or zoomed in sections of trees, to display labels. 

In auspice we refer to nodes / branches which are displayed on the screen as "in view". These tips may be "unselected" (e.g. filtering is applied), so that they are rendered but appear skeletal (very thin lines). This is referred to in the code to whether a tip is visible or not. 

(Potentially see #237 for further information)

### This issue

The hardcoded # of branches selected should only count "visibile" tips which are also in-view. For instance, filtering a large tree (many "in-view" nodes) to only have a few tips visible (e.g. select USA on the nCoV tree) should result in tip labels being displayed.

**Comment by frogsquire** [comment]
@jameshadfield I'd like to take this.

The fix, I believe, is in labels.js, line 14:

`const inViewTerminalNodes = this.nodes
    .filter((d) => d.terminal)
    .filter((d) => d.inView);`

should be

`const inViewTerminalNodes = this.nodes
    .filter((d) => d.terminal)
    .filter((d) => d.inView)
    .filter((d) => d.visibility == NODE_VISIBLE);`

As I understand it, this will make the number of nodes being checked to determine whether to show the tips calculate based only on nodes which are fully "visible", not nodes which are visible, but unselected.

If this looks acceptable to you, I will make a PR. (Normally I would just do so, but as this is my first issue, wanted to check in first.)
