### ISSUE TITLE
Color by legend is broken for numeric traits

### ISSUE THREAD

**Issue by huddlej** [nextstrain/auspice#926]
Selecting a color by option that has numerical values produces an error that "something has gone wrong". For example, selecting "Age" in the novel coronavirus build (https://nextstrain.org/ncov?c=age) produces this output:

![image](https://user-images.githubusercontent.com/85372/76122217-6ada6c80-5faa-11ea-8724-6896e34da9f3.png)

Using git bisect, I tracked this error down to the [truncation of legend labels using the substring method](https://github.com/nextstrain/auspice/commit/07d94a4434fec69014bf6f5a828d37d266d4d469#diff-caeef2e2c6f35f6443be8162ba918ba8R38).

I'm not familiar enough with React to implement a solution here, but it seems like we need to check the type of the label prior to applying substring.

**Comment by joverlee521** [comment]
Thanks for tracking this down! I think we can throw [`String()`](https://www.w3schools.com/jsref/jsref_string.asp) around the label to convert everything to a string before calling `substring`

**Comment by tsibley** [comment]
Yeah, this is a JavaScript type thing. Strings have a substring method, but Numbers don't. I expect a forced conversion to string is needed. There are many ways to format a Number, but `label + ""` might be enough.

**Comment by huddlej** [comment]
Ok, I actually was able to fix the issue with an explicit check for type (5f4a6d7), but if y'all prefer casting to string for everything, that's fine, too.

**Comment by tsibley** [comment]
Thanks! I think that type check is fine. The `label` will be cast to a string anyway as part of the template interpolation, but I think it does make more sense not to apply character-length limits to a numeric value.
