### ISSUE TITLE
Sidebar should provide data filter capability like URL query options do

### ISSUE THREAD

**Issue by brianpardy** [nextstrain/auspice#938]
Currently the only apparent way to filter displayed data in an auspice dataset is by passing URL query options.

The sidebar in auspice should provide the capability to filter the displayed/highlighted data in the same way as the "f_<name>" URL query option provides.

A potential way to implement this would be a 'Filter' section at the bottom of the sidebar, with a drop down menu to select the <name> (region, country, sex, host, and so on), to be filtered, and a text field to enter the filter text, working somewhat like the existing 'Color By' section.

**Comment by emmahodcroft** [comment]
Hi Brian,
Thanks for your feedback - and I'm sorry you've been struggling with URL filter queries this long! 
If you scroll down to the bottom of the main page (not the sidebar), we actually do have text you can select - for country, location, and division (and more), to filter the data. 
Here's a screenshot:
![image](https://user-images.githubusercontent.com/14290674/76433752-0c9bf800-63b5-11ea-80a9-b2109499448e.png)

I hope that helps!

**Comment by brianpardy** [comment]
I keep forgetting that is there at the bottom of the page!  That is more than sufficient, I will close this issue shortly if you don't. Thank you very much!
