### ISSUE TITLE
Add label to x-axis in tree panel

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#941]
Currently the "Phylogeny" panel doesn't have a label for the x-axis:

<img width="1020" alt="x-axis" src="https://user-images.githubusercontent.com/1176109/76491378-c2ce0480-63ea-11ea-8610-682a41c0b5a9.png">

This lack of labeling is hugely confusing to outsiders and everyone knows this is poor data viz practice. Let's fix this. I recommend:

* "Date" if showing a tree with `mu=num_date`.
* "Mutations" if showing a tree with `m=div` and branch lengths are big enough to indicate this this measures substitutions rather than substitutions per site.
* "Divergence" if showing a tree with `m=div` and branch lengths are small enough to indicate this this measures substitutions per site rather than substitutions.

Logic to test between Substitutions and Substitutions per site is here: https://github.com/nextstrain/auspice/commit/80915fd36f1a744907054197dc00f08e9ec86d6b

I wouldn't worry about this labeling for "radial" or "unrooted" views.

**Comment by huddlej** [comment]
Closed by #942
