### ISSUE TITLE
Language support for auspice

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#944]
There is currently no language support in Nextstrain. This issue is cross cutting between auspice & nextstrain.org, but is detailed here for both.

Please see https://github.com/nextstrain/nextstrain.org/issues/130 for a description of this issue, as it applies to both codebases. Please also see PR https://github.com/nextstrain/auspice/pull/892 for a potential start to this work.

**Comment by huddlej** [comment]
Updated title here to disambiguate this issue from the broader nextstrain.org issue of the same title when viewing in project boards.

**Comment by mapmeld** [comment]
I'm open to other ideas on which library / how to implement

What would be helpful from NextStrain internal team would be a) **define an initial scope** for this issue, such as "the narrative UI should have translation options" which then the NextStrain deployment can hook into; or "the /ncov landing page (being super-popular) should be all translatable". 

Then b) start collecting volunteer translators in the wiki - this was super-helpful for translating an open source project I worked on before - [MetaMask](https://twitter.com/metamask_io/status/973627800103018496). You already have many contacts with domain knowledge already, so they come first, but if you have a call for translators I think it will expand the scope even more.

**Comment by mapmeld** [comment]
I'm open to other ideas on which library / how to implement

What would be helpful from NextStrain internal team would be a) **define an initial scope** for this issue, such as "the narrative UI should have translation options" which then the NextStrain deployment can hook into; or "the /ncov landing page (being super-popular) should be all translatable". 

Then b) start collecting volunteer translators in a wiki or Google Form - this was super-helpful for translating an open source project I worked on before - [MetaMask](https://twitter.com/metamask_io/status/973627800103018496). You already have many contacts with domain knowledge already, so they come first, but if you have a call for translators I think it will expand the scope even more.

**Comment by crwilcox** [comment]
I have started work on https://github.com/nextstrain/auspice/compare/master...crwilcox:loc as a prototype. I am still to do some work to arrange where translations live, but this is functional now.
