### ISSUE TITLE
Map pan is broken in narratives

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#945]
This issue occurs in narratives, seemingly when changing between map-only display -> map+tree display. It causes the map to reposition itself incorrectly. Note that this happens after a 1000 or 1500ms delay implying that a `setTimeout` is involved. 

![Mar-13-2020 19-34-46](https://user-images.githubusercontent.com/8350992/76595923-c46e0880-6561-11ea-992a-9c44a0ca07f6.gif)

Steps to reproduce:
1. [Install auspice from source](https://nextstrain.github.io/auspice/introduction/install#installing-from-source)
2. Obtain hCoV-19 datasets & narratives via cloning github.com/nextstrain/ncov
3. Run auspice via `auspice develop --datasetDir <ncov/auspice> --narrativeDir <ncov/narratives>`

Run the latest narrative (currently unpublicised) and switch between http://localhost:4000/narratives/ncov/sit-rep/2020-03-13?n=3 and the following slide.

**Comment by cassiawag** [comment]
Sorry accidentally pushed a button!

**Comment by cpsandbox** [comment]
Is it possible to get access to the data required to work on this?

**Comment by jameshadfield** [comment]
PSA: This issue now has a PR thanks to @mapmeld. For some reason I can't assign him!

> @cpsandbox Is it possible to get access to the data required to work on this? 

The 3 "Steps to reproduce" will give you access to the data. Please let me know if something didn't work!
