### ISSUE TITLE
Add support to app for i18n/l10n matter.

### ISSUE THREAD

**Issue by crwilcox** [nextstrain/auspice#952]
In talking with @colinmegill it seems localization and internationalization for this app would be desired. I am starting on a branch to add this support so translators can add translations for languages.

**Comment by mapmeld** [comment]
Check out some prior discussion on GitHub issue #944, we were leaning towards using i18next

**Comment by crwilcox** [comment]
Perfect! That is what my prototype uses :)

**Comment by jameshadfield** [comment]
Hi @crwilcox -- this sounds great, thankyou!. I've detailed the background & where we want to go in reasonable depth at https://github.com/nextstrain/nextstrain.org/issues/130 (which talks about auspice as well). It's important that our solution fits well between the two repos as together they make up what's seen at nextstrain.org
