### ISSUE TITLE
Make narratives work with R-->L languages

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/auspice#954]
To broaden access to reports on hCov-19, we are translating narratives into Farsi and Arabic, both languages read from R-->L. Currently, narratives do not handle this well, see for example: https://nextstrain.org/narratives/ncov/sit-rep/fa/2020-03-13.

I'm imagining a right-to-left flag that right aligns all text, headers, bullet points, and punctuation. For example, a period would be on the left-side of the final word in a sentence. Bullet points would be on the right side of the screen with the text just to the left of the bullet point.

In an ideal world, this flag would also flip the entire report, so what's on the L-side of the screen would be on the R and vice a versa. Flipping the report would likely be hard, might take a bit of work, and is much lower priority than R-aligning the text.

**Comment by tsibley** [comment]
The predominant direction of the text likely needs to be set with a [dir](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) attribute on the elements containing narrative markdown content. I believe `dir="auto"` should generally Just Work, and it does if I quickly add it to a narrative slide in the inspector, but `dir="rtl"` can be explicitly specified if necessary.

As a quick workaround, the Markdown could include `<div dir="rtl">…</div>` around each slide, which I think would work if `dir` was added to [our allowed attributes](https://github.com/nextstrain/auspice/blob/1274e88c9a92e648fd013c14d24eb3a5d70c92b8/src/components/narrative/MainDisplayMarkdown.js#L137).

**Comment by tsibley** [comment]
An example of me quickly adding `dir=auto` to the sidebar and main content for the narrative linked above:

![image](https://user-images.githubusercontent.com/79913/76810594-dd69fa00-67ab-11ea-9301-8d312c216ce8.png)

**Comment by mhrimaz** [comment]
> An example of me quickly adding `dir=auto` to the sidebar and main content for the narrative linked above:
> 
> ![image](https://user-images.githubusercontent.com/79913/76810594-dd69fa00-67ab-11ea-9301-8d312c216ce8.png)
> 


For first version I used `<p dir="rtl"> </p>`  inside the markdowns. However it only works for regular paragraphs.
The first image is the exact output that we are looking for. Though, I don't know where should I apply your solution.

**Comment by mg878** [comment]
@cassiawag looks like this link is no longer working for editing the 13-03 report:
https://github.com/nextstrain/ncov/blob/sit-rep_fa/narratives/ncov_sit-rep_fa_2020-03-13.md
is there somewhere we can apply the solutions and preview them on the website? thanks
I @mhrimaz  here for him to follow up on this.

**Comment by cassiawag** [comment]
@mg878, one option is to re-create a sit-rep_fa branch, which you can do locally and then push up to master for preview.

A better option is to install Auspice locally, and then you'll be able to preview and trouble shoot narratives locally in addition to modifying the Auspice build (which I think is what @trs is referring to by adding it as an allowed attribute). Please see the [Auspice docs](https://nextstrain.github.io/auspice/) to install.

**Comment by tsibley** [comment]
Auspice should now do the right thing for narratives, but we need to get it released and then deployed to nextstrain.org before it'll do the right thing there.

**Comment by mg878** [comment]
Just checking the preview for this:
https://nextstrain.org/community/narratives/nextstrain/ncov@background_fa/trees-background/fa/?n=1

and the problem is still not resolved...
@tsibley when you said you have to get it released and deployed to nextstrain.org, when is that going to happen? thanks!

**Comment by jameshadfield** [comment]
> when is that going to happen

Today

**Comment by jameshadfield** [comment]
Released & nextstrain.org updated 👍
