### ISSUE TITLE
Allow scrolling within a narrative

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#956]
When viewing narratives in auspice in non-mobile view, the text content of the "narrative sidebar" cannot overflow the available space (any overflow is hidden). This is best explained by viewing a narrative locally at a small screen resolution -- the content in the "narrative sidebar" is too big for the available space but isn't allowed to scroll and is therefore un-viewable.

![narrative_overflow](https://user-images.githubusercontent.com/8350992/76817765-a4dc2600-6868-11ea-856b-dafa9ae3008b.png)

The sidebar content is rendered via [this code](https://github.com/nextstrain/auspice/blob/master/src/components/narrative/index.js#L178). 

My intention for the "narrative sidebar" is that both scroll actions and clicking on the chevrons can move to the surrounding slides. In the case that the content overflows, scrolling should bring it into view rather than changing the slide shown. Moving to the surrounding slides via scroll actions should only happen after the content of the current slide has been fully exposed. 

Please see https://github.com/nextstrain/auspice for how to get auspice installed locally  (from source) with local datasets & narratives. The above example is then viewable via http://localhost:4000/narratives/ncov/sit-rep/2020-03-13?n=3.

**Comment by jameshadfield** [comment]
This issue now has a PR (#959)

**Comment by tsibley** [comment]
@jameshadfield 

> My intention for the "narrative sidebar" is that both scroll actions and clicking on the chevrons can move to the surrounding slides. In the case that the content overflows, scrolling should bring it into view rather than changing the slide shown. Moving to the surrounding slides via scroll actions should only happen after the content of the current slide has been fully exposed.

Have you thought about having a continuous scroll instead of slide-based paging?

**Comment by jameshadfield** [comment]
> Have you thought about having a continuous scroll instead of slide-based paging?

Yes - this was considered during the original design implementation and then more recently with the mobile implementation. Happy for it to be reconsidered in a future implementation.

Closed by #959
