### ISSUE TITLE
Make legend collapsible

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#97]

**Comment by trvrb** [comment]
I'm not sure a collapsible legend is really important. Better layout so legend doesn't obscure tree (especially in mobile) seems smarter.

**Comment by trvrb** [comment]
After working on layout this week, I think I actually much prefer the idea of automatically collapsing the legend when in mobile (browser width less than some value) to the proposal of padding vertical space. This would fix issue #126.
