### ISSUE TITLE
Broken links to JSON schemas from docs

### ISSUE THREAD

**Issue by tseemann** [nextstrain/auspice#971]
https://nextstrain.github.io/auspice/introduction/how-to-run

The links on that page to schemas are 404 ERROR

**Comment by joachimschmidt557** [comment]
This would be solved by https://github.com/nextstrain/auspice/pull/967

**Comment by jameshadfield** [comment]
Closed by #967 -- thanks both!

**Comment by jameshadfield** [comment]
(Will close once I rebuild & push the docs)

**Comment by willingc** [comment]
@jameshadfield Did https://github.com/nextstrain/auspice/commit/d892306bc39af9ab3f5ae14af076efb6421d3d9a close this issue?

cc / @crwilcox Ping me if you need anything doc related.

**Comment by jameshadfield** [comment]
Ahh yes, the docs were rebuilt but the I didn't re-close this issue. Thanks!

**Comment by jameshadfield** [comment]
@willingc your general thoughts on where to go with nextstrain docs (https://github.com/nextstrain/nextstrain.org/issues/127) would be great! I think we need to make a general plan here before soliciting detailed documentation contributions.
