### ISSUE TITLE
Legend ordering is not correct for traits without a supplied colour scale

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#973]
For traits ("colorings") in a dataset which do not have a color-scale provided by the dataset JSON, auspice will generate a colour scale for them. One such trait in the current ncov data is "Exposure History". 

The ordering of the values are reversed in Firefox compared with Chrome (not tested on other browsers):

Firefox (MacOS):
![image](https://user-images.githubusercontent.com/8350992/77261977-4fd06200-6cf7-11ea-95ae-07386ce79c17.png)

Chrome (MacOS):
<img width="267" alt="image" src="https://user-images.githubusercontent.com/8350992/77261983-552dac80-6cf7-11ea-8677-0e786cd96324.png">

The ordering is via [this code](https://github.com/nextstrain/auspice/blob/master/src/util/colorScale.js#L43) and should start (dark blue colours) with the value with the most occurrences in the data and end with the value with the fewest occurrences (red colours). This means that neither of the browsers are correct!

This bug was first noticed in https://github.com/nextstrain/ncov/pull/239.

**Comment by dlowder-salesforce** [comment]
I can have a crack at this

**Comment by jameshadfield** [comment]
Brilliant! Thanks Douglas

**Comment by dlowder-salesforce** [comment]
Interesting, the ordering function never gets hit in the debugger....

**Comment by dlowder-salesforce** [comment]
@jameshadfield which dataset would be good for reproducing this issue?

**Comment by jameshadfield** [comment]
ncov dataset coloured by "exposure history" should be enough to reproduce and fix I think (that's the Dataset behind the screenshots above). You can make the ncov JSON available locally via `curl http://data.nextstrain.org/ncov.json --compressed -o data/ncov.json`

**Comment by dlowder-salesforce** [comment]
Hopefully this is correct then?

![Screen Shot 2020-03-23 at 5 36 15 PM](https://user-images.githubusercontent.com/6577821/77376196-f4b96200-6d2c-11ea-9c33-0ab0e68431fa.png)

**Comment by jameshadfield** [comment]
That looks much better! For keys that have the same tip counts (e.g. USA, Hong Kong, South Korea + others all have n=1) could we sort alphabetically so that it's stable between datasets please.
