### ISSUE TITLE
[i18n] Translate Auspice to Spanish

### ISSUE THREAD

**Issue by crwilcox** [nextstrain/auspice#983]
Following the guide at:
https://github.com/nextstrain/auspice/blob/master/DEV_DOCS.md#contributing-to-internationalization-and-localization-i18nl18n

**Comment by jameshadfield** [comment]
This implementation is about half-way there already and @miparedes & I are going to get it complete & polished 😄

**Comment by jameshadfield** [comment]
Current master is almost complete, however the following strings are still missing. @miparedes when you have a moment could you add them (either as PR or just paste them into this issue, whichever's easiest). Note that 'rectangular' and 'radial' may be the same in Spanish?!?

```
ES: comparing sidebar.json against the English translation
        Following keys are present but are simply a copy of the English version & need to be translated:
                "rectangular"
                "radial"
ES: comparing translation.json against the English translation
        Following keys need to be added:
                "Filtered to"
                "Click on tip to display more info"
                "protein mutations truncated"
                "Date Confidence Interval"
                "Vaccine selected"
                "Vaccine start date"
                "Vaccine end date"
                "Serum strain"
                "Click outside this box to go back to the tree"
                "Authors"
                "Title"
                "Journal"
                "Projected frequency"
```

**Comment by miparedes** [comment]
Yup! '"rectangular" and "radial" is spelled the same in spanish as it is in English. A quick note, I think I translated "unrooted" as "sin base". I've been reading at little more phylogenetics in spanish and think that the translation "sin raíz" would be better. I can edit the file and push it but figured that posting here would be faster. 

“Resaltando”
“Haz clic en la punta del árbol para más información”
“Mutaciones proteicas truncadas”
“Intervalo de confianza de la fecha” (I’m translating this as meaning “the confidence interval of the date” but could do a better job with a little more context)
“Vacuna seleccionada” 
"Fecha de inicio de la vacuna"
"Fecha de finalización de la vacuna"
“Cepa del suero”
“Haz clic afuera de la casilla para regresar al árbol”
“Autores “
“Título”
“Publicación científica”
“Frecuencia proyectada” 

Let me know if anything else is needed!

**Comment by jameshadfield** [comment]
Added in 71492750e228420aab8ad7cc36b22e3d2b4e4ffb -- will release a new version of auspice / nextstrain.org today (hopefully)
