### ISSUE TITLE
[i18n] Translate Auspice to Portuguese

### ISSUE THREAD

**Issue by crwilcox** [nextstrain/auspice#989]
Following the guide at:
https://github.com/nextstrain/auspice/blob/master/DEV_DOCS.md#contributing-to-internationalization-and-localization-i18nl18n

**Comment by melissawm** [comment]
Hi all, I came here via the covid-oss-helpdesk discourse. I can do portuguese translations for Auspice. Just out of curiosity, is this a demand you have from users?

**Comment by jameshadfield** [comment]
Hi @melissawm -- that would be great! Portuguese is currently the ~9th most used language on nextstrain (tens of thousands of sessions) so the demand is there

**Comment by clouraa** [comment]
Hello, I did the internationalization to Portuguese based on the Spanish and English translations

**Comment by melissawm** [comment]
Oh ok. Seems I wasn't quick enough.

**Comment by clouraa** [comment]
Maybe you can review the translated files in my fork if you want :).

**Comment by jameshadfield** [comment]
Closed by #1017
