### ISSUE TITLE
[i18n] Translate Auspice to Italian

### ISSUE THREAD

**Issue by crwilcox** [nextstrain/auspice#990]
Following the guide at:
https://github.com/nextstrain/auspice/blob/master/DEV_DOCS.md#contributing-to-internationalization-and-localization-i18nl18n

**Comment by h-astephan** [comment]
Hi, could I be assigned to this?

**Comment by jameshadfield** [comment]
Thanks @h-astephan -- let me know if you run into any trouble & i'll try to help!
