### ISSUE TITLE
[i18n] Translate Auspice to Arabic

### ISSUE THREAD

**Issue by crwilcox** [nextstrain/auspice#991]
NOTE: this issue may require more work due to writing direction. Other languages have all been left-to-right

Following the guide at:
https://github.com/nextstrain/auspice/blob/master/DEV_DOCS.md#contributing-to-internationalization-and-localization-i18nl18n

**Comment by anouarh** [comment]
I'll take care of this one!

**Comment by SalehA74** [comment]
@anouarh You are most welcome...Would you like to share the translation of this week report to Arabic? Ahmad

**Comment by anouarh** [comment]
Finishing up, however not sure how to resolve issues that arise in sentences that contain english and arabic words.

**Comment by SalehA74** [comment]
Yes, that is a nightmare! We do translate every word to avoid this problem. 
I would like to suggest to do the next translations of situation reports in a certain template or fields where we do not need to deal with the links and codes... Hopefully that would be possible by @nextstrain/auspice and @cassiawag  soon. Regards

**Comment by jameshadfield** [comment]
Closed by #1104 (#1107)
