### ISSUE TITLE
Incorrect dates in the header info display when no tip nodes are in the date selection

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#999]
Some date selections (via the sidebar date slider) result in the header-info-line showing incorrect dates:

![image](https://user-images.githubusercontent.com/8350992/77606767-596afb80-6f7d-11ea-929c-b767042647f1.png)

Note that the URL dates & dates in the sidebar under the slider are correct. The incorrect dates in the info-line are the starting values for the `reduce` call inside `getVisibleDateRange`. It looks like this bug is being triggered when no tips are visible (i.e. the date slider has removed them all from the selection), thus no nodes are passed to the `reduce` call.

**Comment by wsuchy** [comment]
I would like to work on that issue, please assign it to me.

**Comment by jameshadfield** [comment]
Closed by #1011
